import {test,expect,type Page} from '@playwright/test';
const DEV='http://127.0.0.1:5174';
const setup=(page:Page)=>page.locator('#new-document-dialog');
async function finish(page:Page){await setup(page).getByRole('button',{name:'Create document',exact:true}).click();await expect(page.locator('#workspace')).not.toHaveAttribute('inert','');}
async function preferences(page:Page){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('tab',{name:'Grid',exact:true}).click();}
test('Machine and sticker presets create measured workspaces with editable document grids',async({page})=>{
 await page.goto(DEV);const dialog=setup(page);
 await expect(dialog.getByRole('tab',{name:'Machine beds',exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'600 × 400 mm',exact:true}).click();
 await dialog.getByLabel('Grid pattern',{exact:true}).selectOption('polar');await dialog.getByLabel('Grid size (mm)',{exact:true}).fill('2.5');await dialog.getByLabel('Spoke angle',{exact:true}).selectOption('30');await finish(page);
 await expect(page.locator('#grid-status')).toHaveText('Polar (Radial) 2.5 mm · 30°');
 await preferences(page);await expect(page.locator('#pref-grid-size')).toHaveValue('2.5');await expect(page.locator('#pref-grid-type')).toHaveValue('polar');await expect(page.locator('#pref-grid-angle')).toHaveValue('30');
 await page.locator('#pref-grid-type').selectOption('dot');await page.locator('#pref-grid-size').fill('5');await page.locator('#pref-grid-size').press('Tab');await page.locator('#preferences-close').click();await expect(page.locator('#grid-status')).toHaveText('Dot (Step) 5 mm');
 await page.getByRole('button',{name:'New document tab',exact:true}).click();await dialog.getByRole('tab',{name:'Sticker sheets',exact:true}).click();await dialog.getByRole('button',{name:'US Letter',exact:true}).click();await dialog.getByLabel('Grid pattern',{exact:true}).selectOption('square');await dialog.getByLabel('Grid size (mm)',{exact:true}).fill('1');await finish(page);
 expect(await page.evaluate(()=>(window as any).__vectora.canvasSize)).toEqual({kind:'fixed',width:215.9,height:279.4,unit:'in'});
 await page.getByRole('tab',{name:'Untitled.vectora, unsaved changes',exact:true}).click();await expect(page.locator('#grid-status')).toHaveText('Dot (Step) 5 mm');await preferences(page);await expect(page.locator('#pref-grid-size')).toHaveValue('5');await expect(page.locator('#pref-grid-type')).toHaveValue('dot');
});
test('Grid edits round-trip with documents, recovery and undo without changing artwork or exports',async({page})=>{
 await page.goto(DEV);await setup(page).getByLabel('Grid pattern',{exact:true}).selectOption('hexagonal');await setup(page).getByLabel('Grid size (mm)',{exact:true}).fill('7');await finish(page);
 const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts' as string),{exportSVG}=await import('/src/exportSVG.ts' as string);e.addShape(new p.Path.Rectangle({insert:false,rectangle:[10,10,30,20],strokeColor:'white',strokeWidth:1.5,strokeScaling:false}),'Keep');const art=e.snapshot().artwork,svg=exportSVG(e.objects);e.setGridType('polar');e.setGridAngle(45);const file=encodeDocument(e),decoded=await decodeDocument(file);e.undo();const undone=e.snapshot().grid;e.redo();const redone=e.snapshot().grid;const legacy=JSON.parse(file);delete legacy.grid;const old=await decodeDocument(JSON.stringify(legacy));let rejected=0;for(const grid of [{type:'polar',spacing:0,angle:45},{type:'bad',spacing:7,angle:15},{type:'square',spacing:7,angle:17}]){try{await decodeDocument(JSON.stringify({...legacy,grid}));}catch{rejected++;}}return {file,grid:decoded.snapshot.grid,undone,redone,old:old.snapshot.grid,rejected,artPreserved:art===e.snapshot().artwork,svgPreserved:svg===exportSVG(e.objects)};});
 expect(result.grid).toEqual({type:'polar',spacing:7,angle:45});expect(result.undone).toEqual({type:'polar',spacing:7,angle:15});expect(result.redone).toEqual(result.grid);expect(result.old).toEqual({type:'square',spacing:10,angle:15});expect(result.rejected).toBe(3);expect(result.artPreserved&&result.svgPreserved).toBe(true);
 await page.locator('#open-document-file').setInputFiles({name:'Grid.vectora',mimeType:'application/json',buffer:Buffer.from(result.file)});await expect(page.locator('[data-document-name]')).toHaveText('Grid.vectora');await expect(page.locator('#grid-status')).toHaveText('Polar (Radial) 7 mm · 45°');page.once('dialog',d=>d.accept());await page.reload();await expect(page.locator('#workspace')).not.toHaveAttribute('inert','');await expect(setup(page)).toBeHidden();await expect(page.locator('#grid-status')).toHaveText('Polar (Radial) 7 mm · 45°');
});
test('Setup validates grids, supports No grid and cancellation, and fits both themes',async({page})=>{
 await page.goto(DEV);const dialog=setup(page);await dialog.getByLabel('Grid size (mm)',{exact:true}).fill('0');await dialog.getByRole('button',{name:'Create document',exact:true}).click();await expect(dialog).toBeVisible();await dialog.getByLabel('Grid pattern',{exact:true}).selectOption('none');await expect(dialog.getByLabel('Grid size (mm)',{exact:true})).toBeHidden();await finish(page);await expect(page.locator('#grid-status')).toHaveText('No grid');
 await page.getByRole('button',{name:'New document tab',exact:true}).click();await dialog.getByLabel('Grid pattern',{exact:true}).selectOption('triangular');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('.document-tab')).toHaveCount(1);await expect(page.locator('#grid-status')).toHaveText('No grid');
 await page.getByRole('button',{name:'New document tab',exact:true}).click();for(const width of [1280,375]){await page.setViewportSize({width,height:650});for(const theme of ['dark','light']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await dialog.getByRole('tab',{name:'Sticker sheets',exact:true}).click();await dialog.getByRole('button',{name:'A4',exact:true}).click();await dialog.getByLabel('Grid pattern',{exact:true}).selectOption('polar');await dialog.getByLabel('Grid size (mm)',{exact:true}).fill('2');await dialog.getByLabel('Spoke angle',{exact:true}).selectOption('45');const box=(await dialog.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width);await expect(dialog.getByRole('button',{name:'Create document',exact:true})).toBeInViewport();await page.screenshot({path:`test-results/canvas-presets-${theme}-${width}.png`});}}
});
