import {test,expect,Page} from '@playwright/test';
const DEV='http://127.0.0.1:5174';
async function setup(page:Page,points:number[][],closed=false){await page.goto(DEV);await page.evaluate(({points,closed})=>{const e=(window as any).__vectora,p=(window as any).__paper;e.addShape(new p.Path({insert:false,segments:points,closed,strokeColor:'white',strokeWidth:1.5,strokeScaling:false}),'Corners');}, {points,closed});await page.getByRole('button',{name:'Node editing',exact:true}).click();}
async function at(page:Page,index:number){return page.evaluate(i=>{const e=(window as any).__vectora,p=(window as any).__paper,path=e.objects[0],q=p.view.projectToView(path.localToGlobal(path.segments[i].point));return {x:q.x,y:q.y};},index);}
async function selectNode(page:Page,index:number,shift=false){const p=await at(page,index);if(shift)await page.keyboard.down('Shift');await page.mouse.click(p.x,p.y);if(shift)await page.keyboard.up('Shift');}
async function open(page:Page,index:number,kind:'Fillet'|'Chamfer'){const p=await at(page,index);await page.mouse.click(p.x,p.y,{button:'right'});const button=page.getByRole('menuitem',{name:kind,exact:true});await expect(button).toHaveCount(1);await button.click();const d=page.locator('#corner-dialog');await expect(d).toBeVisible();return d;}
const snapshot=(page:Page)=>page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()));

test('Fillet uses an exact radius with tangent joins, preview isolation and one-step undo',async({page})=>{
 await setup(page,[[40,60],[40,40],[60,40]]);await selectNode(page,1);const before=await snapshot(page),d=await open(page,1,'Fillet');await d.getByRole('spinbutton',{name:'Radius mm',exact:true}).fill('5');expect(await snapshot(page)).toBe(before);expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.some((s:any)=>s.data.control==='corner-preview'))).toBe(true);await d.getByRole('button',{name:'Apply',exact:true}).click();
 const r=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,s=e.objects[0],curve=s.curves[1],q=curve.getPointAtTime(.5);return {points:s.segments.map((s:any)=>[s.point.x,s.point.y]),radius:q.getDistance(new p.Point(45,45)),tangent0:curve.getTangentAtTime(0).normalize().toJSON(),tangent1:curve.getTangentAtTime(1).normalize().toJSON(),closed:s.closed};});expect(r.points).toEqual([[40,60],[40,45],[45,40],[60,40]]);expect(r.radius).toBeCloseTo(5,8);expect(r.closed).toBe(false);expect(r.tangent0).toEqual(['Point',0,-1]);expect(r.tangent1).toEqual(['Point',1,0]);
 await page.keyboard.press('Control+z');expect(await snapshot(page)).toBe(before);await page.keyboard.press('Control+Shift+z');expect(await snapshot(page)).not.toBe(before);await expect(page.locator('#properties-panel')).toBeHidden();
});

test('Shift-selected corners chamfer together and reject overlap without changing the drawing',async({page})=>{
 await setup(page,[[40,40],[80,40],[80,70],[40,70]],true);await selectNode(page,0);await selectNode(page,1,true);const before=await snapshot(page),d=await open(page,0,'Chamfer');await expect(d.locator('.corner-count')).toContainText('2 corners');await d.getByRole('spinbutton',{name:'Distance mm',exact:true}).fill('21');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();await expect(d.locator('.corner-feedback')).toContainText('overlap');expect(await snapshot(page)).toBe(before);await d.getByRole('spinbutton',{name:'Distance mm',exact:true}).fill('8');await d.getByRole('button',{name:'Apply',exact:true}).click();
 const result=await page.evaluate(()=>{const s=(window as any).__vectora.objects[0];return {closed:s.closed,points:s.segments.map((s:any)=>[s.point.x,s.point.y]),straight:s.curves.every((c:any)=>c.isStraight())};});expect(result).toEqual({closed:true,points:[[40,48],[48,40],[72,40],[80,48],[80,70],[40,70]],straight:true});await page.keyboard.press('Control+z');expect(await snapshot(page)).toBe(before);
});

test('Cancel, Escape and invalid input leave no geometry or history changes; endpoints and curves are disabled',async({page})=>{
 await setup(page,[[40,60],[40,40],[60,40]]);await selectNode(page,1);const before=await snapshot(page),d=await open(page,1,'Fillet');await d.getByRole('spinbutton',{name:'Radius mm',exact:true}).fill('0');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();await page.keyboard.press('Escape');expect(await snapshot(page)).toBe(before);await expect(d).toBeHidden();await open(page,1,'Chamfer');await d.getByRole('button',{name:'Cancel',exact:true}).click();expect(await snapshot(page)).toBe(before);
 const end=await at(page,0);await page.mouse.click(end.x,end.y,{button:'right'});await expect(page.getByRole('menuitem',{name:'Fillet',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.objects[0].segments[1].handleOut=new p.Point(5,5);});const c=await at(page,1);await page.mouse.click(c.x,c.y,{button:'right'});await expect(page.getByRole('menuitem',{name:'Chamfer',exact:true})).toBeDisabled();
});

test('Geometry handles concave turns, touching fillets and physical millimetres through transforms',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{
  const p=(window as any).__paper,{editCorners}=await import('/src/cornerGeometry.ts'),{documentPath}=await import('/src/deletion.ts');
  const rect=new p.Path({insert:false,segments:[[0,0],[20,0],[20,20],[0,20]],closed:true}),rounded=editCorners(rect,[0,1,2,3],'fillet',10);
  const concave=new p.Path({insert:false,segments:[[0,0],[40,0],[40,20],[20,20],[20,40],[0,40]],closed:true}),inside=editCorners(concave,[3],'fillet',5),arc=inside.curves[3];
  const transformed=new p.Path({insert:false,segments:[[0,20],[0,0],[20,0]],applyMatrix:false});transformed.scale(2,3);transformed.rotate(27);const original=transformed.exportJSON(),edited=editCorners(transformed,[1],'fillet',4),world=documentPath(transformed),a=edited.segments[1].point,b=edited.segments[2].point,vertex=world.segments[1].point;
  const curved=new p.Path({insert:false,segments:[[0,20],[0,0],[20,0],[30,10]]});curved.segments[2].handleOut=[4,0];curved.segments[3].handleIn=[0,-4];const untouched=curved.curves[2].values,partial=editCorners(curved,[1],'chamfer',3);
  return {touching:{count:rounded.segments.length,closed:rounded.closed,nonzero:rounded.curves.every((c:any)=>c.length>1),bounds:[rounded.bounds.width,rounded.bounds.height],area:rounded.area},concave:{points:inside.segments.map((s:any)=>[s.point.x,s.point.y]),radius:arc.getPointAtTime(.5).getDistance(new p.Point(25,25)),t0:arc.getTangentAtTime(0).toJSON(),t1:arc.getTangentAtTime(1).toJSON()},transform:{a:a.getDistance(vertex),b:b.getDistance(vertex),unchanged:original===transformed.exportJSON()},untouched:JSON.stringify(untouched)===JSON.stringify(partial.lastCurve.values)};
 });
 expect(result.touching.count).toBe(4);expect(result.touching.closed).toBe(true);expect(result.touching.nonzero).toBe(true);expect(result.touching.bounds).toEqual([20,20]);expect(result.touching.area).toBeCloseTo(Math.PI*100,0);expect(result.concave.points).toEqual([[0,0],[40,0],[40,20],[25,20],[20,25],[20,40],[0,40]]);expect(result.concave.radius).toBeCloseTo(5,8);expect(result.concave.t0).toEqual(['Point',-1,0]);expect(result.concave.t1).toEqual(['Point',0,1]);expect(result.transform.a).toBeCloseTo(4,8);expect(result.transform.b).toBeCloseTo(4,8);expect(result.transform.unchanged).toBe(true);expect(result.untouched).toBe(true);
});

test('Applying to a transformed compound preserves other contours, layer, style and saved geometry',async({page})=>{
 await setup(page,[[40,60],[40,40],[70,40]]);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,a=e.objects[0];e.addShape(new p.Path.Circle({insert:false,center:[100,60],radius:10,strokeColor:'white',strokeWidth:1.5,strokeScaling:false}),'Other');e.select(a,true);e.joinSelection();e.moveSelectionToCutPath();const s=e.selected;s.applyMatrix=false;s.scale(1.3,.8);s.rotate(15);});
 const data=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,o=e.objects[0],path=o.children.find((c:any)=>!c.closed),q=p.view.projectToView(path.localToGlobal(path.segments[1].point));return {x:q.x,y:q.y,other:o.children.find((c:any)=>c.closed).exportJSON(),matrix:o.matrix.values,style:[o.strokeColor?.toCSS(true),o.fillColor?.toCSS(true),o.strokeWidth,o.strokeScaling],layer:o.layer.data.documentId,vertex:[path.localToGlobal(path.segments[1].point).x,path.localToGlobal(path.segments[1].point).y]};});
 await page.mouse.click(data.x,data.y,{button:'right'});await page.getByRole('menuitem',{name:'Fillet',exact:true}).click();await page.locator('#corner-dialog input').fill('4');await page.locator('#corner-dialog').getByRole('button',{name:'Apply',exact:true}).click();
 const after=await page.evaluate(async()=>{const e=(window as any).__vectora,{documentPath}=await import('/src/deletion.ts'),s=e.objects[0],path=documentPath(s.children.find((c:any)=>!c.closed)),snapshot=e.snapshot();e.restore(snapshot);return {other:s.children.find((c:any)=>c.closed).exportJSON(),matrix:s.matrix.values,style:[s.strokeColor?.toCSS(true),s.fillColor?.toCSS(true),s.strokeWidth,s.strokeScaling],layer:e.objects[0].layer.data.documentId,points:path.segments.map((n:any)=>[n.point.x,n.point.y]),saved:e.objects[0].children.find((c:any)=>!c.closed).segments.length,role:e.objects[0].data.role};});
 expect(after.other).toBe(data.other);expect(after.matrix).toEqual(data.matrix);expect(after.style).toEqual(data.style);expect(after.layer).toBe(data.layer);expect(after.saved).toBe(4);expect(after.role).toBe('cutline');for(const i of [1,2])expect(Math.hypot(after.points[i][0]-data.vertex[0],after.points[i][1]-data.vertex[1])).toBeCloseTo(4,8);
});

test('Corner search, cancellation and dialog layout work in both themes and narrow windows',async({page})=>{
 await setup(page,[[40,60],[40,40],[70,40]]);await selectNode(page,1);const before=await snapshot(page);
 await page.getByRole('button',{name:'Search tools',exact:true}).click();await page.getByRole('combobox',{name:'Search tools'}).fill('Fillet');await page.keyboard.press('Enter');const d=page.locator('#corner-dialog');await expect(d).toBeVisible();
 for(const theme of ['dark','light']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({path:`test-results/fillet-${theme}.png`});}
 await page.setViewportSize({width:390,height:650});await page.screenshot({path:'test-results/fillet-mobile.png'});const box=await d.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(390);expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.y+box!.height).toBeLessThanOrEqual(650);
 await page.setViewportSize({width:900,height:300});const short=await d.boundingBox();expect(short!.y).toBeGreaterThanOrEqual(0);expect(short!.y+short!.height).toBeLessThanOrEqual(300);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(d).toBeHidden();expect(await snapshot(page)).toBe(before);expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.some((s:any)=>s.data.control==='corner-preview'))).toBe(false);
});

test('Corners on multiple layers validate atomically and export only applied geometry',async({page})=>{
 await setup(page,[[30,50],[30,30],[60,30]]);await selectNode(page,1);
 const other=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,first=e.objects[0];e.addShape(new p.Path({insert:false,segments:[[90,45],[90,30],[105,30]],strokeColor:'white'}),'Second');e.moveSelectionToCutPath();e.select(first);return e.objects.find((s:any)=>s.data.name==='Second').data.uid;});
 await selectNode(page,1);const q=await page.evaluate(uid=>{const e=(window as any).__vectora,p=(window as any).__paper,s=e.objects.find((s:any)=>s.data.uid===uid),q=p.view.projectToView(s.segments[1].point);return {x:q.x,y:q.y};},other);await page.keyboard.down('Shift');await page.mouse.click(q.x,q.y);await page.keyboard.up('Shift');const before=await snapshot(page);
 const d=await open(page,1,'Fillet');await expect(d.locator('.corner-count')).toContainText('2 corners');await d.locator('input').fill('16');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();expect(await snapshot(page)).toBe(before);await d.locator('input').fill('5');
 const exported=()=>page.evaluate(async()=>{const e=(window as any).__vectora,{exportSVG}=await import('/src/exportSVG.ts');return exportSVG(e.objects);});const beforeExport=await exported();await d.getByRole('button',{name:'Apply',exact:true}).click();const afterExport=await exported();expect(afterExport).not.toBe(beforeExport);expect(await page.evaluate(svg=>[...new DOMParser().parseFromString(svg,'image/svg+xml').querySelectorAll('path')].every(path=>/[cC]/.test(path.getAttribute('d')??'')),afterExport)).toBe(true);expect(afterExport).not.toContain('corner-preview');expect(await page.evaluate(()=>(window as any).__vectora.objects.map((o:any)=>({n:o.segments.length,role:o.data.role})))).toEqual([{n:4,role:'artwork'},{n:4,role:'cutline'}]);await page.keyboard.press('Control+z');expect(await snapshot(page)).toBe(before);expect(await exported()).toBe(beforeExport);
});

test('An untouched curve loop with coincident anchors survives corner edits elsewhere',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{const p=(window as any).__paper,{editCorners}=await import('/src/cornerGeometry.ts'),source=new p.Path({insert:false,segments:[[0,20],[0,0],[20,0],[30,10],[30,10],[50,10]]});source.segments[3].handleOut=[0,10];source.segments[4].handleIn=[10,10];const loop=source.curves[3].values,length=source.curves[3].length,edited=editCorners(source,[1],'chamfer',3);return {count:edited.segments.length,loop:edited.curves[4].values,length:edited.curves[4].length,expected:loop,expectedLength:length};});expect(result.count).toBe(7);expect(result.loop).toEqual(result.expected);expect(result.length).toBeCloseTo(result.expectedLength,10);
});
