import {test,expect} from './fixtures';
import {writeFileSync} from 'node:fs';
const DEV='http://127.0.0.1:5174';
function records(text:string){const lines=text.trimEnd().split(/\r?\n/),out:{kind:string;tags:[number,string][]}[]=[];for(let i=0;i<lines.length;i+=2){const code=Number(lines[i]),value=lines[i+1];if(code===0)out.push({kind:value,tags:[]});else out.at(-1)?.tags.push([code,value]);}return out;}
const tag=(r:{tags:[number,string][]},n:number)=>r.tags.find(([c])=>c===n)?.[1];
test('Standard DXF preserves transformed circular contours with owned entities and origin-aware preview',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportDXF}=await import('/src/exportDXF.ts'),{createCircularArc}=await import('/src/arc.ts'),{previewDXF,dxfAtOrigin}=await import('/src/exportLayout.ts');e.newDocument();e.setActiveLayer('cutline');e.addShape(new p.Path.Circle({insert:false,center:[50,60],radius:20}),'Circle');e.addShape(createCircularArc({cx:100,cy:60,radius:10,start:0,sweep:270}),'Arc');const before=JSON.stringify(e.snapshot()),dxf=exportDXF(e.objects),origin=dxfAtOrigin(dxf);return {dxf,origin,preview:previewDXF(origin),laser:exportDXF(e.objects,false,'laser'),unchanged:before===JSON.stringify(e.snapshot())};});
 const rs=records(r.dxf),circle=rs.find(r=>r.kind==='CIRCLE')!,arc=rs.find(r=>r.kind==='ARC')!;expect(circle).toBeTruthy();expect([tag(circle,10),tag(circle,20),tag(circle,40)]).toEqual(['50','-60','20']);expect([tag(arc,50),tag(arc,51)]).toEqual(['90','0']);expect(r.unchanged).toBe(true);expect(r.laser).not.toMatch(/\r\n(?:CIRCLE|ARC)\r\n/);expect(r.preview).toContain('<circle');expect(r.preview).toContain('A 10 10');expect(r.preview).toContain('data-export-width="80"');expect(r.preview).toContain('data-export-height="40"');
 const handles=rs.flatMap(r=>tag(r,5)||tag(r,105)?[(tag(r,5)||tag(r,105))!]:[]);expect(new Set(handles).size).toBe(handles.length);for(const entity of [circle,arc])expect(handles).toContain(tag(entity,330));for(const table of rs.filter(r=>r.kind==='TABLE'))expect(tag(table,5)).toBeTruthy();expect(rs.some(r=>r.kind==='BLOCK_RECORD')).toBe(true);expect(rs.some(r=>r.kind==='LAYOUT')).toBe(true);expect(r.dxf).toContain('$EXTMIN');
 for(const layer of rs.filter(r=>r.kind==='LAYER')){expect(handles).toContain(tag(layer,390));expect(tag(layer,370)).toBe('-3');}
 const vp=rs.find(r=>r.kind==='VPORT')!;for(const code of [13,23,14,24,15,25,281,65,146])expect(tag(vp,code)).toBeDefined();
 const dimTable=rs.find(r=>r.kind==='TABLE'&&tag(r,2)==='DIMSTYLE')!;expect(dimTable.tags).toContainEqual([100,'AcDbDimStyleTable']);expect(rs.some(r=>r.kind==='DIMSTYLE'&&tag(r,2)==='Standard')).toBe(true);
 writeFileSync('test-results/standard-native.dxf',r.dxf);writeFileSync('test-results/standard-native-origin.dxf',r.origin);writeFileSync('test-results/laser-native-fallback.dxf',r.laser);
});
test('Noncircular edits flatten, exact transformed circles/arcs survive, and zero-area crossings remain',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportDXF}=await import('/src/exportDXF.ts'),{createCircularArc}=await import('/src/arc.ts');e.newDocument();e.setActiveLayer('cutline');const ellipse=new p.Path.Circle({insert:false,center:[10,20],radius:5});ellipse.scale(2,1);e.addShape(ellipse,'Ellipse');const edited=new p.Path.Circle({insert:false,center:[30,20],radius:5});edited.segments[0].handleOut.x+=.1;e.addShape(edited,'Edited');e.addShape(new p.Path({insert:false,closed:true,segments:[[0,0],[20,20],[0,20],[20,0]]}),'Crossing');const compound=new p.CompoundPath({insert:false,children:[new p.Path.Circle({insert:false,center:[50,50],radius:10}),new p.Path.Circle({insert:false,center:[50,50],radius:5})]});compound.applyMatrix=false;compound.scale(-2,2);compound.rotate(37);e.addShape(compound,'Ring');const arc=createCircularArc({cx:80,cy:30,radius:7,start:20,sweep:-120});arc.applyMatrix=false;arc.scale(-1,1);arc.rotate(30);e.addShape(arc,'Mirrored arc');const dxf=exportDXF(e.objects);let error='';try{exportDXF(e.objects,false,'standard',NaN);}catch(e){error=(e as Error).message;}return {dxf,error};});
 const rs=records(r.dxf);expect(rs.filter(r=>r.kind==='LWPOLYLINE')).toHaveLength(3);expect(rs.filter(r=>r.kind==='CIRCLE').map(r=>Number(tag(r,40))).sort((a,b)=>a-b)).toEqual([10,20]);expect(rs.filter(r=>r.kind==='ARC')).toHaveLength(1);expect(r.error).toMatch(/tolerance/i);writeFileSync('test-results/standard-transforms.dxf',r.dxf);
});
test('Standard writer accepts dense contours without argument-stack limits',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {standardDXF}=await import('/src/dxfDocument.ts');const tags:[number,string|number][]=[[100,'AcDbPolyline'],[90,30000],[70,0]];for(let i=0;i<30000;i++)tags.push([10,i],[20,i%10]);return standardDXF([{kind:'LWPOLYLINE',layer:'CUTLINE',tags}],new Map([['0',7],['CUTLINE',1]]),{minX:0,minY:0,maxX:29999,maxY:9});});expect(records(r).find(r=>r.kind==='LWPOLYLINE')!.tags.filter(([c])=>c===10)).toHaveLength(30000);
});
test('Native arc directions, three-point arcs, layer names and annotation records survive export',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportDXF}=await import('/src/exportDXF.ts'),{createCircularArc,createArc}=await import('/src/arc.ts'),{createDimension}=await import('/src/dimensions.ts');e.newDocument();e.setActiveLayer('cutline');const expected:any[]=[];
  for(const sweep of [-359,-180,-45,5,90,270,359]){const arc=createCircularArc({cx:200,cy:100,radius:12,start:35,sweep});arc.applyMatrix=false;arc.scale(-1.5,1.5);arc.rotate(23);e.addShape(arc,'Arc');const start=arc.localToGlobal(arc.firstSegment.point),end=arc.localToGlobal(arc.lastSegment.point);expected.push({sweep:Math.abs(sweep),points:[[start.x,-start.y],[end.x,-end.y]]});}
  const three=createArc(new p.Point(0,10),new p.Point(10,0),new p.Point(20,10));e.addShape(three,'Three point');const engraving=e.documentLayer('engrave');engraving.name='Cutline';engraving.data.documentId='custom-engrave';engraving.addChild(new p.Path.Rectangle({insert:false,rectangle:[0,0,5,5],data:{role:'engrave',uid:'test-mark',name:'Mark'}}));e.setActiveLayer('artwork');e.addShape(createDimension({kind:'leader',points:[[10,10],[20,20],[30,20]],text:'Ø 10 — check',transform:[1,0,0,1,0,0]}),'Note');return {dxf:exportDXF(e.objects,true),expected};});
 const rs=records(r.dxf),arcs=rs.filter(r=>r.kind==='ARC');expect(arcs).toHaveLength(8);for(let i=0;i<7;i++){const arc=arcs[i],start=Number(tag(arc,50)),end=Number(tag(arc,51)),cx=Number(tag(arc,10)),cy=Number(tag(arc,20)),radius=Number(tag(arc,40));expect(radius).toBeCloseTo(18,7);expect((end-start+360)%360).toBeCloseTo(r.expected[i].sweep,6);for(const angle of [start,end]){const x=cx+radius*Math.cos(angle*Math.PI/180),y=cy+radius*Math.sin(angle*Math.PI/180);expect(Math.min(...r.expected[i].points.map(([a,b]:number[])=>Math.hypot(x-a,y-b)))).toBeLessThan(1e-6);}}
 expect(rs.filter(r=>r.kind==='LAYER'&&tag(r,2)?.startsWith('CUTLINE')).map(r=>[tag(r,2),tag(r,62)])).toEqual([['CUTLINE','5'],['CUTLINE_2','1']]);const label=rs.find(r=>r.kind==='TEXT')!;expect(tag(label,7)).toBe('STANDARD');expect(tag(label,1)).toContain('%%c 10 \\U+2014 check');expect(tag(label,8)).toBe('ANNOTATIONS');writeFileSync('test-results/standard-arcs-labels.dxf',r.dxf);
});
