import {test,expect,Page} from './fixtures';
import {readFileSync} from 'node:fs';
const DEV='http://127.0.0.1:5174';
async function fixture(page:Page){await page.goto(DEV);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.newDocument();e.setActiveLayer('artwork');e.addShape(new p.Path.Rectangle({insert:false,rectangle:[20,30,50,25],strokeColor:'#ffffff',strokeWidth:1.5,strokeScaling:false}),'Artwork');e.setActiveLayer('cutline');e.addShape(new p.Path.Circle({insert:false,center:[120,80],radius:20}),'Cut');});}
async function open(page:Page,format='SVG'){await page.getByRole('button',{name:'File',exact:true}).click();await page.getByRole('menuitem',{name:'Export…',exact:true}).click();await page.getByRole('tab',{name:format==='Laser-compatible DXF'?'DXF':format,exact:true}).click();if(format==='Laser-compatible DXF')await page.getByLabel('Compatibility',{exact:true}).selectOption('laser');}
test('Unified export uses filename, selection and SVG margins without altering document',async({page})=>{
 await fixture(page);const before=await page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()));await open(page);const dialog=page.getByRole('dialog',{name:'Export',exact:true});await expect(dialog).toBeVisible();await dialog.getByLabel('Filename',{exact:true}).fill('My design');await dialog.getByLabel('Export area').selectOption('selection');await dialog.getByLabel('Margin (mm)',{exact:true}).fill('5');await dialog.getByLabel('Margin (mm)',{exact:true}).dispatchEvent('change');const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Export SVG',exact:true}).click();const file=await pending;expect(file.suggestedFilename()).toBe('My design.svg');const xml=readFileSync((await file.path())!,'utf8');expect(xml).toContain('data-layer-role="cutline"');expect(xml).not.toContain('data-layer-role="artwork"');expect(Number(xml.match(/width="([\d.]+)mm"/)![1])).toBeGreaterThan(50);expect(await page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()))).toBe(before);
});
test('PNG settings control pixels, background and retained settings',async({page})=>{
 await fixture(page);await open(page,'PNG');const d=page.locator('#export-dialog');await d.getByLabel('Width (px)',{exact:true}).fill('800');await d.getByLabel('Width (px)',{exact:true}).dispatchEvent('change');await d.getByLabel('Background',{exact:true}).selectOption('colour');await d.getByLabel('Background colour').fill('#ff0000');const pending=page.waitForEvent('download');await d.getByRole('button',{name:'Export PNG',exact:true}).click();const file=await pending,data=readFileSync((await file.path())!);expect(data.readUInt32BE(16)).toBe(800);await open(page,'PNG');await expect(d.getByLabel('Width (px)',{exact:true})).toHaveValue('800');await d.getByRole('button',{name:'Cancel',exact:true}).click();await expect(d).not.toBeVisible();
});
test('DXF origin and curve precision preserve scale and include chosen layers',async({page})=>{
 await fixture(page);await open(page,'Laser-compatible DXF');const d=page.locator('#export-dialog');await d.getByText('Advanced', {exact:true}).click();await d.getByLabel('Move to origin').check();await d.getByLabel('Curve tolerance (mm)').fill('0.1');await d.getByLabel('Curve tolerance (mm)').dispatchEvent('change');const pending=page.waitForEvent('download');await d.getByRole('button',{name:'Export DXF',exact:true}).click();const text=readFileSync((await (await pending).path())!,'utf8');expect(text).toContain('AC1009');expect(text).toContain('$EXTMIN\r\n10\r\n0\r\n20\r\n0');expect(text).not.toContain('ARTWORK');
});
test('PDF pages retain exact paper size and reject overflow; SVG defaults follow the chosen area',async({page})=>{
 await fixture(page);await open(page,'PDF');const d=page.locator('#export-dialog');await d.getByLabel('Page size',{exact:true}).selectOption('a4');await d.getByLabel('Orientation',{exact:true}).selectOption('landscape');const pending=page.waitForEvent('download');await d.getByRole('button',{name:'Export PDF',exact:true}).click();const raw=readFileSync((await (await pending).path())!,'latin1'),box=raw.match(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]/)!;expect(Number(box[1])*25.4/72).toBeCloseTo(297,3);expect(Number(box[2])*25.4/72).toBeCloseTo(210,3);
 await open(page,'PDF');await d.getByLabel('Scale (%)').fill('1000');await d.getByLabel('Scale (%)').dispatchEvent('change');await expect(d.locator('.export-error')).toContainText('does not fit');await expect(d.locator('[data-export-submit]')).toBeDisabled();await d.getByRole('tab',{name:'SVG',exact:true}).click();await d.getByLabel('Export area').selectOption('selection');expect(Number(await d.getByLabel('Width (mm)',{exact:true}).inputValue())).toBeLessThan(41);
});
test('Hidden layers are opt-in for images, invalid settings do not export, and keyboard closes to File',async({page})=>{
 await fixture(page);await page.evaluate(()=>{const e=(window as any).__vectora;e.setLayerState('artwork','visible',false);});await open(page);const d=page.locator('#export-dialog');await d.getByText('Advanced',{exact:true}).click();await expect(d.getByLabel('Artwork',{exact:true})).not.toBeChecked();await d.getByLabel('Artwork',{exact:true}).check();const pending=page.waitForEvent('download');await d.locator('[data-export-submit]').click();expect(readFileSync((await (await pending).path())!,'utf8')).toContain('data-layer-role="artwork"');await open(page,'DXF');await d.getByText('Advanced',{exact:true}).click();await d.getByLabel('Curve tolerance (mm)').fill('-1');await d.getByLabel('Curve tolerance (mm)').dispatchEvent('change');await expect(d.locator('[data-export-submit]')).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'File',exact:true})).toBeFocused();
});
test('Cancel prevents a pending PNG conversion from downloading after close',async({page})=>{
 await fixture(page);await page.evaluate(()=>{const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(callback,type,quality){return original.call(this,blob=>setTimeout(()=>callback(blob),600),type,quality);};});await open(page,'PNG');let downloads=0;page.on('download',()=>downloads++);await page.locator('#export-dialog [data-export-submit]').click();await page.locator('#export-dialog [data-export-cancel]').click();await page.waitForTimeout(900);expect(downloads).toBe(0);await expect(page.locator('#export-dialog')).not.toBeVisible();
});
test('Export dialog remains reachable in both themes on desktop and narrow screens',async({page})=>{
 await fixture(page);for(const theme of ['dark','light']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const [width,height] of [[1280,900],[390,550]]){await page.setViewportSize({width,height});await open(page,'SVG');const d=page.locator('#export-dialog');await expect(d.locator('[data-export-submit]')).toBeInViewport();await page.getByRole('tab',{name:'PDF',exact:true}).click();await page.screenshot({path:`test-results/export-dialog-${theme}-${width}.png`,scale:'css'});await d.locator('[data-export-cancel]').click();}}
});
test('Correcting an empty filename restores export after other settings change',async({page})=>{
 await fixture(page);await open(page);const d=page.locator('#export-dialog');await d.getByLabel('Filename',{exact:true}).fill('');await d.getByLabel('Margin (mm)').fill('2');await d.getByLabel('Margin (mm)').dispatchEvent('change');await expect(d.locator('[data-export-submit]')).toBeDisabled();await d.getByLabel('Filename',{exact:true}).fill('Fixed');await expect(d.locator('[data-export-submit]')).toBeEnabled();
});
test('Dense DXF previews remain responsive and frame annotation labels',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{const {previewDXF}=await import('/src/exportLayout.ts');const vertices=Array.from({length:30000},(_,i)=>`10\n${i}\n20\n${i%10}\n`).join('');const start=performance.now();previewDXF(`0\nSECTION\n2\nENTITIES\n0\nLWPOLYLINE\n70\n0\n${vertices}0\nENDSEC\n0\nEOF\n`);const elapsed=performance.now()-start;const svg=previewDXF('0\nSECTION\n2\nENTITIES\n0\nTEXT\n10\n0\n20\n0\n40\n3\n1\nA long annotation label\n0\nENDSEC\n0\nEOF\n');return {elapsed,view:new DOMParser().parseFromString(svg,'image/svg+xml').documentElement.getAttribute('viewBox')!.split(' ').map(Number)};});expect(result.elapsed).toBeLessThan(1000);expect(result.view[2]).toBeGreaterThan(20);expect(result.view[3]).toBeGreaterThan(2);
});
test('Lowering DPI recovers from an oversized automatic PNG resolution',async({page})=>{
 await fixture(page);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.setActiveLayer('artwork');e.addShape(new p.Path.Rectangle({insert:false,rectangle:[0,0,10000,10000],strokeColor:'white'}),'Huge');});await open(page,'PNG');const d=page.locator('#export-dialog');await expect(d.locator('[data-export-submit]')).toBeDisabled();await d.getByLabel('Resolution (DPI)').fill('1');await d.getByLabel('Resolution (DPI)').dispatchEvent('change');await expect(d.locator('[data-export-submit]')).toBeEnabled();expect(Number(await d.getByLabel('Width (px)').inputValue())).toBeLessThan(400);
});
test('DXF size readout excludes preview-only stroke padding',async({page})=>{
 await fixture(page);await open(page,'Laser-compatible DXF');await expect(page.locator('#export-dialog [data-export-size]')).toHaveText('40.00 × 40.00 mm');
});
test('Empty size inputs stay invalid until corrected',async({page})=>{
 await fixture(page);await open(page);const d=page.locator('#export-dialog');await d.getByLabel('Width (mm)').fill('');await d.getByLabel('Width (mm)').dispatchEvent('change');await expect(d.locator('[data-export-submit]')).toBeDisabled();await d.getByLabel('Width (mm)').fill('50');await d.getByLabel('Width (mm)').dispatchEvent('change');await expect(d.locator('[data-export-submit]')).toBeEnabled();await d.getByRole('tab',{name:'PNG',exact:true}).click();await d.getByLabel('Width (px)').fill('');await d.getByLabel('Width (px)').dispatchEvent('change');await expect(d.locator('[data-export-submit]')).toBeDisabled();
});
test('One DXF tab switches compatibility modes without losing shared settings',async({page})=>{
 await fixture(page);await open(page,'DXF');const d=page.locator('#export-dialog');await expect(d.getByRole('tab')).toHaveCount(4);const compatibility=d.getByLabel('Compatibility',{exact:true});await expect(compatibility).toHaveValue('standard');await d.getByText('Advanced',{exact:true}).click();await d.getByLabel('Move to origin').check();await d.getByLabel('Artwork',{exact:true}).check();await compatibility.selectOption('laser');await expect(d.locator('.export-format-hint')).toContainText('choose millimetres');await expect(d.getByLabel('Move to origin')).toBeChecked();await expect(d.getByLabel('Artwork',{exact:true})).toBeChecked();let pending=page.waitForEvent('download');await d.getByRole('button',{name:'Export DXF',exact:true}).click();expect(readFileSync((await (await pending).path())!,'utf8')).toContain('AC1009');await open(page,'DXF');await expect(compatibility).toHaveValue('laser');await compatibility.selectOption('standard');pending=page.waitForEvent('download');await d.getByRole('button',{name:'Export DXF',exact:true}).click();expect(readFileSync((await (await pending).path())!,'utf8')).toContain('AC1015');await open(page,'DXF');await d.getByRole('tab',{name:'DXF',exact:true}).focus();await page.keyboard.press('ArrowDown');await expect(d.getByRole('tab',{name:'PNG',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(d.getByRole('tab',{name:'DXF',exact:true})).toBeFocused();
});
