import {test,expect,type Page} from './fixtures';
const DEV='http://127.0.0.1:5174';
async function ready(page:Page){await page.goto(DEV);await expect(page.locator('#workspace')).not.toHaveAttribute('inert','');}
async function draw(page:Page){return page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.addShape(new p.Path.Rectangle({insert:false,rectangle:[10,20,40,30],strokeColor:e.drawingColor}),'Box');e.select(null);});}
async function fill(page:Page){await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.fillAt(new p.Point(25,35));});}
test('Appearance tabs choose solid, gradient and pattern paints for Fill without editing on tab change',async({page})=>{
 await ready(page);await draw(page);await page.getByRole('button',{name:'Fill & appearance',exact:true}).click();const panel=page.getByRole('region',{name:'Fill & appearance',exact:true});await expect(panel.getByRole('tab')).toHaveCount(3);
 await panel.getByRole('tab',{name:'Gradient',exact:true}).click();await expect(panel.getByRole('tabpanel',{name:'Gradient',exact:true})).toBeVisible();await fill(page);expect(await page.evaluate(()=>(window as any).__vectora.selected.fillColor.type)).toBe('gradient');
 const before=await page.evaluate(()=>(window as any).__vectora.snapshot());await panel.getByRole('tab',{name:'Pattern',exact:true}).click();expect(await page.evaluate(()=>(window as any).__vectora.snapshot())).toEqual(before);
 await fill(page);expect(await page.evaluate(()=>(window as any).__vectora.selected.data.fillPaint.kind)).toBe('pattern');await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await page.evaluate(()=>(window as any).__vectora.selected.data.fillPaint.kind)).toBe('gradient');
});
test('Gradient stops, pattern settings and opacity survive documents and SVG/PNG/PDF export',async({page})=>{
 await ready(page);await draw(page);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper;const {encodeDocument,decodeDocument}=await import('/src/documentFormat.ts' as string),{exportSVG}=await import('/src/exportSVG.ts' as string),{exportPNG}=await import('/src/exportImage.ts' as string),{exportPDF}=await import('/src/exportPDF.ts' as string);
 e.setFillPaint({kind:'gradient',type:'radial',angle:30,opacity:.6,stops:[{colour:'#FF0000',offset:0,opacity:1},{colour:'#00FF00',offset:.4,opacity:.5},{colour:'#0000FF',offset:1,opacity:1}]});e.fillAt(new p.Point(25,35));
 const gradient=e.selected.data.fillPaint;const data=await decodeDocument(encodeDocument(e));e.loadDocument(data.snapshot,data.view);const restored=e.objects.find((s:any)=>s.data.regionFill),svg=exportSVG(e.objects);const parsed=new DOMParser().parseFromString(svg,'image/svg+xml');const stops=parsed.querySelectorAll('radialGradient stop').length;
 e.select(restored);e.setFillPaint({kind:'pattern',type:'dots',foreground:'#112233',background:'#FFFFFF',transparent:false,size:4,angle:30,detail:25,opacity:.7},true);
 const patternSVG=exportSVG(e.objects),png=await exportPNG(patternSVG,{width:100}),pdf=await exportPDF(patternSVG);const again=await decodeDocument(encodeDocument(e));e.loadDocument(again.snapshot,again.view);return {gradient,restored:restored.data.fillPaint,stops,pattern:e.objects.find((s:any)=>s.data.regionFill).data.fillPaint,svg:patternSVG,png:png.size,pdf:pdf.size};});
 expect(result.gradient.stops).toHaveLength(3);expect(result.stops).toBe(3);expect(result.pattern).toMatchObject({kind:'pattern',type:'dots',size:4,angle:30,opacity:.7});expect(result.svg).toContain('<pattern');expect(result.png).toBeGreaterThan(100);expect(result.pdf).toBeGreaterThan(100);
});

test('Pattern pixels repeat and stay attached through transforms and document reload',async({page})=>{
 await ready(page);await draw(page);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts' as string);
 const sample=(x:number,y:number)=>{p.view.update();const pos=p.view.projectToView(new p.Point(x,y)),canvas=p.view.element,ratio=canvas.width/p.view.viewSize.width;return [...canvas.getContext('2d').getImageData(Math.round(pos.x*ratio),Math.round(pos.y*ratio),1,1).data].slice(0,3);};
 e.setFillPaint({kind:'pattern',type:'checkerboard',foreground:'#FF0000',background:'#FFFFFF',transparent:false,size:10,angle:0,detail:25,opacity:1});e.fillAt(new p.Point(25,35));e.select(null);const original=[sample(12,22),sample(17,22),sample(22,22)];
 const shape=e.objects.find((s:any)=>s.data.regionFill);shape.translate(new p.Point(20,10));e.refreshTheme();const moved=[sample(32,32),sample(37,32),sample(42,32)];
 const doc=await decodeDocument(encodeDocument(e));e.loadDocument(doc.snapshot,doc.view);e.select(null);return {original,moved,restored:[sample(32,32),sample(37,32),sample(42,32)]};});
 expect(result.original).toEqual([[255,0,0],[255,255,255],[255,0,0]]);expect(result.moved).toEqual(result.original);expect(result.restored).toEqual(result.original);
});

test('Controls, keyboard tabs and previews fit both themes and the reference',async({page,context})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);await draw(page);await page.getByRole('button',{name:'Fill & appearance',exact:true}).click();const panel=page.locator('#colour-panel');await panel.getByRole('tab',{name:'Gradient',exact:true}).click();
 await panel.getByRole('textbox',{name:'Stop 1 colour',exact:true}).fill('#112233');await panel.getByRole('textbox',{name:'Stop 1 colour',exact:true}).press('Enter');await panel.getByRole('button',{name:'Add gradient stop',exact:true}).click();await expect(panel.locator('[data-stop]')).toHaveCount(3);await fill(page);expect(await page.evaluate(()=>(window as any).__vectora.selected.data.fillPaint.stops[0].colour)).toBe('#112233');
 await panel.getByRole('button',{name:'Remove stop 2',exact:true}).click();await expect(panel.locator('[data-stop]')).toHaveCount(2);await panel.getByRole('combobox',{name:'Gradient type',exact:true}).selectOption('radial');await expect(panel.getByRole('spinbutton',{name:'Gradient angle (°)',exact:true})).toBeDisabled();await page.screenshot({path:'test-results/appearance-gradient-dark.png'});
 await panel.getByRole('tab',{name:'Gradient',exact:true}).focus();await page.keyboard.press('ArrowRight');await expect(panel.getByRole('tab',{name:'Pattern',exact:true})).toHaveAttribute('aria-selected','true');
 for(const type of ['stripes','crosshatch','dots','checkerboard']){await panel.getByRole('combobox',{name:'Pattern type',exact:true}).selectOption(type);expect(await page.evaluate(()=>(window as any).__vectora.fillPaint.type)).toBe(type);}
 await panel.getByRole('checkbox',{name:'Transparent background',exact:true}).uncheck();await panel.getByRole('textbox',{name:'Background colour',exact:true}).fill('#EEEEEE');await panel.getByRole('textbox',{name:'Background colour',exact:true}).press('Enter');await page.screenshot({path:'test-results/appearance-pattern-dark.png'});
 await page.evaluate(()=>{document.documentElement.dataset.theme='light';(window as any).__vectora.refreshTheme();});await page.screenshot({path:'test-results/appearance-pattern-light.png'});
 for(const width of [600,375]){await page.setViewportSize({width,height:650});for(const tab of ['Colour','Gradient','Pattern']){await panel.getByRole('tab',{name:tab,exact:true}).click();expect(await panel.locator('.appearance-page:visible').evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(false);const scroll=panel.locator('.appearance-page:visible > div');expect(await scroll.evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(false);}}
 const ref=await context.newPage();ref.on('pageerror',e=>errors.push(e.message));await ref.goto(DEV+'/reference/design-system.html');await ref.getByRole('button',{name:'Fill & appearance',exact:true}).click();await ref.getByRole('tab',{name:'Gradient',exact:true}).click();await expect(ref.locator('[data-paint-preview="gradient"] svg linearGradient')).toHaveCount(1);await ref.close();expect(errors).toEqual([]);
});

test('Pattern PNGs preserve foreground, background and opacity; previews do not inherit icon strokes',async({page})=>{
 await ready(page);await draw(page);await page.getByRole('button',{name:'Fill & appearance',exact:true}).click();await page.getByRole('tab',{name:'Pattern',exact:true}).click();expect(await page.locator('[data-paint-preview="pattern"] svg').evaluate(el=>getComputedStyle(el).stroke)).toBe('none');
 const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportSVG}=await import('/src/exportSVG.ts' as string),{exportPNG}=await import('/src/exportImage.ts' as string),{exportPDF}=await import('/src/exportPDF.ts' as string);const samples=[];
 for(const type of ['stripes','crosshatch','dots','checkerboard']){e.setFillPaint({kind:'pattern',type,foreground:'#FF0000',background:'#FFFFFF',transparent:false,size:10,angle:0,detail:50,opacity:.5});e.fillAt(new p.Point(25,35));const svg=exportSVG([e.selected]),blob=await exportPNG(svg,{width:400}),bitmap=await createImageBitmap(blob),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(bitmap,0,0);const sample=(x:number,y:number)=>[...ctx.getImageData(x,y,1,1).data];samples.push({type,a:sample(type==='dots'?50:20,type==='dots'?50:20),b:sample(75,25)});bitmap.close();}
 const pdfText=await (await exportPDF(exportSVG([e.selected]))).text();return {samples,patternPDF:pdfText.includes('/PatternType 1')};});
 for(const s of result.samples){expect(s.a.slice(0,3)).toEqual([255,0,0]);expect(s.a[3]).toBeCloseTo(128,0);if(['dots','checkerboard'].includes(s.type))expect(s.b.slice(0,3)).toEqual([255,255,255]);}expect(result.patternPDF).toBe(true);
});

test('Gradient holes, No fill, undo and malformed document protection retain paint semantics',async({page})=>{
 await ready(page);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts' as string);e.addShape(new p.Path.Circle({insert:false,center:[40,40],radius:30}),'Outer');e.addShape(new p.Path.Circle({insert:false,center:[40,40],radius:10}),'Inner');e.setFillPaint({kind:'gradient',type:'linear',angle:45,opacity:.8,stops:[{colour:'#FF0000',offset:0,opacity:1},{colour:'#0000FF',offset:1,opacity:1}]});e.fillAt(new p.Point(60,40));const hole=!e.selected.contains(new p.Point(40,40)),before=e.snapshot();e.setFillColor('none');e.fillAt(new p.Point(60,40));const cleared=e.objects.filter((s:any)=>s.data.regionFill).length;e.undo();const restored=e.snapshot();const data=JSON.parse(encodeDocument(e));data.layers.flatMap((l:any)=>l.objects).find((s:any)=>s.data.fillPaint).data.fillPaint.stops[0].offset=2;let rejected=false;try{await decodeDocument(JSON.stringify(data));}catch{rejected=true;}return {hole,cleared,same:JSON.stringify(before)===JSON.stringify(restored),rejected};});expect(result).toEqual({hole:true,cleared:0,same:true,rejected:true});
});

test('Production appearance tabs have working previews and independent controls',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await expect(page.locator('#workspace')).not.toHaveAttribute('inert','');await page.getByRole('button',{name:'Fill & appearance',exact:true}).click();await page.getByRole('tab',{name:'Gradient',exact:true}).click();await page.getByRole('combobox',{name:'Gradient type',exact:true}).selectOption('radial');await expect(page.locator('[data-paint-preview="gradient"] radialGradient')).toHaveCount(1);await page.getByRole('tab',{name:'Pattern',exact:true}).click();await page.getByRole('combobox',{name:'Pattern type',exact:true}).selectOption('dots');await expect(page.locator('[data-paint-preview="pattern"] pattern circle')).toHaveCount(1);await page.getByRole('tab',{name:'Gradient',exact:true}).click();await expect(page.getByRole('combobox',{name:'Gradient type',exact:true})).toHaveValue('radial');expect(errors).toEqual([]);
});

test('Dissecting or splitting painted artwork produces saveable outline paths',async({page})=>{
 await ready(page);await draw(page);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts' as string);e.setFillPaint({kind:'pattern',type:'stripes',foreground:'#FF0000',background:'#FFFFFF',transparent:false,size:5,angle:0,detail:25,opacity:1});e.fillAt(new p.Point(25,35));e.objects.filter((s:any)=>!s.data.regionFill).forEach((s:any)=>s.remove());e.setTool('dissect-delete');e.deleteAt(new p.Point(10,35));const trimmed=e.objects[0];await decodeDocument(encodeDocument(e));const trim={paint:!!trimmed.data.fillPaint,fill:!!trimmed.fillColor,stroke:trimmed.strokeColor.toCSS(true)};e.undo();const owner=e.objects.find((s:any)=>s.data.regionFill);owner.data.rasterTrace={mode:'fill'};e.select(owner);e.nodes.active={uid:owner.data.uid,contour:0,index:0};e.nodes.action('split');await decodeDocument(encodeDocument(e));return {trim,split:e.objects.map((s:any)=>({paint:!!s.data.fillPaint,fill:!!s.fillColor,stroke:s.strokeColor.toCSS(true)}))};});expect(result.trim).toEqual({paint:false,fill:false,stroke:'#ff0000'});expect(result.split).toEqual([result.trim]);
});

test('PDF preserves varying gradient alpha without rasterizing strokes or other artwork',async({page})=>{
 await ready(page);await draw(page);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportSVG}=await import('/src/exportSVG.ts' as string),{preparePDFPaint}=await import('/src/pdfPaint.ts' as string),{exportPDF}=await import('/src/exportPDF.ts' as string);e.setFillPaint({kind:'gradient',type:'linear',angle:0,opacity:1,stops:[{colour:'#FF0000',offset:0,opacity:1},{colour:'#0000FF',offset:1,opacity:0}]});e.fillAt(new p.Point(25,35));const before=e.snapshot(),contents=exportSVG(e.objects),svg=new DOMParser().parseFromString(contents,'image/svg+xml').documentElement as unknown as SVGSVGElement;await preparePDFPaint(svg);const image=svg.querySelector('image')!,bitmap=await createImageBitmap(await (await fetch(image.getAttribute('href')!)).blob()),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(bitmap,0,0);const alpha=(fraction:number)=>ctx.getImageData(Math.round(bitmap.width*fraction),Math.round(bitmap.height/2),1,1).data[3];const pixels=[alpha(.05),alpha(.95)];bitmap.close();const pdf=await (await exportPDF(contents)).text();return {pixels,images:svg.querySelectorAll('image').length,vectors:svg.querySelectorAll('path[stroke]').length,mask:pdf.includes('/SMask'),unchanged:JSON.stringify(before)===JSON.stringify(e.snapshot())};});expect(result.pixels[0]).toBeGreaterThan(220);expect(result.pixels[1]).toBeLessThan(30);expect(result.images).toBe(1);expect(result.vectors).toBeGreaterThan(0);expect(result.mask).toBe(true);expect(result.unchanged).toBe(true);
});

test('Colour and opacity edits preserve rotated/scaled pattern frames',async({page})=>{
 await ready(page);await draw(page);const result=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.setFillPaint({kind:'pattern',type:'dots',foreground:'#FF0000',background:'#FFFFFF',transparent:false,size:5,angle:0,detail:25,opacity:1});e.fillAt(new p.Point(25,35));const shape=e.selected;shape.rotate(30);shape.scale(2,1.5);const frame=()=>[shape.fillColor.origin,shape.fillColor.destination,shape.fillColor.highlight].map((v:any)=>[v.x,v.y]),before=frame();e.setFillPaint({...shape.data.fillPaint,foreground:'#0000FF',opacity:.4},true);const edited=frame();const layer=e.addDocumentLayer('artwork');e.select(shape);e.moveSelectionToLayer(layer.data.documentId);return {before,edited,transferred:frame()};});expect(result.edited).toEqual(result.before);expect(result.transferred).toEqual(result.before);
});

test('Artwork paint never overrides operation-layer colours during outline conversion',async({page})=>{
 await ready(page);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,{loadTextFont,createTextShape}=await import('/src/text.ts' as string);await loadTextFont('lato');const colours=[];for(const [role,colour] of [['cutline','#ff0000'],['engrave','#0000ff'],['construction','#ff00ff']]){e.setActiveLayer('artwork');e.addShape(createTextShape({content:'O',fontId:'lato',sizeMM:10,transform:[1,0,0,1,10,10]}),'Text');e.setFillPaint({kind:'gradient',type:'linear',angle:0,opacity:1,stops:[{colour:'#00FF00',offset:0,opacity:1},{colour:'#FFFF00',offset:1,opacity:1}]},true);e.moveSelectionToLayer(role);e.convertTextToPaths();colours.push({expected:colour,actual:e.selectedItems.map((s:any)=>s.strokeColor.toCSS(true))});}return colours;});for(const row of result)expect(row.actual.every((c:string)=>c===row.expected)).toBe(true);
});

test('Every Fill paint goes to Artwork while keeping the chosen drawing layer',async({page})=>{
 await ready(page);await draw(page);const result=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,records=[];e.select(e.objects[0]);e.moveSelectionToLayer('cutline');const outline=e.objects[0],before=outline.pathData;const paints=[{kind:'colour',colour:'#22AA88',opacity:.6},{kind:'gradient',type:'radial',angle:0,opacity:.8,stops:[{colour:'#FF0000',offset:0,opacity:1},{colour:'#0000FF',offset:1,opacity:1}]},{kind:'pattern',type:'dots',foreground:'#123456',background:'#FFFFFF',transparent:true,size:5,angle:45,detail:25,opacity:.7}];for(const role of ['cutline','engrave','construction'])for(const paint of paints){e.setActiveLayer(role);e.setFillPaint(paint);e.fillAt(new p.Point(25,35));records.push({layer:e.selected.layer.data.documentId,active:e.activeLayerId,expectedActive:role,kind:e.selected.data.fillPaint?.kind??'colour',expectedKind:paint.kind,opacity:e.selected.opacity,expectedOpacity:paint.opacity});}const count=e.objects.length;e.undo();e.redo();return {records,count,unchanged:outline.pathData===before,stroke:outline.strokeColor.toCSS(true),redoLayer:e.selected.layer.data.documentId};});for(const row of result.records){expect(row.layer).toBe('artwork');expect(row.active).toBe(row.expectedActive);expect(row.kind).toBe(row.expectedKind);expect(row.opacity).toBe(row.expectedOpacity);}expect(result.count).toBe(2);expect(result.unchanged).toBe(true);expect(result.stroke).toBe('#ff0000');expect(result.redoLayer).toBe('artwork');
});

test('Pointer Fill ignores active operation-layer locks but respects the Artwork destination',async({page})=>{
 await ready(page);await draw(page);const point=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.select(e.objects[0]);e.moveSelectionToLayer('cutline');e.setActiveLayer('cutline');e.setFillColor('#22AA88');e.setTool('fill');e.cutlines.locked=true;const pt=p.view.projectToView(new p.Point(25,35)),bounds=p.view.element.getBoundingClientRect();return {x:pt.x+bounds.x,y:pt.y+bounds.y};});await page.mouse.click(point.x,point.y);expect(await page.evaluate(()=>(window as any).__vectora.selected?.layer.data.documentId)).toBe('artwork');const result=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,errors=[];e.setActiveLayer('engrave');for(const flag of ['locked','visible','deleted']){e.artwork.locked=flag==='locked';e.artwork.visible=flag!=='visible';e.artwork.data.deleted=flag==='deleted';try{e.fillAt(new p.Point(25,35));errors.push(false);}catch{errors.push(true);}}return errors;});expect(result).toEqual([true,true,true]);
});
