import {test,expect} from '@playwright/test';
const DEV='http://127.0.0.1:5174';

test('Font library loads every local face and Properties switches real text between all families',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(DEV);
  const fonts=await page.evaluate(async()=>{const {TEXT_FONTS,loadTextFont}=await import('/src/text.ts');const e=(window as any).__vectora,p=(window as any).__paper;await loadTextFont();e.saveText('AO 123',10,new p.Point(35,40),null,'lato');return TEXT_FONTS;});
  await page.getByRole('button',{name:'Properties',exact:true}).click();const picker=page.getByRole('combobox',{name:'Font',exact:true});expect(await picker.locator('option').count()).toBe(13);expect(await picker.locator('optgroup').count()).toBe(5);
  for(const font of fonts){
    await expect(picker).toBeEnabled();await picker.selectOption(font.id);await expect.poll(()=>page.evaluate(()=>(window as any).__vectora.selected.data.text.fontId)).toBe(font.id);
    const state=await page.evaluate(async(font)=>{await document.fonts.load(`20px "Vectora ${font.name}"`);const s=(window as any).__vectora.selected;return {loaded:document.fonts.check(`20px "Vectora ${font.name}"`),width:s.bounds.width,height:s.bounds.height,contours:s.children.length,filled:!!s.fillColor};},font);
    expect(state.loaded).toBe(true);expect(state.width).toBeGreaterThan(8);expect(state.height).toBeGreaterThan(3);expect(state.contours).toBeGreaterThan(4);expect(state.filled).toBe(true);
  }
  expect(errors).toEqual([]);await page.screenshot({path:'test-results/font-library-properties.png'});
  await page.goto(DEV+'/reference/design-system.html');expect(await page.locator('#example-text-font option').evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value))).toEqual(fonts.map(f=>f.id));
});

for(const id of ['hershey','relief-single-line'])test(`${id} converts and exports original single-line strokes with transforms, cut colour and undo`,async({page})=>{
  await page.goto(DEV);const before=await page.evaluate(async(id)=>{const {loadTextFont,createTextShape}=await import('/src/text.ts'),{exportDXF}=await import('/src/exportDXF.ts');const e=(window as any).__vectora,p=(window as any).__paper;await loadTextFont(id);e.saveText('AO',15,new p.Point(45,45),null,id);e.setRotation(31);e.setProperty('width',e.selectionBounds.width*1.4);e.moveSelectionToCutPath();const expected=createTextShape(e.selected.data.text,true),curves=(expected.children as any[]).map(path=>path.curves.map((c:any)=>c.values));expected.remove();return {snapshot:e.snapshot(),curves,dxf:exportDXF(e.objects),displayCount:e.selected.children.length};},id);
  await page.getByRole('button',{name:'Convert to path',exact:true}).click();const after=await page.evaluate(async()=>{const {exportDXF}=await import('/src/exportDXF.ts');const e=(window as any).__vectora;return {curves:e.objects.map((p:any)=>p.curves.map((c:any)=>c.values)),open:e.objects.every((p:any)=>!p.closed),colors:e.objects.map((p:any)=>p.strokeColor.toCSS(true)),fill:e.objects.some((p:any)=>!!p.fillColor),text:e.objects.some((p:any)=>!!p.data.text),dxf:exportDXF(e.objects)};});
  expect(after.curves).toEqual(before.curves);expect(after.curves.length).toBe(id==='hershey'?4:3);expect(before.displayCount).toBeGreaterThan(after.curves.length);expect(after.open).toBe(true);expect(after.colors).toEqual(Array(after.curves.length).fill('#ff0000'));expect(after.fill).toBe(false);expect(after.text).toBe(false);expect(after.dxf).toEqual(before.dxf);expect(after.dxf.match(/LWPOLYLINE/g)).toHaveLength(after.curves.length);
  await page.keyboard.press('Control+z');expect(await page.evaluate(()=>(window as any).__vectora.snapshot())).toEqual(before.snapshot);await page.keyboard.press('Control+Shift+z');await page.getByRole('button',{name:'Node editing',exact:true}).click();expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.filter((p:any)=>p.data.control==='node').length)).toBeGreaterThan(8);
});

test('Stencil fonts retain bridges and ordinary outlined O retains inner and outer contours',async({page})=>{
  await page.goto(DEV);const result=await page.evaluate(async()=>{const {loadTextFont,createTextShape}=await import('/src/text.ts');const report=[];for(const id of ['allerta-stencil','saira-stencil-one','free-mono','inter','jetbrains-mono','oswald','montserrat','bebas-neue']){await loadTextFont(id);const shape=createTextShape({content:'O',sizeMM:20,fontId:id,transform:[1,0,0,1,0,0]},true),center=shape.bounds.center;report.push({id,count:shape.children.length,enclosing:shape.children.some(p=>p.contains(center)),closed:shape.children.every((p:any)=>p.closed)});shape.remove();}return report;});
  for(const font of result){expect(font.closed).toBe(true);if(font.id.includes('stencil')){expect(font.enclosing).toBe(false);}else{expect(font.count).toBe(2);expect(font.enclosing).toBe(true);}}
});

test('Production engraving text remains plain editable text while typing and converts after editing',async({page})=>{
  await page.goto(DEV);await page.evaluate(async()=>{const {loadTextFont}=await import('/src/text.ts'),e=(window as any).__vectora,p=(window as any).__paper;await loadTextFont('relief-single-line');e.saveText('Relief',12,new p.Point(50,45),null,'relief-single-line');});await page.getByRole('button',{name:'Properties',exact:true}).click();await page.getByRole('button',{name:'Edit text',exact:true}).click();const input=page.getByRole('textbox',{name:'Edit text on canvas',exact:true});await expect(input).toBeVisible();await input.fill('Relief AO');await expect(input).toHaveCSS('font-family','"Vectora Relief Single Line"');await page.screenshot({path:'test-results/engraving-inline-text.png'});await input.press('Control+Enter');await expect(input).toBeHidden();expect(await page.evaluate(()=>(window as any).__vectora.selected.data.text.content)).toBe('Relief AO');await page.getByRole('button',{name:'Convert to path',exact:true}).click();expect(await page.evaluate(()=>(window as any).__vectora.objects.every((p:any)=>!p.fillColor&&!p.closed))).toBe(true);
  await page.goto('http://127.0.0.1:4173');const loaded=await page.evaluate(async()=>{const names=['Hershey Sans 1-stroke','Relief Single Line','FreeMono','Inter','JetBrains Mono','Oswald','Montserrat','Bebas Neue','Allerta Stencil','Saira Stencil One'];return Promise.all(names.map(async name=>{const faces=await document.fonts.load(`20px "Vectora ${name}"`);return faces.length;}));});expect(loaded).toEqual(Array(10).fill(1));
});
