import {test,expect,Page} from './fixtures';
const DEV='http://127.0.0.1:5174';
async function choose(page:Page){await page.getByRole('button',{name:'Shapes',exact:true}).click();const heart=page.locator('#primary-shapes-menu [data-shape="Heart"]');await expect(heart).toHaveCount(1);await heart.click();}
async function draw(page:Page,from:number[],to:number[],shift=false){const [a,b]=await page.evaluate(points=>{const p=(window as any).__paper;return points.map(point=>{const q=p.view.projectToView(new p.Point(point));return {x:q.x,y:q.y};});},[from,to]);await page.mouse.move(a.x,a.y);await page.mouse.down();if(shift)await page.keyboard.down('Shift');await page.mouse.move(b.x,b.y,{steps:4});await page.mouse.up();if(shift)await page.keyboard.up('Shift');}

test('Heart draws a symmetric closed curve in snapped bounds and the current layer with undo and export',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>(window as any).__vectora.setActiveLayer('cutline'));await choose(page);await draw(page,[21,19],[69,81]);
 const result=await page.evaluate(async()=>{const e=(window as any).__vectora,s=e.selected,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts'),{exportSVG}=await import('/src/exportSVG.ts'),{exportDXF}=await import('/src/exportDXF.ts');const data={name:s.data.name,closed:s.closed,fill:s.fillColor,color:s.strokeColor.toCSS(true),role:s.data.role,bounds:[s.bounds.x,s.bounds.y,s.bounds.width,s.bounds.height],points:s.segments.map((n:any)=>[n.point.x,n.point.y]),curves:s.curves.every((c:any)=>!c.isStraight()),json:s.exportJSON({precision:12}),svg:exportSVG(e.objects),dxf:exportDXF(e.objects)};const saved=encodeDocument(e),doc=await decodeDocument(saved);e.loadDocument(doc.snapshot,doc.view);return {...data,loaded:e.objects[0].exportJSON({precision:12})};});
 expect(result).toMatchObject({name:'Heart',closed:true,fill:null,color:'#ff0000',role:'cutline',bounds:[20,20,50,60],curves:true});expect(JSON.parse(result.loaded)).toEqual(JSON.parse(result.json));expect(result.points).toContainEqual([45,80]);expect(result.points.filter((p:number[])=>p[1]===20)).toHaveLength(2);for(const [x,y] of result.points)expect(result.points.some((p:number[])=>Math.abs(p[0]-(90-x))<1e-8&&Math.abs(p[1]-y)<1e-8)).toBe(true);expect(result.svg).toMatch(/d="[^"]*[cC]/);expect(result.dxf).toContain('LWPOLYLINE');await expect(page.locator('#properties-panel')).toBeVisible();
 // A fresh draw is one history step, independent of the document round-trip above.
 await choose(page);await draw(page,[100,20],[140,60]);expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(2);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(1);await page.keyboard.press('Control+Shift+z');expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(2);
});

test('Heart supports reverse drags, Shift proportions, cancellation and node editing',async({page})=>{
 await page.goto(DEV);await choose(page);await draw(page,[80,80],[30,60],true);const data=await page.evaluate(()=>{const s=(window as any).__vectora.selected;return {bounds:[s.bounds.x,s.bounds.y,s.bounds.width,s.bounds.height],json:JSON.stringify((window as any).__vectora.snapshot())};});expect(data.bounds).toEqual([30,30,50,50]);await page.mouse.move(800,350);await page.mouse.down();await page.mouse.move(950,480);await page.keyboard.press('Escape');await page.mouse.up();expect(await page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()))).toBe(data.json);
 await page.getByRole('button',{name:'Node editing',exact:true}).click();const node=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,q=p.view.projectToView(e.selected.segments[0].point);return {x:q.x,y:q.y};});await page.mouse.move(node.x,node.y);await page.mouse.down();await page.mouse.move(node.x+35,node.y+20);await page.mouse.up();expect(await page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()))).not.toBe(data.json);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()))).toBe(data.json);
});

test('Heart works through production Shapes, search and the shared reference',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await choose(page);await page.mouse.move(350,250);await page.mouse.down();await page.mouse.move(620,530,{steps:4});await page.mouse.up();await expect(page.locator('#selection-menu')).toBeVisible();await expect(page.locator('#tool-status')).toContainText('Heart');await page.screenshot({path:'test-results/heart-production.png',scale:'css'});
 await page.goto(DEV);await page.getByRole('button',{name:'Search tools',exact:true}).click();await page.getByRole('combobox',{name:'Search tools'}).fill('heart');await page.keyboard.press('Enter');expect(await page.evaluate(()=>(window as any).__vectora.tool)).toBe('heart');await page.mouse.click(400,300);expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(0);
 await page.goto(DEV+'/reference/design-system.html');await page.locator('[data-shape-trigger]').first().click();await page.locator('#primary-shapes-menu [data-shape="Heart"]').click();await expect(page.locator('#primary-shapes-menu [data-shape="Heart"]')).toHaveAttribute('aria-checked','true');expect(errors).toEqual([]);
});
