import {test,expect,type Page} from './fixtures';
const DEV='http://127.0.0.1:5174';
async function open(page:Page){await page.locator('[data-generator-trigger]').click();await page.locator('[data-generator="jigsaw"]').click();return page.locator('#generator-dialog');}
test('Extreme jigsaw tabs stay simple, inside the assembled border and within the sampling budget',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{
  const {CATALOG,defaults}=await import('/src/generators/catalog.ts'),{generate}=await import('/src/generators/geometry.ts'),p=(window as any).__paper;
  const cases=[];for(const [width,height,columns,rows] of [[10,10,2,2],[400,40,4,8],[40,400,8,4],[2000,2000,2,2]])for(let seed=1;seed<=8;seed++){
   const r=generate('jigsaw','jigsaw-pieces',{...defaults(CATALOG.jigsaw.profiles[1]),width,height,columns,rows,gap:0,tabSize:20,variation:30,seed});
   const paths=r.parts.map(part=>new p.Path({insert:false,segments:(part.contours[0] as any).points,closed:true}));
   cases.push({crossings:paths.reduce((n:number,path:any)=>n+path.getCrossings(path).length,0),area:paths.reduce((n:number,path:any)=>n+Math.abs(path.area),0),expected:width*height,bounds:r.bounds,points:r.parts.reduce((n,part)=>n+(part.contours[0] as any).points.length,0),width,height});paths.forEach((path:any)=>path.remove());
  }
  let bounded=false;try{generate('jigsaw','jigsaw-pieces',{...defaults(CATALOG.jigsaw.profiles[1]),width:2000,height:2000,columns:30,rows:30,tabSize:20});}catch(e){bounded=(e as Error).message.includes('too detailed');}
  return {cases,bounded};
 });expect(result.bounded).toBe(true);for(const r of result.cases){expect(r.crossings).toBe(0);expect(r.area).toBeCloseTo(r.expected,5);expect(r.bounds).toEqual({x:0,y:0,width:r.width,height:r.height});expect(r.points).toBeLessThan(50000);}
});
test('Jigsaw pieces tile the exact puzzle with complementary edges, no crossings and repeatable seeds',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{
  const {CATALOG,defaults}=await import('/src/generators/catalog.ts'),{generate}=await import('/src/generators/geometry.ts');const cat=(CATALOG as any).jigsaw;if(!cat)return null;const base={...defaults(cat.profiles.find((p:any)=>p.id==='jigsaw-pieces')),width:180,height:120,columns:6,rows:4,gap:0,seed:42};
  const pieces=generate('jigsaw' as any,'jigsaw-pieces',base),cuts=generate('jigsaw' as any,'jigsaw-cuts',base),p=(window as any).__paper;
  const keys=(result:any)=>{const map=new Map<string,number>();for(const part of result.parts)for(const c of part.contours){for(let i=0;i<c.points.length-(c.closed?0:1);i++){const a=c.points[i],b=c.points[(i+1)%c.points.length];if(a[0]===b[0]&&(a[0]===0||a[0]===180)||a[1]===b[1]&&(a[1]===0||a[1]===120))continue;const key=[a.map((n:number)=>n.toFixed(8)).join(','),b.map((n:number)=>n.toFixed(8)).join(',')].sort().join('|');map.set(key,(map.get(key)??0)+1);}}return map;};
  const shared=keys(cuts),paired=keys(pieces),paths=pieces.parts.map(part=>new p.Path({insert:false,segments:(part.contours[0] as any).points,closed:true}));
  const area=paths.reduce((sum:any,path:any)=>sum+Math.abs(path.area),0),crossings=paths.reduce((sum:any,path:any)=>sum+path.getCrossings(path).length,0);paths.forEach((p:any)=>p.remove());
  return {count:pieces.parts.length,closed:pieces.parts.every(part=>(part.contours[0] as any).closed),area,crossings,bounds:pieces.bounds,matched:shared.size===paired.size&&[...shared].every(([key,count])=>count===1&&paired.get(key)===2),cuts:cuts.parts.length,repeat:JSON.stringify(pieces)===JSON.stringify(generate('jigsaw' as any,'jigsaw-pieces',base)),different:JSON.stringify(pieces)!==JSON.stringify(generate('jigsaw' as any,'jigsaw-pieces',{...base,seed:43}))};
 });expect(result).not.toBeNull();expect(result!).toMatchObject({count:24,closed:true,crossings:0,matched:true,cuts:9,repeat:true,different:true,bounds:{x:0,y:0,width:180,height:120}});expect(result!.area).toBeCloseTo(180*120,6);
});
test('Separated jigsaw pieces leave the requested gap and preserve each outline',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{const {CATALOG,defaults}=await import('/src/generators/catalog.ts'),{generate}=await import('/src/generators/geometry.ts');const cat=(CATALOG as any).jigsaw;if(!cat)return null;const v={...defaults(cat.profiles[1]),columns:4,rows:3,width:120,height:90,tabSize:20,variation:30,seed:9};const plain=generate('jigsaw' as any,'jigsaw-pieces',{...v,gap:0}),spaced=generate('jigsaw' as any,'jigsaw-pieces',{...v,gap:4}),p=(window as any).__paper;const paths=spaced.parts.map(part=>new p.Path({insert:false,segments:(part.contours[0] as any).points,closed:true}));let clearance=Infinity;for(let i=0;i<paths.length;i++)for(let j=i+1;j<paths.length;j++){const a=paths[i].bounds,b=paths[j].bounds;const dx=Math.max(a.left-b.right,b.left-a.right,0),dy=Math.max(a.top-b.bottom,b.top-a.bottom,0);clearance=Math.min(clearance,Math.hypot(dx,dy));}const unchanged=plain.parts.every((part,i)=>{const a=(part.contours[0] as any).points,b=(spaced.parts[i].contours[0] as any).points,dx=b[0][0]-a[0][0],dy=b[0][1]-a[0][1];return a.length===b.length&&a.every((pt:number[],j:number)=>Math.abs(pt[0]+dx-b[j][0])<1e-8&&Math.abs(pt[1]+dy-b[j][1])<1e-8);});paths.forEach((p:any)=>p.remove());return {clearance,unchanged};});expect(result).not.toBeNull();expect(result!.unchanged).toBe(true);expect(result!.clearance).toBeGreaterThanOrEqual(4-1e-8);
});
test('Jigsaw rejects excessive density and tiny cells, and supports single-piece and single-row puzzles',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{const {CATALOG,defaults}=await import('/src/generators/catalog.ts'),{generate}=await import('/src/generators/geometry.ts');const cat=(CATALOG as any).jigsaw;if(!cat)return null;const v=defaults(cat.profiles[0]);const good=[{columns:1,rows:1},{columns:1,rows:8},{columns:8,rows:1}].map(values=>{const r=generate('jigsaw' as any,'jigsaw-cuts',{...v,...values});return {count:r.parts.length,bounds:r.bounds};});const bad=[{columns:50,rows:50},{columns:50,rows:1,width:10},{columns:3.5},{tabSize:0},{seed:NaN}].map(values=>{try{generate('jigsaw' as any,'jigsaw-cuts',{...v,...values});return false;}catch{return true;}});return {good,bad};});expect(result).not.toBeNull();expect(result!.bad.every(Boolean)).toBe(true);expect(result!.good.map(r=>r.count)).toEqual([1,8,8]);
});
test('Jigsaw live controls insert into the active layer with one undo and round-trip through save and export',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>(window as any).__vectora.setActiveLayer('cutline'));const d=await open(page);await expect(d).toBeVisible();await expect(d.locator('[data-insert]')).toBeEnabled();await d.getByLabel('Columns', {exact:true}).fill('3');await d.getByLabel('Rows',{exact:true}).fill('2');await expect(d.locator('.generator-metrics')).toContainText('6');const initial=await d.locator('.generator-outlines').innerHTML();await d.getByRole('button',{name:'New seed',exact:true}).click();expect(await d.locator('.generator-outlines').innerHTML()).not.toBe(initial);
 await d.locator('[data-insert]').click();expect(await page.evaluate(()=>{const e=(window as any).__vectora;return [e.objects.length,e.selectedItems.length,e.objects.every((s:any)=>s.layer.data.documentId==='cutline')];})).toEqual([4,4,true]);
 await page.evaluate(async()=>{const e=(window as any).__vectora,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts'),{exportSVG}=await import('/src/exportSVG.ts'),{exportDXF}=await import('/src/exportDXF.ts'),{exportLaserDXF}=await import('/src/exportLaserDXF.ts');const loaded=await decodeDocument(encodeDocument(e));if(loaded.snapshot.cutlines==='[]')throw new Error('Missing saved cuts');if(!exportSVG(e.objects).includes('<path'))throw new Error('Missing SVG');const dxf=exportDXF(e.objects);if(!dxf.includes('ENTITIES'))throw new Error('Missing DXF');if(!exportLaserDXF(e.objects,false).includes('LINE'))throw new Error('Missing laser paths');e.undo();if(e.objects.length)throw new Error('Undo did not remove generator');e.redo();if(e.objects.length!==4)throw new Error('Redo did not restore paths');});
});
test('Jigsaw profiles, validation and cancellation work in production and the reference, including narrow layouts',async({page})=>{
 for(const url of ['http://127.0.0.1:4173',DEV+'/reference/design-system.html']){
  await page.goto(url);const d=await open(page);await expect(d.getByLabel('Profile',{exact:true})).toHaveValue('jigsaw-cuts');await expect(d.locator('.generator-outlines path')).toHaveCount(9);
  await d.getByLabel('Profile',{exact:true}).selectOption('jigsaw-pieces');await expect(d.locator('.generator-outlines path')).toHaveCount(24);await expect(d.getByLabel('Piece spacing',{exact:true})).toBeVisible();
  await d.getByLabel('Columns',{exact:true}).fill('50');await d.getByLabel('Rows',{exact:true}).fill('50');await expect(d.locator('[data-insert]')).toBeDisabled();await expect(d.locator('.generator-feedback')).toContainText('1,000');await expect(d.locator('.generator-outlines path')).toHaveCount(0);
  await d.getByRole('button',{name:'Reset parameters'}).click();await expect(d.locator('.generator-outlines path')).toHaveCount(24);await page.keyboard.press('Escape');await expect(d).not.toBeVisible();
 }
 await page.goto(DEV);await page.locator('[data-tool-search]').click();await page.locator('#tool-search-dialog input').fill('jigsaw');await page.locator('.tool-search-result').first().click();const d=page.locator('#generator-dialog');await expect(d.locator('#generator-title')).toHaveText('Jigsaw puzzle');
 await page.screenshot({path:'test-results/jigsaw-desktop.png',scale:'css'});await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:550});await open(page);await expect(d.locator('[data-insert]')).toBeInViewport();const box=(await d.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(390);await page.screenshot({path:'test-results/jigsaw-mobile.png',scale:'css'});await d.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(0);
});
