import {test,expect} from '@playwright/test';
const DEV='http://127.0.0.1:5174';
test('Large drawings avoid hidden layer rows and idle pointer refreshes',async({page})=>{
 await page.goto(DEV);await expect(page.locator('#workspace')).not.toHaveAttribute('inert','');
 const result=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;for(let i=0;i<2500;i++){const shape=new p.Path.Rectangle({insert:false,rectangle:[(i%50)*4,Math.floor(i/50)*4,3,3],strokeColor:'#FFFFFF',strokeWidth:1.5,strokeScaling:false});shape.data={uid:`perf-${i}`,name:'Rectangle',role:'artwork'};e.artwork.addChild(shape);}p.view.center=[100,100];e.refreshTheme();const timings:Record<string,{ms:number;calls:number}>={};for(const name of ['drawOverlay','onChange','snapshot','hitObject','onDocumentChange']){const original=e[name];e[name]=function(...args:any[]){const start=performance.now();try{return original.apply(this,args);}finally{const t=timings[name]??={ms:0,calls:0};t.ms+=performance.now()-start;t.calls++;}};}const measure=(work:()=>void)=>{const start=performance.now();work();return performance.now()-start;};const single=measure(()=>{for(let i=0;i<20;i++)e.select(e.objects[i]);});e.selection=e.objects;e.interaction={kind:'move',items:e.selectedItems};const group=measure(()=>{for(let i=0;i<10;i++){for(const item of e.selectedItems)item.translate([.1,0]);e.changed();}});const dragDecorations=e.overlays.children.filter((item:any)=>item.data.role==='overlay').length;e.interaction=null;const callsBeforeIdle=timings.onChange.calls;const idle=measure(()=>{for(let i=0;i<20;i++)e.pointerMove(new PointerEvent('pointermove',{clientX:400+i,clientY:400}));});return {dragDecorations,idleUpdates:timings.onChange.calls-callsBeforeIdle,singleMs:single/20,groupMs:group/10,idleMs:idle/20,timings,domRows:document.querySelectorAll('.layer-object').length,objects:e.objects.length};});console.log('LARGE_DOCUMENT_PROFILE',JSON.stringify(result));expect(result.objects).toBe(2500);expect(result.domRows).toBe(0);expect(result.idleUpdates).toBe(0);expect(result.dragDecorations).toBeLessThan(32);
 const clickPoint=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.selection=[];e.changed();const stats={snapshots:0,snapshotMs:0,cacheMs:0};const snapshot=e.snapshot.bind(e),cache=e.onDocumentChange;e.snapshot=()=>{const start=performance.now();stats.snapshots++;const result=snapshot();stats.snapshotMs+=performance.now()-start;return result;};e.onDocumentChange=()=>{const start=performance.now();cache();stats.cacheMs+=performance.now()-start;};(window as any).__perfClick=stats;const point=p.view.projectToView([101,101]),rect=e.canvas.getBoundingClientRect();return {x:point.x+rect.x,y:point.y+rect.y};});await page.mouse.click(clickPoint.x,clickPoint.y);const click=await page.evaluate(()=>(window as any).__perfClick);console.log('CLICK_PROFILE',click);expect(click.snapshots).toBe(1);expect(click.cacheMs).toBe(0);
});

test('Expanded layer rows are reused across selection changes and large moves undo exactly',async({page})=>{
 await page.goto(DEV);await expect(page.locator('#workspace')).not.toHaveAttribute('inert','');await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;for(let i=0;i<150;i++){const shape=new p.Path.Rectangle({insert:false,rectangle:[(i%15)*8,Math.floor(i/15)*8,5,5],strokeColor:'#FFFFFF',strokeWidth:1.5,strokeScaling:false});shape.data={uid:`large-${i}`,name:'Rectangle',role:'artwork'};e.artwork.addChild(shape);}e.refreshTheme();});await page.getByRole('button',{name:'Layers',exact:true}).click();await expect(page.locator('.layer-object')).toHaveCount(0);await page.getByRole('button',{name:'Expand Artwork',exact:true}).click();await expect(page.locator('.layer-object')).toHaveCount(150);
 const reuse=await page.evaluate(()=>{const e=(window as any).__vectora,node=document.querySelector('[data-object-id="large-0"]');e.select(e.objects[0]);e.select(e.objects[1]);return node===document.querySelector('[data-object-id="large-0"]');});expect(reuse).toBe(true);await expect(page.locator('[data-object-id="large-1"]')).toHaveAttribute('aria-pressed','true');
 await page.locator('#close-layers').click();const point=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.selection=e.objects;e.setSnappingEnabled(false);e.changed();const pt=p.view.projectToView([42,34]),rect=e.canvas.getBoundingClientRect();return {x:pt.x+rect.x,y:pt.y+rect.y};});const before=await page.evaluate(()=>(window as any).__vectora.snapshot().artwork);await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+40,point.y+30,{steps:4});expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.filter((s:any)=>s.data.role==='overlay').length)).toBeLessThan(32);await page.mouse.up();expect(await page.evaluate(()=>(window as any).__vectora.selectedItems.length)).toBe(150);expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.filter((s:any)=>s.data.role==='overlay').length)).toBeGreaterThan(150);expect(await page.evaluate(()=>(window as any).__vectora.snapshot().artwork)).not.toBe(before);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await page.evaluate(()=>(window as any).__vectora.snapshot().artwork)).toBe(before);
});
