import {test,expect} from '@playwright/test';
import {readFileSync,writeFileSync} from 'node:fs';
const DEV='http://127.0.0.1:5174';
function records(text:string){const lines=text.trimEnd().split(/\r?\n/),records:{type:string;tags:[number,string][]}[]=[];for(let i=0;i<lines.length;i+=2){const code=Number(lines[i]),value=lines[i+1];if(code===0)records.push({type:value,tags:[]});else records.at(-1)?.tags.push([code,value]);}return records;}
const tag=(r:{tags:[number,string][]},n:number)=>r.tags.find(([code])=>code===n)?.[1];

test('Laser DXF exports exact closed and open line geometry with old-format tables and bounds',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportDXF}=await import('/src/exportDXF.ts');e.newDocument();e.setActiveLayer('cutline');e.addShape(new p.Path.Rectangle({insert:false,rectangle:[10,20,100,50]}),'Rectangle');e.setActiveLayer('engrave');e.addShape(new p.Path({insert:false,segments:[[15,25],[45,35],[60,30]]}),'Open');const before=JSON.stringify(e.snapshot());const dxf=exportDXF(e.objects,false,'laser');return {dxf,unchanged:before===JSON.stringify(e.snapshot()),standard:exportDXF(e.objects)};});
 expect(result.dxf).toContain('AC1009');expect(result.dxf).not.toContain('AcDb');expect(result.dxf).not.toContain('LWPOLYLINE');expect(result.dxf.replace(/\r\n/g,'')).not.toContain('\n');expect(result.dxf).toContain('$EXTMIN\r\n10\r\n10\r\n20\r\n-70\r\n30\r\n0');expect(result.dxf).toContain('$EXTMAX\r\n10\r\n110\r\n20\r\n-20');expect(result.unchanged).toBe(true);expect(result.standard).toContain('AC1015');expect(result.standard.match(/0\nLWPOLYLINE\n/g)).toHaveLength(2);
 const entities=records(result.dxf).filter(r=>r.type==='LINE');expect(entities).toHaveLength(6);const cut=entities.filter(r=>tag(r,8)==='CUTLINE');expect(cut).toHaveLength(4);expect(cut.every(r=>tag(r,62)==='1'&&tag(r,30)==='0'&&tag(r,31)==='0')).toBe(true);expect(entities.filter(r=>tag(r,8)==='ENGRAVE').map(r=>[tag(r,10),tag(r,20),tag(r,11),tag(r,21),tag(r,62)])).toEqual([['15','-25','45','-35','5'],['45','-35','60','-30','5']]);
 const endpoints=cut.flatMap(r=>[[tag(r,10),tag(r,20)],[tag(r,11),tag(r,21)]].map(x=>x.join(',')));for(const point of ['10,-20','110,-20','110,-70','10,-70'])expect(endpoints.filter(p=>p===point)).toHaveLength(2);
 writeFileSync('test-results/laser-geometry.dxf',result.dxf);
});

test('Laser export retains compound holes, transformed curves, text outlines and layer filters',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportDXF}=await import('/src/exportDXF.ts'),{flattenInDocument}=await import('/src/geometry.ts'),{loadTextFont,createTextShape}=await import('/src/text.ts');e.newDocument();e.setActiveLayer('cutline');const ring=new p.CompoundPath({insert:false,children:[new p.Path.Circle({insert:false,center:[40,40],radius:20}),new p.Path.Circle({insert:false,center:[40,40],radius:8})]});ring.applyMatrix=false;ring.matrix=new p.Matrix(1.5,.2,.1,1,10,5);e.addShape(ring,'Ring');const expected=flattenInDocument(ring).reduce((n,c)=>n+c.points.length,0);e.setActiveLayer('artwork');await loadTextFont('lato');e.addShape(createTextShape({content:'O',sizeMM:10,fontId:'lato',transform:[1,0,0,1,90,40]}),'Letter');e.setActiveLayer('construction');e.addShape(new p.Path.Rectangle({insert:false,rectangle:[0,0,300,300]}),'Guide');e.setLayerState('cutline','visible',false);e.setLayerState('cutline','locked',true);const before=JSON.stringify(e.snapshot()),cut=exportDXF(e.objects,false,'laser'),all=exportDXF(e.objects,true,'laser');return {expected,cut,all,unchanged:before===JSON.stringify(e.snapshot())};});
 expect(records(result.cut).filter(r=>r.type==='LINE')).toHaveLength(result.expected);const entities=records(result.all).filter(r=>r.type==='LINE');expect(entities.filter(r=>tag(r,8)==='ARTWORK').length).toBeGreaterThan(10);expect(entities.every(r=>['ARTWORK','CUTLINE'].includes(tag(r,8)!))).toBe(true);expect(result.all).not.toContain('CONSTRUCTION');expect(result.unchanged).toBe(true);writeFileSync('test-results/laser-curves-text.dxf',result.all);
});

test('Laser annotation labels use legacy TEXT and unsupported labels report an error',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const e=(window as any).__vectora,{exportDXF}=await import('/src/exportDXF.ts'),{createDimension}=await import('/src/dimensions.ts');e.newDocument();e.addShape(createDimension({kind:'leader',points:[[10,10],[20,20],[30,20]],text:'Cut here',transform:[1,0,0,1,0,0]}),'Note');const dxf=exportDXF(e.objects,true,'laser');e.selected.data.dimension.text='你好';let error='';try{exportDXF(e.objects,true,'laser');}catch(e){error=(e as Error).message;}return {dxf,error};});expect(records(r.dxf).filter(r=>r.type==='TEXT')).toHaveLength(1);expect(r.dxf).toContain('Cut here');expect(r.dxf).not.toContain('AcDbText');expect(r.error).toContain('annotation');writeFileSync('test-results/laser-annotation.dxf',r.dxf);
});

test('Export settings and search download laser format in both themes',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.newDocument();e.setActiveLayer('cutline');e.addShape(new p.Path.Rectangle({insert:false,rectangle:[20,20,30,30]}),'Box');});
 for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.setViewportSize({width:390,height:700});await page.getByRole('button',{name:'Search tools',exact:true}).click();await page.getByRole('combobox',{name:'Search tools'}).fill('laser-compatible');await page.keyboard.press('Enter');await expect(page.getByRole('tab',{name:'DXF',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.getByLabel('Compatibility',{exact:true})).toHaveValue('laser');await expect(page.locator('#export-dialog .export-format-hint')).toContainText('millimetres');const pending=page.waitForEvent('download');await page.locator('#export-dialog [data-export-submit]').click();const file=await pending;expect(file.suggestedFilename()).toBe('Untitled.dxf');expect(readFileSync((await file.path())!,'utf8')).toContain('AC1009');}
});

test('Production download and reference expose laser compatibility',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.getByRole('button',{name:'Shapes',exact:true}).click();await page.locator('#primary-shapes-menu [data-shape="Rectangle"]').click();await page.mouse.move(400,250);await page.mouse.down();await page.mouse.move(550,400,{steps:3});await page.mouse.up();await page.getByRole('button',{name:'File',exact:true}).click();await page.getByRole('menuitem',{name:'Export…',exact:true}).click();await page.getByRole('tab',{name:'DXF',exact:true}).click();await page.getByLabel('Compatibility',{exact:true}).selectOption('laser');await page.locator('#export-dialog summary').click();await page.locator('#export-dialog').getByLabel('Artwork',{exact:true}).check();const downloaded=page.waitForEvent('download');await page.locator('#export-dialog [data-export-submit]').click();const file=await downloaded,contents=readFileSync((await file.path())!,'utf8');expect(file.suggestedFilename()).toBe('Untitled.dxf');expect(records(contents).filter(r=>r.type==='LINE')).toHaveLength(4);writeFileSync('test-results/laser-production.dxf',contents);
 await page.goto(DEV+'/reference/design-system.html');await expect(page.locator('[aria-labelledby="export-reference-title"]')).toContainText('Laser-compatible DXF');expect(errors).toEqual([]);
});

test('Laser output preserves self-crossing closed cut paths with zero signed area',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{exportDXF}=await import('/src/exportDXF.ts');e.newDocument();e.setActiveLayer('cutline');e.addShape(new p.Path({insert:false,closed:true,segments:[[0,0],[20,20],[0,20],[20,0]]}),'Crossed outline');return exportDXF(e.objects,false,'laser');});expect(records(result).filter(r=>r.type==='LINE')).toHaveLength(4);writeFileSync('test-results/laser-crossed.dxf',result);
});
