import {test,expect,Page} from '@playwright/test';
const DEV='http://127.0.0.1:5174';
const snapshot=(page:Page)=>page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()));
async function setup(page:Page){await page.goto(DEV);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.addShape(new p.Path.Circle({insert:false,center:[40,40],radius:5,strokeColor:'white',strokeWidth:1.5,strokeScaling:false}),'Hole');});}
async function open(page:Page){const b=page.getByRole('button',{name:'Pattern',exact:true});await expect(b).toHaveCount(1);await b.click();const d=page.getByRole('dialog',{name:'Pattern',exact:true});await expect(d).toBeVisible();return d;}

test('Rectangular patterns use exact signed pitch, preserve the original and undo together',async({page})=>{
 await setup(page);const before=await snapshot(page),d=await open(page);await d.getByLabel('Columns',{exact:true}).fill('3');await d.getByLabel('Rows',{exact:true}).fill('2');await d.getByLabel('Column spacing',{exact:true}).fill('25.5');await d.getByLabel('Row spacing',{exact:true}).fill('-20');expect(await snapshot(page)).toBe(before);await expect(d.getByRole('status')).toContainText('6 instances');await d.getByRole('button',{name:'Apply',exact:true}).click();
 const result=await page.evaluate(()=>{const e=(window as any).__vectora;return {centres:e.objects.map((s:any)=>[s.bounds.center.x,s.bounds.center.y]),selected:e.selectedItems.length,ids:new Set(e.objects.map((s:any)=>s.data.uid)).size};});expect(result.centres).toEqual([[40,40],[65.5,40],[91,40],[40,20],[65.5,20],[91,20]]);expect(result.selected).toBe(6);expect(result.ids).toBe(6);await expect(page.locator('#properties-panel')).toBeHidden();await page.keyboard.press('Control+z');expect(await snapshot(page)).toBe(before);await page.keyboard.press('Control+Shift+z');expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(6);
});

test('Circular patterns distribute a full turn without a duplicate and can rotate each copy',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.addShape(new p.Path({insert:false,segments:[[60,40],[70,40]],strokeColor:'white',strokeWidth:1.5}),'Slot');});const d=await open(page);await d.getByRole('tab',{name:'Circular',exact:true}).click();await d.getByLabel('Instances',{exact:true}).fill('4');await d.getByLabel('Total angle',{exact:true}).fill('360');await d.getByLabel('Centre X',{exact:true}).fill('40');await d.getByLabel('Centre Y',{exact:true}).fill('40');await d.getByLabel('Rotate copies',{exact:true}).check();await d.getByRole('button',{name:'Apply',exact:true}).click();
 const points=await page.evaluate(()=>(window as any).__vectora.objects.map((s:any)=>s.segments.map((n:any)=>[n.point.x,n.point.y])));const wanted=[[[60,40],[70,40]],[[40,60],[40,70]],[[20,40],[10,40]],[[40,20],[40,10]]];points.forEach((path:number[][],i:number)=>path.forEach((q:number[],j:number)=>q.forEach((n,k)=>expect(n).toBeCloseTo(wanted[i][j][k],8))));
});

test('Partial circular patterns include both ends and preserve copy orientation when unchecked',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.addShape(new p.Path({insert:false,segments:[[60,40],[70,40]],strokeColor:'white'}),'Slot');});const d=await open(page);await d.getByRole('tab',{name:'Circular',exact:true}).click();await d.getByLabel('Instances',{exact:true}).fill('3');await d.getByLabel('Total angle',{exact:true}).fill('-180');await d.getByLabel('Centre X',{exact:true}).fill('40');await d.getByLabel('Centre Y',{exact:true}).fill('40');await d.getByLabel('Rotate copies',{exact:true}).uncheck();await d.getByRole('button',{name:'Apply',exact:true}).click();const points=await page.evaluate(()=>(window as any).__vectora.objects.map((s:any)=>s.segments.map((n:any)=>[n.point.x,n.point.y])));const wanted=[[[60,40],[70,40]],[[35,15],[45,15]],[[10,40],[20,40]]];points.forEach((path:number[][],i:number)=>path.forEach((q:number[],j:number)=>q.forEach((n,k)=>expect(n).toBeCloseTo(wanted[i][j][k],8))));
});

test('Invalid counts and spacing cannot apply; cancelling clears preview without history changes',async({page})=>{
 await setup(page);const before=await snapshot(page),d=await open(page);await d.getByLabel('Columns',{exact:true}).fill('1000000');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();expect(await snapshot(page)).toBe(before);await d.getByLabel('Columns',{exact:true}).fill('2.5');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();await d.getByLabel('Columns',{exact:true}).fill('2');await d.getByLabel('Column spacing',{exact:true}).fill('0');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();await d.getByLabel('Column spacing',{exact:true}).fill('15');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeEnabled();await page.keyboard.press('Escape');await expect(d).toBeHidden();expect(await snapshot(page)).toBe(before);expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.some((s:any)=>s.data.control==='pattern-preview'))).toBe(false);
});

test('Picking a circular centre snaps without drawing, supports keyboard cancellation and window blur',async({page})=>{
 await setup(page);const before=await snapshot(page),d=await open(page);await d.getByRole('tab',{name:'Circular',exact:true}).click();await d.getByRole('button',{name:'Pick centre on canvas'}).click();await expect(d).toBeHidden();const q=await page.evaluate(()=>{const p=(window as any).__paper,q=p.view.projectToView(new p.Point(53,47));return {x:q.x,y:q.y};});await page.mouse.move(q.x,q.y);await page.mouse.click(q.x,q.y);await expect(d).toBeVisible();await expect(d.getByLabel('Centre X',{exact:true})).toHaveValue('50');await expect(d.getByLabel('Centre Y',{exact:true})).toHaveValue('50');expect(await snapshot(page)).toBe(before);
 await d.getByRole('button',{name:'Pick centre on canvas'}).click();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Cancel pick'})).toBeFocused();await page.keyboard.press('Enter');await expect(d).toBeVisible();await expect(d.getByLabel('Centre X',{exact:true})).toHaveValue('50');
 await d.getByRole('button',{name:'Pick centre on canvas'}).click();await page.keyboard.press('Escape');await expect(d).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(d).toBeHidden();expect(await snapshot(page)).toBe(before);expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.some((s:any)=>s.data.control==='pattern-preview'))).toBe(false);
});

test('Circular copies preserve text editability, arc controls, fills, layers and original geometry',async({page})=>{
 await page.goto(DEV);const original=await page.evaluate(async()=>{
  const e=(window as any).__vectora,p=(window as any).__paper,{loadTextFont,createTextShape}=await import('/src/text.ts'),{createCircularArc}=await import('/src/arc.ts');await loadTextFont('lato');
  e.addShape(createTextShape({content:'Ab',sizeMM:8,fontId:'lato',transform:[1,0,0,1,20,25]}),'Label');const text=e.selected;
  e.addShape(new p.CompoundPath({insert:false,children:[new p.Path.Rectangle({insert:false,rectangle:[50,20,20,20]}),new p.Path.Circle({insert:false,center:[60,30],radius:3})]}),'Filled hole');const fill=e.selected;fill.data.regionFill=true;fill.data.regionFillColor='#00ff00';fill.fillColor='#00ff00';fill.strokeColor=null;fill.fillRule='evenodd';
  e.addShape(createCircularArc({cx:70,cy:60,radius:10,start:0,sweep:90}),'Arc');e.moveSelectionToCutPath();const arc=e.selected;e.select(text,true);e.select(fill,true);
  return e.objects.map((s:any)=>({uid:s.data.uid,json:s.exportJSON({precision:12})}));
 });
 const d=await open(page);await d.getByRole('tab',{name:'Circular',exact:true}).click();await d.getByLabel('Instances',{exact:true}).fill('2');await d.getByLabel('Centre X',{exact:true}).fill('40');await d.getByLabel('Centre Y',{exact:true}).fill('40');await d.getByRole('button',{name:'Apply',exact:true}).click();
 const result=await page.evaluate(original=>{const e=(window as any).__vectora,ids=original.map(o=>o.uid),copies=e.objects.filter((s:any)=>!ids.includes(s.data.uid)),text=copies.find((s:any)=>s.data.name==='Label'),fill=copies.find((s:any)=>s.data.name==='Filled hole'),arc=copies.find((s:any)=>s.data.name==='Arc');const snapshot=e.snapshot();e.restore(snapshot);return {originals:original.map(o=>e.objects.find((s:any)=>s.data.uid===o.uid).exportJSON({precision:12})),text:text.data.text,fill:{color:fill.fillColor.toCSS(true),rule:fill.fillRule,contours:fill.children.length,role:fill.data.role},arc:{...arc.data.arc,role:arc.data.role,color:arc.strokeColor.toCSS(true)},saved:e.objects.length};},original);
 expect(result.originals).toEqual(original.map(o=>o.json));expect(result.saved).toBe(6);expect(result.text.content).toBe('Ab');const matrix=[-1,0,0,-1,60,55];result.text.transform.forEach((n:number,i:number)=>expect(n).toBeCloseTo(matrix[i],8));expect(result.fill).toEqual({color:'#00ff00',rule:'evenodd',contours:2,role:'artwork'});expect(result.arc.cx).toBeCloseTo(10,8);expect(result.arc.cy).toBeCloseTo(20,8);expect(result.arc.start).toBe(180);expect(result.arc.radius).toBe(10);expect(result.arc.sweep).toBe(90);expect(result.arc.role).toBe('cutline');expect(result.arc.color).toBe('#ff0000');
});

test('Pattern limits prevent excessive geometry and out-of-range copies before insertion',async({page})=>{
 await setup(page);const before=await snapshot(page),d=await open(page);await d.getByLabel('Rows',{exact:true}).fill('1');await d.getByLabel('Columns',{exact:true}).fill('2');await d.getByLabel('Column spacing',{exact:true}).fill('1000000');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();expect(await snapshot(page)).toBe(before);await d.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.selected.removeSegments();e.selected.addSegments(Array.from({length:2000},(_,i)=>new p.Point(40+5*Math.cos(i*.1),40+5*Math.sin(i*.1))));});const complex=await snapshot(page);await open(page);await d.getByLabel('Rows',{exact:true}).fill('1');await d.getByLabel('Columns',{exact:true}).fill('100');await d.getByLabel('Column spacing',{exact:true}).fill('10');await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();await expect(d.getByRole('status')).toContainText('too detailed');expect(await snapshot(page)).toBe(complex);await page.keyboard.press('Escape');
});

test('Pattern search, themes and compact layouts keep controls reachable and icons resolved',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await setup(page);await page.getByRole('button',{name:'Search tools',exact:true}).click();await page.getByRole('combobox',{name:'Search tools'}).fill('circular pattern');await page.keyboard.press('Enter');const d=page.getByRole('dialog',{name:'Pattern',exact:true});await expect(d.getByRole('tab',{name:'Circular',exact:true})).toHaveAttribute('aria-selected','true');
 const broken=await d.evaluate(el=>[...el.querySelectorAll('use')].map(el=>el.getAttribute('href')!).filter(href=>!document.querySelector(href)));expect(broken).toEqual([]);
 for(const theme of ['dark','light']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await page.screenshot({path:`test-results/pattern-${theme}.png`,scale:'css'});}
 for(const viewport of [{width:390,height:700},{width:900,height:300}]){await page.setViewportSize(viewport);const box=await d.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(viewport.width);expect(box!.y+box!.height).toBeLessThanOrEqual(viewport.height);await d.getByRole('button',{name:'Apply',exact:true}).scrollIntoViewIfNeeded();await expect(d.getByRole('button',{name:'Apply',exact:true})).toBeInViewport();}
 await d.getByRole('button',{name:'Cancel',exact:true}).click();expect(errors).toEqual([]);
});

test('Preview stays out of exports and tool switching cancels it; applied copies preserve the selected arrangement',async({page})=>{
 await setup(page);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,first=e.selected;e.addShape(new p.Path.Rectangle({insert:false,rectangle:[55,35,10,10],strokeColor:'white'}),'Slot');e.select(first,true);});
 const exported=()=>page.evaluate(async()=>{const {exportSVG}=await import('/src/exportSVG.ts');return exportSVG((window as any).__vectora.objects);});const before=await snapshot(page),svg=await exported();const d=await open(page);await d.getByRole('tab',{name:'Circular',exact:true}).click();await d.getByLabel('Instances',{exact:true}).fill('4');await d.getByLabel('Centre X',{exact:true}).fill('50');await d.getByLabel('Centre Y',{exact:true}).fill('60');await d.getByLabel('Rotate copies',{exact:true}).uncheck();expect(await exported()).toBe(svg);
 await d.getByRole('button',{name:'Pick centre on canvas'}).click();await page.getByRole('button',{name:'Node editing',exact:true}).click();await expect(d).toBeHidden();await expect(page.getByRole('button',{name:'Cancel pick'})).toBeHidden();expect(await snapshot(page)).toBe(before);expect(await page.evaluate(()=>(window as any).__vectora.overlays.children.some((s:any)=>s.data.control==='pattern-preview'))).toBe(false);
 await open(page);await d.getByRole('tab',{name:'Circular',exact:true}).click();await d.getByLabel('Instances',{exact:true}).fill('4');await d.getByLabel('Centre X',{exact:true}).fill('50');await d.getByLabel('Centre Y',{exact:true}).fill('60');await d.getByLabel('Rotate copies',{exact:true}).uncheck();await d.getByRole('button',{name:'Apply',exact:true}).click();
 const centers=await page.evaluate(()=>(window as any).__vectora.objects.map((s:any)=>[s.bounds.center.x,s.bounds.center.y]).sort((a:number[],b:number[])=>a[1]-b[1]||a[0]-b[0]));const wanted=[[40,40],[60,40],[20,60],[40,60],[60,60],[80,60],[40,80],[60,80]];centers.forEach((p:number[],i:number)=>p.forEach((n,j)=>expect(n).toBeCloseTo(wanted[i][j],8)));expect(await exported()).not.toBe(svg);
});

test('Production pattern workflow creates editable copies and the reference uses the shared controls',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:4173');await page.getByRole('button',{name:'Snapping',exact:true}).click();await page.keyboard.press('r');await page.mouse.move(320,280);await page.mouse.down();await page.mouse.move(380,330);await page.mouse.up();const d=await open(page);await d.getByLabel('Columns',{exact:true}).fill('3');await d.getByLabel('Rows',{exact:true}).fill('1');await d.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.locator('#selection-menu .selection-count')).toHaveText('3 selected');await page.keyboard.press('Control+z');await expect(page.locator('#selection-menu .selection-count')).toHaveText('1 selected');
 await page.goto(DEV+'/reference/design-system.html');await expect(page.getByRole('group',{name:'Example pattern settings'})).toBeVisible();const broken=await page.getByRole('group',{name:'Example pattern settings'}).evaluate(el=>[...el.querySelectorAll('use')].map(u=>u.getAttribute('href')!).filter(href=>!document.querySelector(href)));expect(broken).toEqual([]);expect(errors).toEqual([]);
});

test('Copies keep the original stacking order even when objects were selected in reverse order',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;const add=(color:string,radius:number)=>{e.addShape(new p.Path.Circle({insert:false,center:[40,40],radius}),'Filled');const s=e.selected;s.data.regionFill=true;s.data.regionFillColor=color;s.fillColor=color;s.strokeColor=null;return s;};const blue=add('#0000ff',5),red=add('#ff0000',3);e.select(red);e.select(blue,true);});const d=await open(page);await d.getByLabel('Rows',{exact:true}).fill('1');await d.getByLabel('Columns',{exact:true}).fill('2');await d.getByLabel('Column spacing',{exact:true}).fill('30');await d.getByRole('button',{name:'Apply',exact:true}).click();const top=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;return [...e.objects].reverse().find((s:any)=>s.contains(new p.Point(70,40))).fillColor.toCSS(true);});expect(top).toBe('#ff0000');
});

test('Editing Properties during centre picking cancels the pattern before changing the source',async({page})=>{
 await page.goto(DEV);await page.evaluate(async()=>{const e=(window as any).__vectora,{createCircularArc}=await import('/src/arc.ts');e.addShape(createCircularArc({cx:60,cy:50,radius:10,start:0,sweep:90}),'Arc');});await page.getByRole('button',{name:'Properties',exact:true}).click();const d=await open(page);await d.getByRole('tab',{name:'Circular',exact:true}).click();await d.getByRole('button',{name:'Pick centre on canvas'}).click();await page.locator('#arc-flip').click();await expect(page.getByRole('button',{name:'Cancel pick'})).toBeHidden();expect(await page.evaluate(()=>{const e=(window as any).__vectora;return {count:e.objects.length,sweep:e.objects[0].data.arc.sweep,preview:e.overlays.children.some((s:any)=>s.data.control==='pattern-preview')};})).toEqual({count:1,sweep:-90,preview:false});
});
