import { test, expect } from '@playwright/test';
const DEV='http://127.0.0.1:5174';

test('object snaps use exact curves, finite lines, centres and visible document geometry',async({page})=>{
  await page.goto(DEV);await expect(page.locator('#wasm-status')).toHaveText('Outline engine ready');
  const result=await page.evaluate(async()=>{
    const p=(window as any).__paper,e=(window as any).__vectora;
    const {findObjectSnap}=await import('/src/objectSnapping.ts');
    const {createArc,createCircularArc}=await import('/src/arc.ts');
    const P=(x:number,y:number)=>new p.Point(x,y);
    const modes=(...names:string[])=>Object.fromEntries(['intersection','nearest','centre','tangent','perpendicular'].map(name=>[name,names.includes(name)])) as any;
    const add=(path:any,name='Line')=>{e.addShape(path,name);return path;};
    const line=add(new p.Path({segments:[[0,0],[20,0]],insert:false}));
    const vertical=add(new p.Path({segments:[[8,-10],[8,10]],insert:false}));
    const check=(hit:any,x:number,y:number,mode:string,tolerance=1e-7)=>{if(!hit||hit.mode!==mode||hit.point.getDistance(P(x,y))>tolerance)throw new Error(`${mode}: ${JSON.stringify(hit)} expected ${x},${y}`);};
    check(findObjectSnap([line,vertical],P(8.4,.3),1,modes('intersection','nearest')),8,0,'intersection');
    check(findObjectSnap([line],P(6.1,.2),1,modes('nearest')),6.1,0,'nearest');
    check(findObjectSnap([line],P(6.3,.2),1,modes('perpendicular'),P(6,10)),6,0,'perpendicular');
    if(findObjectSnap([line],P(20,.1),1,modes('perpendicular'),P(30,10)))throw new Error('Perpendicular extended beyond segment');
    if(findObjectSnap([line],P(6,.1),1,modes('perpendicular')))throw new Error('Perpendicular without anchor');
    const circle=add(new p.Path.Circle({center:[0,0],radius:10,insert:false}),'Circle');
    check(findObjectSnap([circle],P(.3,.2),1,modes('centre')),0,0,'centre');
    check(findObjectSnap([circle,line],P(10.2,.2),1,modes('intersection')),10,0,'intersection');
    check(findObjectSnap([circle],P(10.2,0),1,modes('nearest')),10,0,'nearest');
    const tangent=findObjectSnap([circle],P(-10/3,Math.sqrt(800/9)),1,modes('tangent','nearest'),P(-30,0));
    check(tangent,-10/3,Math.sqrt(800/9),'tangent',.005);
    const location=circle.getNearestLocation(tangent!.point);
    if(Math.abs(tangent!.point.subtract(P(-30,0)).normalize().cross(location.tangent))>1e-8)throw new Error('Not tangent to actual curve');
    check(findObjectSnap([circle],P(.1,-10),1,modes('tangent'),P(-30,-10)),0,-10,'tangent',1e-6);
    const ellipse=add(new p.Path.Ellipse({rectangle:[30,10,40,20],insert:false}),'Ellipse');ellipse.rotate(37);
    check(findObjectSnap([ellipse],P(50.2,20.1),1,modes('centre')),50,20,'centre');
    const curve=ellipse.curves[0],point=curve.getPointAtTime(.43),anchor=point.subtract(curve.getTangentAtTime(.43).multiply(40));
    check(findObjectSnap([ellipse],point.add([.1,.1]),1,modes('tangent'),anchor),point.x,point.y,'tangent',1e-6);
    const arc=add(createCircularArc({cx:70,cy:50,radius:10,start:20,sweep:130}),'Arc');
    check(findObjectSnap([arc],P(70.1,50),1,modes('centre')),70,50,'centre');
    const oldArc=add(createArc(P(100,50),P(110,60),P(120,50)),'Arc');
    check(findObjectSnap([oldArc],P(110.2,50),1,modes('centre')),110,50,'centre');
    const group=new p.Group({insert:false,children:[new p.Path({segments:[[0,0],[20,0]],insert:false})],applyMatrix:false});
    const transformed=group.children[0];group.rotate(30);group.translate([20,30]);e.artwork.addChild(group);
    const a=transformed.localToGlobal(transformed.firstSegment.point),b=transformed.localToGlobal(transformed.lastSegment.point),mid=a.add(b).divide(2);
    check(findObjectSnap([transformed],mid.add([.1,.1]),1,modes('nearest')),mid.x+.118301270189,mid.y+.068301270189,'nearest',1e-6);
    e.artwork.locked=true;check(findObjectSnap([circle],P(.1,.1),1,modes('centre')),0,0,'centre');
    e.artwork.visible=false;if(findObjectSnap([circle],P(.1,.1),1,modes('centre')))throw new Error('Hidden reference used');
    e.artwork.visible=true;e.artwork.locked=false;
    if(findObjectSnap([circle],P(.1,.1),1,modes('centre'),undefined,[circle]))throw new Error('Edited reference used');
    for(const zoom of [0.5,3.7795,100]){
      check(findObjectSnap([line],P(6,9/zoom),10/zoom,modes('nearest')),6,0,'nearest');
      if(findObjectSnap([line],P(6,11/zoom),10/zoom,modes('nearest')))throw new Error('Capture radius changed with zoom');
    }
    return {tangent:tangent!.point.toString()};
  });
  expect(result.tangent).toBeTruthy();
});

test('Snap options drive drawing, polyline constraints, overlays and history',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(DEV);await expect(page.locator('#wasm-status')).toHaveText('Outline engine ready');
  const options=page.getByRole('button',{name:'Settings',exact:true});
  await options.click();
  const menu=page.getByRole('dialog',{name:'Preferences',exact:true});
  for(const name of ['Intersection','Nearest','Centre','Tangent','Perpendicular'])await expect(menu.getByRole('switch',{name,exact:true})).not.toBeChecked();
  await menu.getByRole('switch',{name:'Centre',exact:true}).focus();
  await page.keyboard.press('Space');
  await expect(menu.getByRole('switch',{name:'Centre',exact:true})).toBeChecked();
  await menu.getByRole('switch',{name:'Centre',exact:true}).press('Escape');
  await expect(menu).toBeHidden();await expect(options).toBeFocused();
  await page.evaluate(()=>{const p=(window as any).__paper,e=(window as any).__vectora;p.view.center=new p.Point(0,0);e.addShape(new p.Path.Circle({center:[0,0],radius:20,strokeColor:'#383838',insert:false}),'Circle');e.select(null);});
  const screen=async(x:number,y:number)=>page.evaluate(({x,y})=>{const p=(window as any).__paper,v=p.view.projectToView(new p.Point(x,y));return {x:v.x,y:v.y};},{x,y});
  const mouse=async(x:number,y:number)=>{const pt=await screen(x,y);await page.mouse.move(pt.x,pt.y);};
  await page.locator('#cad-canvas').focus();await page.keyboard.press('l');
  await mouse(1,.5);
  await expect.poll(()=>page.evaluate(()=>(window as any).__vectora.activeObjectSnap?.mode)).toBe('centre');
  await page.mouse.down();await mouse(40,30);await page.mouse.up();
  expect(await page.evaluate(()=>{const s=(window as any).__vectora.selected;return [s.firstSegment.point.x,s.firstSegment.point.y];})).toEqual([0,0]);
  await page.evaluate(()=>{const e=(window as any).__vectora;e.setObjectSnap('centre',false);e.setObjectSnap('perpendicular',true);e.setSnapToGrid(false);});
  await page.keyboard.press('l');await mouse(40,10);await page.mouse.down();await mouse(30.5,22.4);
  await expect.poll(()=>page.evaluate(()=>(window as any).__vectora.activeObjectSnap?.mode)).toBe('perpendicular');
  await page.screenshot({path:'test-results/object-snap-perpendicular.png'});
  const preview=await page.evaluate(()=>{const e=(window as any).__vectora;return [e.activeObjectSnap.point.x,e.activeObjectSnap.point.y];});
  await page.mouse.up();
  expect(await page.evaluate(()=>{const s=(window as any).__vectora.selected;return [s.lastSegment.point.x,s.lastSegment.point.y];})).toEqual(preview);
  expect(await page.evaluate(()=>(window as any).__vectora.activeObjectSnap)).toBeNull();
  const after=await page.evaluate(()=>(window as any).__vectora.objects.length);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(after-1);await page.keyboard.press('Control+Shift+z');
  await page.evaluate(()=>{const e=(window as any).__vectora;e.setObjectSnap('perpendicular',false);e.setObjectSnap('tangent',true);});
  await page.keyboard.press('p');await mouse(-50,0);await page.mouse.down();await page.mouse.up();await mouse(-8,Math.sqrt(336));
  await expect.poll(()=>page.evaluate(()=>(window as any).__vectora.activeObjectSnap?.mode)).toBe('tangent');
  await page.mouse.down();await page.mouse.up();await page.keyboard.press('Enter');
  expect(await page.evaluate(()=>(window as any).__vectora.selected.segments.length)).toBe(2);
  await page.keyboard.press('l');await mouse(-50,0);await page.mouse.down();await page.keyboard.down('Shift');await mouse(-8,Math.sqrt(336));
  expect(await page.evaluate(()=>(window as any).__vectora.activeObjectSnap)).toBeNull();
  await page.keyboard.press('Escape');await page.mouse.up();await page.keyboard.up('Shift');
  await options.click();await page.screenshot({path:'test-results/object-snap-options.png'});
  await page.setViewportSize({width:390,height:750});
  const bounds=(await menu.boundingBox())!;expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(390);expect(bounds.y).toBeGreaterThanOrEqual(0);
  await menu.getByRole('switch',{name:'Perpendicular',exact:true}).scrollIntoViewIfNeeded();
  await expect(menu.getByRole('switch',{name:'Perpendicular',exact:true})).toBeInViewport();
  await page.screenshot({path:'test-results/object-snap-mobile.png'});
  expect(errors).toEqual([]);
});

test('object snaps move and resize to exact targets without grid rounding or exported guides',async({page})=>{
  await page.goto(DEV);await expect(page.locator('#wasm-status')).toHaveText('Outline engine ready');
  await page.evaluate(()=>{
    const p=(window as any).__paper,e=(window as any).__vectora;p.view.center=new p.Point(20,20);
    e.addShape(new p.Path.Circle({center:[0,0],radius:5,insert:false}),'Circle');
    e.addShape(new p.Path.Circle({center:[15.2,14.4],radius:2,insert:false}),'Circle');
    e.addShape(new p.Path.Rectangle({rectangle:[20,20,10,10],insert:false}),'Rectangle');
    e.setObjectSnap('centre',true);e.setTool('select');
  });
  const move=async(x:number,y:number)=>{const point=await page.evaluate(({x,y})=>{const p=(window as any).__paper,v=p.view.projectToView(new p.Point(x,y));return {x:v.x,y:v.y};},{x,y});await page.mouse.move(point.x,point.y);};
  await move(25,25);await page.mouse.down();await move(5.3,5.2);await page.mouse.up();
  const bounds=()=>page.evaluate(()=>{const b=(window as any).__vectora.selected.bounds;return [b.x,b.y,b.width,b.height];});
  expect(await bounds()).toEqual([0,0,10,10]);
  await move(10,10);await page.mouse.down();await move(15.5,14.2);
  expect(await page.evaluate(()=>(window as any).__vectora.activeObjectSnap?.mode)).toBe('centre');
  const exported=await page.evaluate(async()=>{const {exportDXF}=await import('/src/exportDXF.ts');return exportDXF((window as any).__vectora.objects,true);});
  expect(exported.match(/\r?\n0\r?\nLWPOLYLINE\r?\n/g)?.length).toBe(1);
  expect(exported.match(/\r?\n0\r?\nCIRCLE\r?\n/g)?.length).toBe(2);
  await page.mouse.up();const resized=await bounds();expect(resized[2]).toBeCloseTo(15.2,8);expect(resized[3]).toBeCloseTo(14.4,8);
  await page.keyboard.press('Control+z');expect(await bounds()).toEqual([0,0,10,10]);
  await page.evaluate(()=>(window as any).__vectora.setProperty('width',12.3456));expect((await bounds())[2]).toBeCloseTo(12.3456,8);
});

test('master magnet pauses all snapping and restores individual Preferences choices',async({page})=>{
  await page.goto(DEV);await expect(page.locator('#wasm-status')).toHaveText('Outline engine ready');
  await expect(page.locator('[data-snap-options]')).toHaveCount(0);
  const magnet=page.getByRole('button',{name:'Snapping',exact:true});
  const settings=page.getByRole('button',{name:'Settings',exact:true});
  await settings.click();const dialog=page.getByRole('dialog',{name:'Preferences',exact:true});
  for(const name of ['Intersection','Nearest','Centre','Tangent','Perpendicular'])await dialog.getByRole('switch',{name,exact:true}).check();
  await page.keyboard.press('Escape');
  await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;p.view.center=new p.Point(0,0);e.addShape(new p.Path.Circle({center:[0,0],radius:20,insert:false}),'Circle');e.setTool('line');});
  const move=async(x:number,y:number)=>{const point=await page.evaluate(({x,y})=>{const p=(window as any).__paper,v=p.view.projectToView(new p.Point(x,y));return {x:v.x,y:v.y};},{x,y});await page.mouse.move(point.x,point.y);};
  await move(1,.5);expect(await page.evaluate(()=>(window as any).__vectora.activeObjectSnap?.mode)).toBe('centre');
  const choices=await page.evaluate(()=>({...((window as any).__vectora.objectSnapModes)}));
  await magnet.click();await expect(magnet).toHaveAttribute('aria-pressed','false');
  await move(1,.5);expect(await page.evaluate(()=>(window as any).__vectora.activeObjectSnap)).toBeNull();
  await page.locator('#cad-canvas').focus();await page.keyboard.press('r');await move(27.2,12.7);await page.mouse.down();await move(41.4,26.2);await page.mouse.up();
  const bounds=await page.evaluate(()=>{const e=(window as any).__vectora,b=e.selected.bounds;return {bounds:[b.x,b.y,b.width,b.height],grid:e.gridSnappingActive};});
  expect(bounds.grid).toBe(false);for(const [i,value] of [27.2,12.7,14.2,13.5].entries())expect(bounds.bounds[i]).toBeCloseTo(value,4);
  expect(await page.evaluate(()=>(window as any).__vectora.objectSnapModes)).toEqual(choices);
  await settings.click();await expect(dialog.getByRole('switch',{name:'Enable snapping',exact:true})).not.toBeChecked();
  for(const name of ['Snap to grid','Intersection','Nearest','Centre','Tangent','Perpendicular'])await expect(dialog.getByRole('switch',{name,exact:true})).toBeChecked();
  await dialog.getByRole('switch',{name:'Nearest',exact:true}).uncheck();await dialog.getByRole('switch',{name:'Snap to grid',exact:true}).uncheck();
  await page.keyboard.press('Escape');await page.locator('#cad-canvas').focus();await page.keyboard.press('s');
  await expect(magnet).toHaveAttribute('aria-pressed','true');await page.keyboard.press('l');await move(1,.5);
  expect(await page.evaluate(()=>(window as any).__vectora.activeObjectSnap?.mode)).toBe('centre');
  expect(await page.evaluate(()=>{const e=(window as any).__vectora;return [e.objectSnapModes.nearest,e.snapToGridEnabled,e.gridSnappingActive];})).toEqual([false,false,false]);
  await settings.click();await expect(dialog.getByRole('switch',{name:'Enable snapping',exact:true})).toBeChecked();
  await dialog.getByRole('switch',{name:'Enable snapping',exact:true}).uncheck();await page.keyboard.press('Escape');await expect(magnet).toHaveAttribute('aria-pressed','false');
});
