import {test,expect,type Page} from './fixtures';
const DEV='http://127.0.0.1:5174';
async function seed(page:Page,kind:string){await page.goto(DEV);await page.evaluate(async kind=>{const e=(window as any).__vectora,p=(window as any).__paper,{buildCreationShape,creationFields}=await import('/src/shapeCreation.ts');const values=Object.fromEntries(creationFields(kind as any,{x:0,y:0}).map((f:any)=>[f.key,f.value]));Object.assign(values,{x:10,y:20,radius:15,count:6,length:40,angle:0});e.setActiveLayer('cutline');e.addShape(buildCreationShape(kind as any,values,'radius','dashed','#ff0000'),kind);e.setTool('select');},kind);await page.getByRole('button',{name:'Properties',exact:true}).click();}
async function change(page:Page,id:string,value:string){await page.locator(id).fill(value);await page.locator(id).press('Tab');}
const snap=(page:Page)=>page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()));

test('Circle Properties edits radius or diameter and centre with one undo while preserving style and layer',async({page})=>{
 await seed(page,'circle');const before=await snap(page);await expect(page.locator('#shape-radius')).toHaveValue('15');await expect(page.locator('#field-x')).toHaveValue('10');await change(page,'#shape-radius','12.375');const s=await page.evaluate(()=>{const e=(window as any).__vectora,s=e.selected;return {centre:[s.bounds.center.x,s.bounds.center.y],width:s.bounds.width,layer:s.layer.data.documentId,colour:s.strokeColor.toCSS(true),weight:s.strokeWidth,dash:s.dashArray,fill:s.fillColor};});expect(s).toEqual({centre:[10,20],width:24.75,layer:'cutline',colour:'#ff0000',weight:.4,dash:[1.6,.8],fill:null});await page.evaluate(()=>(window as any).__vectora.undo());expect(await snap(page)).toBe(before);await page.evaluate(()=>(window as any).__vectora.redo());await page.locator('#shape-measurement').selectOption('diameter');await expect(page.locator('#shape-radius')).toHaveValue('24.75');await change(page,'#shape-radius','50.5');await change(page,'#field-x','-3.125');const dimensions=await page.evaluate(()=>{const b=(window as any).__vectora.selected.bounds;return [b.center.x,b.center.y,b.width];});for(const [i,want] of [-3.125,20,50.5].entries())expect(dimensions[i]).toBeCloseTo(want,9);
});

test('Line Properties uses directed length and angle anchored to the first endpoint',async({page})=>{
 await seed(page,'line');await change(page,'#shape-length','37.7');await change(page,'#shape-angle','30');const points=await page.evaluate(()=>(window as any).__vectora.selected.segments.map((s:any)=>[s.point.x,s.point.y]));expect(points[0]).toEqual([10,20]);expect(points[1][0]).toBeCloseTo(42.649157723,8);expect(points[1][1]).toBeCloseTo(38.85,8);await change(page,'#field-y','-2.25');expect(await page.evaluate(()=>(window as any).__vectora.selected.firstSegment.point.y)).toBe(-2.25);
});

test('Polygon and Star radius, count and angle keep regular geometry after save, rotation and undo',async({page})=>{
 for(const kind of ['polygon','star']){await seed(page,kind);await change(page,'#shape-radius','20');const before=await snap(page);await change(page,'#shape-count','7');await change(page,'#shape-angle','30');const result=await page.evaluate(async()=>{const e=(window as any).__vectora,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts');const uid=e.selected.data.uid,saved=await decodeDocument(encodeDocument(e));e.restore(saved.snapshot);e.select(e.objects.find((s:any)=>s.data.uid===uid));return {points:e.selected.segments.map((s:any)=>[s.point.x,s.point.y]),layer:e.selected.layer.data.documentId};});expect(result.layer).toBe('cutline');expect(result.points).toHaveLength(kind==='star'?14:7);for(let i=0;i<result.points.length;i++)expect(Math.hypot(result.points[i][0]-10,result.points[i][1]-20)).toBeCloseTo(kind==='star'&&i%2?8:20,7);expect(result.points[0][0]).toBeCloseTo(27.320508076,7);expect(result.points[0][1]).toBeCloseTo(30,7);await page.evaluate(()=>{const e=(window as any).__vectora;e.undo();e.undo();});expect(await snap(page)).toBe(before);}
});

test('Arc Properties positions the centre and shares compact fields with creation; freeform and multi-selection keep bounds',async({page})=>{
 await seed(page,'arc');await change(page,'#field-x','-5.25');await change(page,'#arc-radius','12.5');await change(page,'#arc-sweep','-135');expect(await page.evaluate(()=>(window as any).__vectora.selectedArc)).toMatchObject({cx:-5.25,cy:20,radius:12.5,sweep:-135});await expect(page.locator('#shape-bounds-details')).toBeVisible();await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;e.addShape(new p.Path({insert:false,segments:[[0,0],[10,0],[5,7],[0,4]],closed:true}),'Edited path');});await expect(page.locator('#shape-radius')).toBeHidden();await expect(page.locator('#field-width')).toBeVisible();await change(page,'#field-width','20');expect(await page.evaluate(()=>(window as any).__vectora.selected.bounds.width)).toBe(20);await page.evaluate(()=>{const e=(window as any).__vectora;e.select(e.objects[0],true);});await expect(page.locator('#shape-radius')).toBeHidden();await expect(page.locator('#field-width')).toBeVisible();
});

test('Invalid shape edits and transformed freeform shapes cannot corrupt the document',async({page})=>{
 await seed(page,'polygon');const before=await snap(page);await change(page,'#shape-count','3.5');await expect(page.locator('#shape-count')).toHaveAttribute('aria-invalid','true');expect(await snap(page)).toBe(before);await change(page,'#shape-radius','0');expect(await snap(page)).toBe(before);await page.evaluate(()=>{const e=(window as any).__vectora;e.setProperty('width',50);});await expect(page.locator('#shape-radius')).toBeHidden();await expect(page.locator('#field-width')).toBeVisible();
});


test('Editing fields match creation styling and remain usable in all themes and narrow windows',async({page})=>{
 await seed(page,'circle');await page.setViewportSize({width:390,height:650});for(const theme of ['dark','light','high-contrast']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await expect(page.locator('#shape-bounds-details')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await expect(page.locator('#shape-bounds-details')).toHaveCSS('border-radius','0px');await page.locator('#shape-radius').scrollIntoViewIfNeeded();await page.screenshot({path:`test-results/edit-properties-${theme}.png`});await change(page,'#shape-radius','17.25');await expect(page.locator('#shape-radius')).toHaveValue('17.25');}
 const style=(el:Element)=>{const input=el.querySelector('input')!,prefix=el.querySelector('.number-prefix')!,shell=el.querySelector('.number-shell')!;return [getComputedStyle(input).padding,getComputedStyle(input).fontSize,getComputedStyle(prefix).minWidth,getComputedStyle(shell).height];};const editing=await page.locator('#shape-radius').locator('..').locator('..').evaluate(style);
 await page.evaluate(()=>(window as any).__vectora.setTool('circle'));expect(await page.locator('.object-creation [aria-label="Radius (millimetres)"]').locator('..').locator('..').evaluate(style)).toEqual(editing);
 await page.goto(DEV+'/reference/design-system.html');expect(await page.locator('#example-edit-shape-radius').locator('..').locator('..').evaluate(style)).toEqual(editing);await page.locator('#example-edit-shape-bounds-details summary').click();await expect(page.locator('#example-edit-field-width')).toBeVisible();
});

test('Only arcs show arc actions and all floating panels stay inside the workspace',async({page})=>{
 await seed(page,'circle');await expect(page.locator('#arc-semicircle')).toBeHidden();await expect(page.locator('#arc-flip')).toBeHidden();expect(await page.locator('#primary-layers-panel').evaluate(el=>!!el.closest('#workspace'))).toBe(true);
 await seed(page,'arc');await expect(page.locator('#arc-semicircle')).toBeVisible();await page.locator('#arc-semicircle').click();expect(await page.evaluate(()=>(window as any).__vectora.selectedArc.sweep)).toBe(180);
});

test('Rotating circles preserves radius through precise edits and saved documents',async({page})=>{
 await seed(page,'circle');await page.evaluate(()=>{const e=(window as any).__vectora;e.setRotation(30);});await expect(page.locator('#shape-radius')).toHaveValue('15');await change(page,'#shape-radius','12.375');const radius=await page.evaluate(async()=>{const e=(window as any).__vectora,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts'),{preciseGeometry}=await import('/src/shapeProperties.ts');const saved=await decodeDocument(encodeDocument(e));e.loadDocument(saved.snapshot,saved.view);e.select(e.objects[0]);return preciseGeometry(e.selected)?.radius;});expect(radius).toBeCloseTo(12.375,8);
});

test('Search Resize and Rotate reveal and focus their precise-shape bounds controls',async({page})=>{
 await seed(page,'circle');for(const [command,field] of [['Resize','#field-width'],['Rotate','#field-rotation']]){await page.getByRole('button',{name:'Search tools',exact:true}).click();await page.getByRole('combobox',{name:'Search tools'}).fill(command);await page.keyboard.press('Enter');await expect(page.locator(field)).toBeVisible();await expect(page.locator(field)).toBeFocused();}
});

test('Saved small circles retain radius editing, while node-edited curves keep generic bounds',async({page})=>{
 await seed(page,'circle');for(const radius of [.001,.1]){await page.evaluate(async radius=>{const e=(window as any).__vectora,p=(window as any).__paper,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts');e.addShape(new p.Path.Circle({insert:false,center:[10,20],radius}),'Circle');e.setRotation(30);const saved=await decodeDocument(encodeDocument(e));e.restore(saved.snapshot);e.select(e.objects[e.objects.length-1]);},radius);await expect(page.locator('#shape-radius')).toHaveValue(String(radius));await change(page,'#shape-radius',String(radius*2));await expect(page.locator('#shape-radius')).toHaveValue(String(radius*2));}
 await page.evaluate(()=>{const e=(window as any).__vectora;e.selected.firstSegment.point.x+=.05;e.changed();});await expect(page.locator('#shape-radius')).toBeHidden();await expect(page.locator('#field-width')).toBeVisible();
});

test('Narrow Properties stays unobstructed and restores the selection bar when closed or widened',async({page})=>{
 await seed(page,'circle');await page.setViewportSize({width:390,height:650});await expect(page.locator('#selection-menu')).toBeHidden();await page.locator('#shape-radius').scrollIntoViewIfNeeded();const input=page.locator('#shape-radius');expect(await input.evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===el;})).toBe(true);await input.click();await expect(input).toBeFocused();await page.locator('#close-properties').click();await expect(page.locator('#selection-menu')).toBeVisible();await page.getByRole('button',{name:'Properties',exact:true}).click();await expect(page.locator('#selection-menu')).toBeHidden();await page.setViewportSize({width:1280,height:900});await expect(page.locator('#selection-menu')).toBeVisible();
});
