import {test,expect,type Page} from './fixtures';
const DEV='http://127.0.0.1:5174';
async function picture(page:Page){const data=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=40;c.height=40;const x=c.getContext('2d')!;x.fillStyle='#ff0000';x.fillRect(0,0,20,40);x.fillStyle='#0000ff';x.fillRect(20,0,20,40);return c.toDataURL('image/png').split(',')[1];});return {name:'picture.png',mimeType:'image/png',buffer:Buffer.from(data,'base64')};}
async function open(page:Page){await page.locator('[data-generator-trigger]').click();await page.locator('[data-generator="paint-by-numbers"]').click();return page.locator('#paint-by-numbers-dialog');}
test('Paint generator uploads, previews, edits palette colours and inserts editable sheets into the canvas',async({page})=>{
 await page.goto(DEV);const file=await picture(page),d=await open(page);await expect(d.locator('[data-paint-insert]')).toBeDisabled();await d.locator('[data-paint-file]').setInputFiles(file);await expect(d.locator('[data-paint-insert]')).toBeEnabled();await expect(d.locator('[data-paint-status]')).toContainText('2 regions');await expect(d.locator('[data-paint-view] [data-paint-label]').first()).toHaveCSS('stroke','none');await expect(d.locator('[data-paint-palette] button')).toHaveCount(2);
 await d.getByRole('tab',{name:'Colour reference',exact:true}).click();await expect(d.locator('[data-paint-view] path[fill="#FF0000"]')).not.toHaveCount(0);await d.locator('[data-paint-palette] button').first().click();const picker=d.locator('#paint-numbers-colour-popover');await expect(picker).toBeVisible();await picker.getByLabel('Hex colour',{exact:true}).fill('#00FF00');await picker.getByLabel('Hex colour',{exact:true}).press('Enter');await picker.getByRole('button',{name:'Close colour picker'}).click();await expect(d.locator('[data-paint-view] path[fill="#00FF00"]')).not.toHaveCount(0);
 await d.locator('[data-paint-insert]').click();await expect(d).not.toBeVisible();const r=await page.evaluate(()=>{const e=(window as any).__vectora;return {layers:e.documentLayers.slice(-2).map((l:any)=>l.name),selectedLayer:e.selectedItems[0].layer.name,text:e.objects.filter((o:any)=>o.data.text).length,green:e.objects.some((o:any)=>o.fillColor?.toCSS(true)==='#00ff00')};});expect(r.layers).toEqual(['Paint by numbers','Colour reference']);expect(r.selectedLayer).toBe('Paint by numbers');expect(r.text).toBeGreaterThan(2);expect(r.green).toBe(true);await page.evaluate(()=>(window as any).__vectora.undo());expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(0);
});
test('Paint generator rejects broken images/settings, ignores stale work and cancels without changing the drawing',async({page})=>{
 await page.goto(DEV);const file=await picture(page),d=await open(page);await d.locator('[data-paint-file]').setInputFiles(file);await expect(d.locator('[data-paint-insert]')).toBeEnabled();await d.getByLabel('Colour count',{exact:true}).fill('33');await expect(d.locator('[data-paint-insert]')).toBeDisabled();await expect(d.locator('[data-paint-status]')).toContainText('2–32');await d.getByLabel('Colour count',{exact:true}).fill('4');await d.locator('[data-paint-file]').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('invalid')});await expect(d.locator('[data-paint-insert]')).toBeDisabled();await expect(d.locator('[data-paint-status]')).toContainText('header');await d.locator('[data-paint-file]').setInputFiles(file);await d.getByRole('button',{name:'Cancel',exact:true}).click();await expect(d).not.toBeVisible();expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(0);await expect(page.locator('[data-generator-trigger]')).toBeFocused();
});
test('Paint generator and reference share themes, keyboard controls and responsive preview layout',async({page})=>{
 for(const url of ['http://127.0.0.1:4173',DEV+'/reference/design-system.html']){await page.goto(url);const file=await picture(page),d=await open(page);await d.locator('[data-paint-file]').setInputFiles(file);await expect(d.locator('[data-paint-view] svg')).toBeVisible();if(url.includes('reference'))await expect(d.locator('[data-paint-insert]')).toBeDisabled();else await expect(d.locator('[data-paint-insert]')).toBeEnabled();await page.keyboard.press('Escape');await expect(d).not.toBeVisible();}
 await page.goto(DEV);await page.locator('[data-tool-search]').click();await page.locator('#tool-search-dialog input').fill('paint by numbers');await page.locator('.tool-search-result').first().click();const d=page.locator('#paint-by-numbers-dialog');await d.locator('[data-paint-file]').setInputFiles(await picture(page));await expect(d.locator('[data-paint-insert]')).toBeEnabled();await page.screenshot({path:'test-results/paint-desktop.png',scale:'css'});
 for(const theme of ['light','dark','high-contrast']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await expect(d.locator('[data-paint-view] path').first()).toHaveAttribute('fill','#FFFFFF');}await page.setViewportSize({width:390,height:550});await expect(d.locator('[data-paint-insert]')).toBeInViewport();const b=(await d.boundingBox())!;expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.width).toBeLessThanOrEqual(390);await page.screenshot({path:'test-results/paint-mobile.png',scale:'css'});await page.keyboard.press('Escape');
});
