import {test,expect} from './fixtures';
const DEV='http://127.0.0.1:5174';
test('Paint preview uses the same centred glyph geometry as editable canvas text',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {previewSheetSVG,loadLabelMetrics}=await import('/src/paintByNumbers/paperSheets.ts'),{createTextShape}=await import('/src/text.ts'),p=(window as any).__paper;await loadLabelMetrics();const item={kind:'text' as const,name:'Number 12',content:'12',x:40,y:50,sizeMM:3,colour:'#000000'},svg=previewSheetSVG({widthMM:210,heightMM:297,numbered:[item],reference:[]},'numbered'),element=new DOMParser().parseFromString(svg,'image/svg+xml').querySelector('[data-paint-label]')!,shape=new p.CompoundPath({insert:false,pathData:element.getAttribute('d')}),expected=createTextShape({content:'12',sizeMM:3,fontId:'lato',transform:[1,0,0,1,0,0]});const out={centre:[shape.bounds.center.x,shape.bounds.center.y],width:shape.bounds.width,height:shape.bounds.height,expected:[expected.bounds.width,expected.bounds.height],text:svg.includes('<text')};shape.remove();expected.remove();return out;});expect(r.centre[0]).toBeCloseTo(40,5);expect(r.centre[1]).toBeCloseTo(50,5);expect(r.width).toBeCloseTo(r.expected[0],5);expect(r.height).toBeCloseTo(r.expected[1],5);expect(r.text).toBe(false);
});
test('Paint sheets retain A4 size, aspect ratio, white pages, physical strokes and editable black labels',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {pageFrame,layoutSheets}=await import('/src/paintByNumbers/layout.ts'),{loadLabelMetrics,prepareSheets}=await import('/src/paintByNumbers/paperSheets.ts'),{processPaint}=await import('/src/paintByNumbers/process.ts'),{DEFAULT_PAGE}=await import('/src/paintByNumbers/types.ts'),p=(window as any).__paper;const metrics=await loadLabelMetrics(),frame=pageFrame(2,2,DEFAULT_PAGE),data=new Uint8ClampedArray(40*20*4);for(let i=0;i<800;i++)data.set(i%40<20?[255,0,0,255]:[0,0,255,255],i*4);const result=processPaint({width:40,height:20,data},{colours:2,cleanupMM2:10,imageWidthMM:frame.image.width,imageHeightMM:frame.image.height,labelSizeMM:3,metrics}),layout=layoutSheets(result,DEFAULT_PAGE),sheets=await prepareSheets(layout,new p.Point(100,100),true);const numbered=sheets[0].items,reference=sheets[1].items;const out={centred:layout.numbered.every((item,i)=>item.kind!=='text'||numbered[i].bounds.center.getDistance(new p.Point(item.x+100-105,item.y+100-148.5))<1e-8),frame,width:layout.widthMM,height:layout.heightMM,names:sheets.map(s=>s.name),page:numbered[0].bounds.toJSON(),white:numbered[0].fillColor.toCSS(true),strokes:numbered.filter(s=>s.strokeColor).map(s=>[s.strokeWidth,s.strokeScaling,s.strokeColor.toCSS(true)]),text:numbered.filter(s=>s.data.text).map(s=>[s.data.text.content,s.fillColor.toCSS(true)]),fills:reference.map(s=>s.fillColor?.toCSS(true)),bounds:sheets.map(s=>s.items[0].bounds.x)};sheets.forEach(s=>s.items.forEach(i=>i.remove()));return out;});expect(r.centred).toBe(true);expect(r.width).toBe(210);expect(r.height).toBe(297);expect(r.frame.image.width/r.frame.image.height).toBeCloseTo(2,6);expect(r.white).toBe('#ffffff');expect(r.names).toEqual(['Colour by numbers','Colour reference']);expect(r.strokes.every(([w,scale,c])=>w===.2&&scale===true&&c==='#000000')).toBe(true);expect(r.text.length).toBeGreaterThan(2);expect(r.text.every(([,c])=>c==='#000000')).toBe(true);expect(r.fills).toContain('#ff0000');expect(r.fills).toContain('#0000ff');expect(r.bounds[1]-r.bounds[0]).toBe(230);
});
test('Paint page presets and key layout bound labels, margins and custom page dimensions',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {pageFrame}=await import('/src/paintByNumbers/layout.ts'),{DEFAULT_PAGE}=await import('/src/paintByNumbers/types.ts');const a=pageFrame(1,32,{...DEFAULT_PAGE,preset:'a3',orientation:'landscape'}),b=pageFrame(1,32,{...DEFAULT_PAGE,preset:'custom',widthMM:300,heightMM:300});const bad=[{widthMM:NaN,preset:'custom'},{widthMM:30,preset:'custom'},{marginMM:150},{labelSizeMM:1},{lineWeightMM:0}].map(v=>{try{pageFrame(1,32,{...DEFAULT_PAGE,...v} as any);return false;}catch{return true;}});return {a,b,bad};});expect(r.a).toMatchObject({widthMM:420,heightMM:297});expect(r.b).toMatchObject({widthMM:300,heightMM:300});expect(r.a.keyY).toBeGreaterThanOrEqual(r.a.image.y+r.a.image.height);expect(r.bad.every(Boolean)).toBe(true);
});
