import {test,expect} from './fixtures';
const DEV='http://127.0.0.1:5174';
test('Paint label search finds narrow vertical limbs using the actual digit proportions',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {processPaint}=await import('/src/paintByNumbers/process.ts'),{loadLabelMetrics}=await import('/src/paintByNumbers/paperSheets.ts');const metrics=await loadLabelMetrics(),data=new Uint8ClampedArray(800*800*4);for(let y=300;y<500;y++)for(let x=280;x<520;x++)if(y<309||x>=396&&x<404)data.set([255,0,0,255],(y*800+x)*4);const result=processPaint({width:800,height:800,data},{colours:2,cleanupMM2:0,imageWidthMM:200,imageHeightMM:200,labelSizeMM:3,metrics});const [x,y]=result.regions[0].label,m=metrics[0],rx=(m.width*3/2+.2)*4,ry=(m.height*3/2+.2)*4;let fits=true;for(let Y=Math.floor(y-ry);Y<Math.ceil(y+ry);Y++)for(let X=Math.floor(x-rx);X<Math.ceil(x+rx);X++)fits&&=data[(Y*800+X)*4+3]===255;return {regions:result.regions.length,merged:result.mergedCount,fits};});expect(r).toEqual({regions:1,merged:0,fits:true});
});
test('Paint diagonal hole contacts remain independent simple contours with exact even-odd coverage',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {buildRegions}=await import('/src/paintByNumbers/regions.ts'),p=(window as any).__paper;const result=buildRegions({width:3,height:3,labels:new Int16Array([0,0,0,0,-1,0,0,0,-1]),palette:['#FF0000']},{colours:2,cleanupMM2:0,imageWidthMM:100,imageHeightMM:100,labelSizeMM:3,metrics:Array.from({length:32},(_,i)=>({number:i+1,left:0,top:0,width:.5,height:.8}))});const loops=result.regions[0].contours,path=new p.CompoundPath({insert:false,children:loops.map(c=>new p.Path({insert:false,segments:c,closed:true}))});path.fillRule='evenodd';const out={simple:loops.every(c=>new Set(c.map(p=>p.join(','))).size===c.length),intersections:path.getIntersections(path).length,area:path.area,hole:path.contains(new p.Point(1.5,1.5)),outside:path.contains(new p.Point(2.5,2.5))};path.remove();return out;});expect(r.simple).toBe(true);expect(r.area).toBe(7);expect(r.hole).toBe(false);expect(r.outside).toBe(false);
});
test('Paint palette preserves flat colours, reduces deterministically and respects transparent pixels',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{
  const {quantize}=await import('/src/paintByNumbers/quantize.ts');
  const solid=quantize({width:2,height:1,data:new Uint8ClampedArray([255,0,0,255,255,0,0,255])},12);
  const image={width:4,height:1,data:new Uint8ClampedArray([255,0,0,255,0,0,255,255,0,0,0,0,0,0,0,128])};
  const a=quantize(image,3),b=quantize(image,3);
  return {solid:{palette:solid.palette,labels:[...solid.labels]},palette:a.palette,labels:[...a.labels],repeat:JSON.stringify(a)===JSON.stringify(b)};
 });expect(r.solid).toEqual({palette:['#FF0000'],labels:[0,0]});expect(r.palette).toEqual(['#0000FF','#7F7F7F','#FF0000']);expect(r.labels[2]).toBe(-1);expect(r.repeat).toBe(true);
});
test('Paint palette bounds unique colours and rejects invalid source/count before allocating',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {quantize}=await import('/src/paintByNumbers/quantize.ts');const data=new Uint8ClampedArray(100*4);for(let i=0;i<100;i++)data.set([i*2,255-i*2,i,255],i*4);const source={width:10,height:10,data},a=quantize(source,8);const invalid=[()=>quantize(source,33),()=>quantize(source,2.5),()=>quantize({...source,width:Infinity},8),()=>quantize({...source,width:1201},8),()=>quantize({...source,data:new Uint8ClampedArray(3)},8)].map(fn=>{try{fn();return false;}catch{return true;}});return {palette:a.palette,labels:[...a.labels],invalid};});expect(new Set(r.palette).size).toBe(r.palette.length);expect(r.palette.length).toBeLessThanOrEqual(8);expect(new Set(r.labels).size).toBe(r.palette.length);expect(r.invalid.every(Boolean)).toBe(true);
});
test('Paint regions preserve shared borders, islands, holes and readable interior labels',async({page})=>{
 await page.goto(DEV);const results=await page.evaluate(async()=>{
  const {processPaint}=await import('/src/paintByNumbers/process.ts'),p=(window as any).__paper;
  const metrics=Array.from({length:32},(_,i)=>({number:i+1,left:0,top:0,width:i<9?.5:1,height:.8}));
  const cases=[{w:40,h:40,colour:(x:number,y:number)=>x<20?0:1},{w:40,h:40,colour:(x:number,y:number)=>x>=12&&x<28&&y>=12&&y<28?1:0},{w:4,h:4,colour:(x:number,y:number)=>(x+y)%2},{w:40,h:40,colour:(x:number)=>x<15?0:x<25?-1:0}];
  return cases.map(c=>{const data=new Uint8ClampedArray(c.w*c.h*4);let area=0;for(let y=0;y<c.h;y++)for(let x=0;x<c.w;x++){const n=c.colour(x,y);if(n>=0){data.set(n?[0,0,255,255]:[255,0,0,255],(y*c.w+x)*4);area++;}}
   const r=processPaint({width:c.w,height:c.h,data},{colours:2,cleanupMM2:0,imageWidthMM:100,imageHeightMM:100,labelSizeMM:3,metrics});let actual=0,crossings=0,inside=true,holes=0;
   for(const region of r.regions){const path=new p.CompoundPath({insert:false,children:region.contours.map(points=>new p.Path({insert:false,segments:points,closed:true}))});path.fillRule='evenodd';actual+=Math.abs(path.area);holes+=region.contours.length-1;crossings+=path.getCrossings(path).length;const m=metrics[region.paletteIndex],rx=m.width*3*c.w/100/2,ry=m.height*3*c.h/100/2;for(const [x,y] of [[-rx,-ry],[rx,-ry],[rx,ry],[-rx,ry],[0,0]])inside&&=path.contains(new p.Point(region.label[0]+x,region.label[1]+y));path.remove();}
   return {area,actual,crossings,inside,holes,regions:r.regions.length,repeat:JSON.stringify(r)===JSON.stringify(processPaint({width:c.w,height:c.h,data},{colours:2,cleanupMM2:0,imageWidthMM:100,imageHeightMM:100,labelSizeMM:3,metrics}))};});
 });for(const r of results){expect(r.actual).toBeCloseTo(r.area,6);expect(r.crossings).toBe(0);expect(r.inside).toBe(true);expect(r.repeat).toBe(true);}expect(results[1].holes).toBe(1);expect(results[2].regions).toBe(16);expect(results[3].regions).toBe(2);
});
test('Paint cleanup keeps coverage and rejects isolated unlabelable fragments and invalid settings',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {processPaint}=await import('/src/paintByNumbers/process.ts');const metrics=Array.from({length:32},(_,i)=>({number:i+1,left:0,top:0,width:1,height:1})),settings={colours:2,cleanupMM2:10,imageWidthMM:100,imageHeightMM:100,labelSizeMM:3,metrics};const data=new Uint8ClampedArray(40*40*4);for(let i=0;i<1600;i++)data.set([255,0,0,255],i*4);data.set([0,0,255,255],(20*40+20)*4);const a=processPaint({width:40,height:40,data},settings);const tiny=new Uint8ClampedArray(40*40*4);tiny.set([255,0,0,255],0);const invalid=[()=>processPaint({width:40,height:40,data:tiny},{...settings,imageWidthMM:10,imageHeightMM:10}),()=>processPaint({width:40,height:40,data:new Uint8ClampedArray(data.length)},settings),()=>processPaint({width:40,height:40,data},{...settings,labelSizeMM:NaN}),()=>processPaint({width:40,height:40,data},{...settings,metrics:[]})].map(fn=>{try{fn();return false;}catch{return true;}});return {regions:a.regions.length,pixels:a.regions.reduce((n,c)=>n+c.pixels,0),merged:a.mergedCount,invalid};});expect(r).toMatchObject({regions:1,pixels:1600});expect(r.merged).toBeGreaterThan(0);expect(r.invalid.every(Boolean)).toBe(true);
});
test('Paint photo-like gradients retain complete simple regions while excessive noise is bounded',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {processPaint}=await import('/src/paintByNumbers/process.ts'),p=(window as any).__paper;const w=120,h=100,data=new Uint8ClampedArray(w*h*4),metrics=Array.from({length:32},(_,i)=>({number:i+1,left:0,top:0,width:i<9?.5:1,height:.8}));for(let y=0;y<h;y++)for(let x=0;x<w;x++)data.set([Math.round(x/w*255),Math.round(y/h*255),Math.round((.5+.4*Math.sin(x/12+y/15))*255),255],(y*w+x)*4);const start=performance.now(),a=processPaint({width:w,height:h,data},{colours:12,cleanupMM2:10,imageWidthMM:190,imageHeightMM:160,labelSizeMM:3,metrics});let area=0,crossings=0;for(const region of a.regions){const path=new p.CompoundPath({insert:false,children:region.contours.map(c=>new p.Path({insert:false,segments:c,closed:true}))});area+=Math.abs(path.area);crossings+=path.getCrossings(path).length;path.remove();}const noise=new Uint8ClampedArray(200*200*4);for(let i=0;i<40000;i++)noise.set(i%200%2===Math.floor(i/200)%2?[255,0,0,255]:[0,0,255,255],i*4);let rejected=false;try{processPaint({width:200,height:200,data:noise},{colours:2,cleanupMM2:0,imageWidthMM:190,imageHeightMM:190,labelSizeMM:3,metrics});}catch(e){rejected=(e as Error).message.includes('too detailed');}return {area,crossings,rejected,regions:a.regions.length,elapsed:performance.now()-start};});expect(r.area).toBeCloseTo(12000,6);expect(r.crossings).toBe(0);expect(r.rejected).toBe(true);expect(r.regions).toBeGreaterThan(5);expect(r.elapsed).toBeLessThan(5000);
});
test('Paint physical cleanup uses the actual palette page fit and reserves thick-outline label clearance',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {processPaint}=await import('/src/paintByNumbers/process.ts'),{pageFrame}=await import('/src/paintByNumbers/layout.ts'),{DEFAULT_PAGE}=await import('/src/paintByNumbers/types.ts');const metrics=Array.from({length:32},(_,i)=>({number:i+1,left:0,top:0,width:.5,height:.8})),page={...DEFAULT_PAGE,labelSizeMM:1.5},frame=pageFrame(2/3,32,page),data=new Uint8ClampedArray(200*300*4);for(let i=0;i<60000;i++)data.set([255,0,0,255],i*4);for(let y=100;y<104;y++)for(let x=100;x<104;x++)data.set([0,0,255,255],(y*200+x)*4);const a=processPaint({width:200,height:300,data},{colours:32,cleanupMM2:10,imageWidthMM:frame.image.width,imageHeightMM:frame.image.height,labelSizeMM:1.5,metrics,page} as any);const tiny=new Uint8ClampedArray(40*40*4);tiny.set([255,0,0,255],(20*40+20)*4);let thick=false;try{processPaint({width:40,height:40,data:tiny},{colours:2,cleanupMM2:0,imageWidthMM:100,imageHeightMM:100,labelSizeMM:1.5,metrics,clearanceMM:1.1} as any);}catch{thick=true;}return {regions:a.regions.length,thick};});expect(r.regions).toBe(2);expect(r.thick).toBe(true);
});
