import {test,expect} from './fixtures';
const DEV='http://127.0.0.1:5174';
async function insert(page:any){return page.evaluate(async()=>{const {layoutSheets,pageFrame}=await import('/src/paintByNumbers/layout.ts'),{loadLabelMetrics,prepareSheets}=await import('/src/paintByNumbers/paperSheets.ts'),{processPaint}=await import('/src/paintByNumbers/process.ts'),{DEFAULT_PAGE}=await import('/src/paintByNumbers/types.ts'),p=(window as any).__paper,e=(window as any).__vectora;const frame=pageFrame(1,2,DEFAULT_PAGE),metrics=await loadLabelMetrics(),data=new Uint8ClampedArray(30*30*4);for(let i=0;i<900;i++)data.set(i%30<15?[255,0,0,255]:[0,0,255,255],i*4);const r=processPaint({width:30,height:30,data},{colours:2,cleanupMM2:10,imageWidthMM:frame.image.width,imageHeightMM:frame.image.height,labelSizeMM:3,metrics});e.addArtworkSheets(await prepareSheets(layoutSheets(r,DEFAULT_PAGE),p.view.center,true));return {count:e.objects.length,selected:e.selectedItems.length,layers:e.documentLayers.map((l:any)=>({name:l.name,role:l.data.objectRole,count:l.children.length})),selectedLayer:e.selectedItems[0].layer.name};});}
test('Paint canvas insertion uses new Artwork layers with one Undo, editable labels and saved explicit colours',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>(window as any).__vectora.setActiveLayer('cutline'));const r=await insert(page);expect(r.count).toBeGreaterThan(r.selected);expect(r.selectedLayer).toBe('Paint by numbers');expect(r.layers.slice(-2).map((l:any)=>[l.name,l.role])).toEqual([['Paint by numbers','artwork'],['Colour reference','artwork']]);
 const result=await page.evaluate(async()=>{const e=(window as any).__vectora,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts'),{exportSVG}=await import('/src/exportSVG.ts');const count=e.objects.length,selected=e.selectedItems.length,source=exportSVG(e.selectedItems),saved=encodeDocument(e);e.undo();const empty=e.objects.length,defaultLayers=e.documentLayers.length;e.redo();const restored=e.objects.length;const decoded=await decodeDocument(saved);e.loadDocument(decoded.snapshot,decoded.view);return {count,selected,empty,defaultLayers,restored,loaded:e.objects.length,text:e.objects.filter((o:any)=>o.data.text).length,source,page:e.objects.find((o:any)=>o.data.name==='White page').fillColor.toCSS(true),cutCount:e.cutlines.children.length};});expect(result.empty).toBe(0);expect(result.defaultLayers).toBe(5);expect(result.restored).toBe(result.count);expect(result.loaded).toBe(result.count);expect(result.text).toBeGreaterThan(2);expect(result.page).toBe('#ffffff');expect(result.cutCount).toBe(0);expect(result.source).toContain('width="210mm"');expect(result.source).toContain('height="297mm"');expect(result.source).not.toContain('Colour reference');
 await insert(page);expect(await page.evaluate(()=>(window as any).__vectora.documentLayers.slice(-2).map((l:any)=>l.name))).toEqual(['Paint by numbers 2','Colour reference 2']);
});
test('Paint rejected geometry and failed insertion preserve the complete document and history',async({page})=>{
 await page.goto(DEV);const result=await page.evaluate(()=>{const p=(window as any).__paper,e=(window as any).__vectora;e.addShape(new p.Path.Rectangle({insert:false,rectangle:[0,0,10,10]}),'Original');const before=JSON.stringify(e.snapshot()),undo=e.canUndo;const bad=new p.Path({insert:false,segments:[[0,0],[10,10]]});const old=bad._segments;bad._segments=new Array(500001);let limited=false;try{e.addArtworkSheets([{name:'Too big',items:[bad]}]);}catch{limited=true;}bad._segments=old;bad.remove();const afterLimit=JSON.stringify(e.snapshot())===before;const good=new p.Path.Rectangle({insert:false,rectangle:[0,0,5,5]}),method=e.insertDrawing;e.insertDrawing=()=>{throw new Error('Injected failure');};let failed=false;try{e.addArtworkSheets([{name:'Paint by numbers',items:[good]}]);}catch{failed=true;}e.insertDrawing=method;return {limited,afterLimit,failed,unchanged:JSON.stringify(e.snapshot())===before,undo:e.canUndo===undo,layers:e.documentLayers.length,objects:e.objects.length};});expect(result).toEqual({limited:true,afterLimit:true,failed:true,unchanged:true,undo:true,layers:5,objects:1});
});
