import {test,expect,type Page} from './fixtures';
const DEV='http://127.0.0.1:5174';
async function source(page:Page){await page.goto(DEV);return page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,c=p.view.center,s=new p.Path.Rectangle({insert:false,rectangle:[c.x-110,c.y-55,25,25],fillColor:'#2389B7'});s.data={rasterTrace:{mode:'colour'},regionFill:true,regionFillColor:'#2389B7',customColour:'#2389B7'};e.addTracedShapes([s],'Colour source');e.select(null);const v=p.view.projectToView(s.bounds.center),r=e.canvas.getBoundingClientRect();return {x:r.left+v.x,y:r.top+v.y};});}
async function open(page:Page,tab:string,trigger:string,name:string){await page.getByRole('button',{name:'Fill & appearance',exact:true}).click();await page.getByRole('tab',{name:tab,exact:true}).click();await page.getByRole('button',{name:trigger,exact:true}).click();const picker=page.getByRole('dialog',{name,exact:true});await expect(picker.getByRole('button',{name:'Pick colour from canvas',exact:true})).toHaveCount(1,{timeout:1500});return picker;}
test('Gradient stop eyedropper updates only that stop and stays open after picking',async({page})=>{
 const point=await source(page),picker=await open(page,'Gradient','Choose stop 1 colour','Stop 1 colour');const before=await page.evaluate(()=>(window as any).__vectora.fillPaint);await picker.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await page.mouse.move(point.x,point.y);await expect(page.locator('.colour-sample-hud')).toContainText('#2389B7');await page.mouse.click(point.x,point.y);
 await expect(picker).toBeVisible();await expect(picker.getByRole('textbox',{name:'Hex colour',exact:true})).toHaveValue('#2389B7');expect(await page.evaluate(()=>(window as any).__vectora.fillPaint)).toEqual({...before,stops:[{...before.stops[0],colour:'#2389B7'},...before.stops.slice(1)]});expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(1);
 const eyedropper=picker.getByRole('button',{name:'Pick colour from canvas',exact:true});await eyedropper.click();await page.keyboard.press('Escape');await expect(eyedropper).toBeFocused();await expect(picker).toBeVisible();
});
test('Pattern foreground and background pickers sample independently and can be cancelled',async({page})=>{
 const point=await source(page),picker=await open(page,'Pattern','Choose foreground colour','Foreground colour');await picker.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await page.mouse.click(point.x,point.y);await expect(picker).toBeVisible();expect(await page.evaluate(()=>(window as any).__vectora.fillPaint.foreground)).toBe('#2389B7');await picker.getByRole('button',{name:'Close colour picker',exact:true}).click();
 await page.getByRole('checkbox',{name:'Transparent background',exact:true}).uncheck();await page.getByRole('button',{name:'Choose background colour',exact:true}).click();const background=page.getByRole('dialog',{name:'Background colour',exact:true}),button=background.getByRole('button',{name:'Pick colour from canvas',exact:true});await button.click();await page.mouse.click(point.x,point.y);await expect(background).toBeVisible();expect(await page.evaluate(()=>(window as any).__vectora.fillPaint.background)).toBe('#2389B7');await button.click();await background.getByRole('button',{name:'Close colour picker',exact:true}).click();await expect(page.locator('.colour-sample-hud')).toHaveCount(0);
});
test('Layer colour pop-out samples canvas without changing Fill paint',async({page})=>{
 const point=await source(page);await page.getByRole('button',{name:'Layers',exact:true}).click();await page.getByRole('button',{name:'Add layer',exact:true}).click();await page.getByRole('menuitem',{name:'Artwork',exact:true}).click();await page.getByRole('button',{name:'Change Artwork 2 colour',exact:true}).click();const picker=page.getByRole('dialog',{name:'Layer colour',exact:true});await expect(picker.getByRole('button',{name:'Pick colour from canvas',exact:true})).toHaveCount(1,{timeout:1500});const before=await page.evaluate(()=>(window as any).__vectora.fillPaint);await picker.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await page.mouse.click(point.x,point.y);await expect(picker).toBeVisible();await expect(picker.getByRole('textbox',{name:'Hex colour',exact:true})).toHaveValue('#2389B7');expect(await page.evaluate(()=>(window as any).__vectora.activeLayer.data.colour)).toBe('#2389B7');expect(await page.evaluate(()=>(window as any).__vectora.fillPaint)).toEqual(before);
 await picker.getByRole('button',{name:'Close colour picker',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await page.evaluate(()=>(window as any).__vectora.activeLayer.data.colour)).not.toBe('#2389B7');
});

test('Sampling a stop changes selected filled Artwork in one Undo step',async({page})=>{
 const point=await source(page);const uid=await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper,c=p.view.center,s=new p.Path.Rectangle({insert:false,rectangle:[c.x-15,c.y-15,25,25],fillColor:'#FFFFFF'});s.data={rasterTrace:{mode:'colour'},regionFill:true,regionFillColor:'#FFFFFF',customColour:'#FFFFFF'};e.addTracedShapes([s],'Target');return s.data.uid;});
 const picker=await open(page,'Gradient','Choose stop 1 colour','Stop 1 colour');await picker.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await page.mouse.click(point.x,point.y);await expect(picker).toBeVisible();expect(await page.evaluate(()=>(window as any).__vectora.selected.data.fillPaint.stops[0].colour)).toBe('#2389B7');expect(await page.evaluate(()=>(window as any).__vectora.selected.data.uid)).toBe(uid);
 await picker.getByRole('button',{name:'Close colour picker',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await page.evaluate(()=>{const e=(window as any).__vectora;return {uid:e.selected.data.uid,fill:e.selected.fillColor.toCSS(true),count:e.objects.length};})).toEqual({uid,fill:'#ffffff',count:2});
});
test('The reference can sample from a pop-out and production pop-outs fit narrow screens',async({page,context})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(DEV+'/reference/design-system.html');const picker=await open(page,'Pattern','Choose foreground colour','Foreground colour');await picker.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();const r=(await page.getByLabel('Eyedropper sample artwork').boundingBox())!;await page.mouse.click(r.x+40,r.y+40);await expect(picker).toBeVisible();await expect(picker.getByRole('textbox',{name:'Hex colour',exact:true})).toHaveValue('#2389B7');
 const prod=await context.newPage();prod.on('pageerror',e=>errors.push(e.message));await prod.goto('http://127.0.0.1:4173');const popup=await open(prod,'Gradient','Choose stop 1 colour','Stop 1 colour');await prod.setViewportSize({width:375,height:650});await popup.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await prod.keyboard.press('Escape');await expect(popup).toBeVisible();await expect(popup.getByRole('button',{name:'Pick colour from canvas',exact:true})).toBeFocused();expect(await popup.locator('.colour-hex-row').evaluate(row=>{const r=row.getBoundingClientRect();return [...row.querySelectorAll('input,button,.colour-preview')].every(c=>{const b=c.getBoundingClientRect();return b.left>=r.left&&b.right<=r.right+1;});})).toBe(true);expect(errors).toEqual([]);await prod.screenshot({path:'test-results/popout-eyedropper-narrow.png'});
});
test('Focused pop-out pipette retains readable icon contrast in every theme',async({page})=>{
 await source(page);const picker=await open(page,'Pattern','Choose foreground colour','Foreground colour'),button=picker.getByRole('button',{name:'Pick colour from canvas',exact:true});
 for(const theme of ['dark','light','high-contrast']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await button.hover();await button.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');const ratio=await button.evaluate(el=>{const style=getComputedStyle(el),lum=(colour:string)=>{const channels=colour.match(/[\d.]+/g)!.slice(0,3).map(Number).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;});return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722;},a=lum(style.color),b=lum(style.backgroundColor);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);});expect(ratio).toBeGreaterThan(3);}
});

test('Gradient stops take sampled alpha while pattern and layer colours remain opaque',async({page})=>{
 const point=await source(page);await page.evaluate(()=>{const e=(window as any).__vectora;e.objects[0].opacity=.4;(window as any).__paper.view.update();});const picker=await open(page,'Gradient','Choose stop 1 colour','Stop 1 colour');await picker.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await page.mouse.click(point.x,point.y);expect(await page.evaluate(()=>(window as any).__vectora.fillPaint.stops[0].opacity)).toBeCloseTo(.4,2);await picker.getByRole('button',{name:'Close colour picker',exact:true}).click();
 await page.getByRole('tab',{name:'Pattern',exact:true}).click();await page.getByRole('button',{name:'Choose foreground colour',exact:true}).click();const foreground=page.getByRole('dialog',{name:'Foreground colour',exact:true});await foreground.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await page.mouse.click(point.x,point.y);expect(await foreground.locator('.colour-preview span').evaluate(el=>getComputedStyle(el).opacity)).toBe('1');expect(await page.evaluate(()=>(window as any).__vectora.fillPaint.opacity)).toBe(1);await foreground.getByRole('button',{name:'Close colour picker',exact:true}).click();
 await page.getByRole('button',{name:'Layers',exact:true}).click();await page.getByRole('button',{name:'Add layer',exact:true}).click();await page.getByRole('menuitem',{name:'Artwork',exact:true}).click();await page.getByRole('button',{name:'Change Artwork 2 colour',exact:true}).click();const layer=page.getByRole('dialog',{name:'Layer colour',exact:true});await layer.getByRole('button',{name:'Pick colour from canvas',exact:true}).click();await page.mouse.click(point.x,point.y);expect(await layer.locator('.colour-preview span').evaluate(el=>getComputedStyle(el).opacity)).toBe('1');
});
