import {test,expect} from './fixtures';
const DEV='http://127.0.0.1:5174';

test('Colour tracing keeps thin coloured details and transparent holes without number-fitting merges',async({page})=>{
 await page.goto(DEV);
 const r=await page.evaluate(async()=>{
  const {traceRaster}=await import('/src/rasterTrace.ts'),p=(window as any).__paper,w=160,data=new Uint8ClampedArray(w*w*4);let visible=0;
  for(let y=0;y<w;y++)for(let x=0;x<w;x++){const d=Math.hypot(x-80,y-80);if(d<15)continue;visible++;data.set(x===10&&y>=10&&y<30?[0,255,255,255]:d<40?[0,255,0,255]:d<45?[0,0,255,255]:[255,0,0,255],(y*w+x)*4);}
  const raw=traceRaster(data,w,w,128,'colour' as any,{colourCount:4,colourSmoothing:0,despeckleSize:0} as any),heavy=traceRaster(data,w,w,128,'colour' as any,{colourCount:4,colourSmoothing:2,despeckleSize:0} as any);
  const shapes=raw.paths.map((t:any)=>new p.CompoundPath({insert:false,pathData:t.svg,fillRule:'evenodd'})),hole=shapes.some((s:any)=>s.contains(new p.Point(80,80))),area=shapes.reduce((n:number,s:any)=>n+s.area,0),thin=shapes[raw.paths.findIndex((t:any)=>t.fill==='#00FFFF')]?.bounds.width;shapes.forEach((s:any)=>s.remove());
  return {colours:raw.paths.map((t:any)=>t.fill).sort(),thin,hole,area,visible,raw:raw.paths.length,heavy:heavy.paths.length,fractional:heavy.paths.flatMap(t=>t.points).filter(([x,y])=>!Number.isInteger(x)||!Number.isInteger(y)).length};
 });
 expect(r.colours).toEqual(['#0000FF','#00FF00','#00FFFF','#FF0000']);expect(r.thin).toBe(1);expect(r.hole).toBe(false);expect(r.area).toBe(r.visible);expect(r.heavy).toBe(r.raw);expect(r.fractional).toBeGreaterThan(40);
});

test('Colour mode previews smoothing and inserts coloured Artwork with saved holes, export and atomic history',async({page})=>{
 await page.goto(DEV);await page.evaluate(()=>(window as any).__vectora.setActiveLayer('cutline'));
 await page.getByRole('button',{name:'Images',exact:true}).click();await page.getByRole('menuitem',{name:'Raster to vector',exact:true}).click();
 const d=page.locator('#raster-dialog');await d.getByRole('radio',{name:'Colour',exact:true}).check();
 await expect(d.getByLabel('Smoothing',{exact:true})).toHaveValue('2');await expect(d.getByLabel('Threshold',{exact:true})).toBeHidden();
 const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=160;const ctx=c.getContext('2d')!;ctx.fillStyle='#ff0000';ctx.fillRect(0,0,160,160);ctx.fillStyle='#0000ff';for(let y=0;y<160;y++){const edge=Math.round(70+20*Math.sin(y/30));ctx.fillRect(edge,y,160-edge,1);}ctx.fillStyle='#00ff00';ctx.beginPath();ctx.arc(120,80,20,0,Math.PI*2);ctx.fill();ctx.clearRect(117,77,6,6);return c.toDataURL().split(',')[1];});
  await d.locator('#raster-file').setInputFiles({name:'colours.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await expect(d.locator('#raster-add')).toBeEnabled();
 await d.getByLabel('Colour count',{exact:true}).fill('2');await expect(d.locator('#raster-add')).toBeEnabled();expect(await d.locator('#raster-vector path').evaluateAll(paths=>new Set(paths.map(p=>p.getAttribute('fill'))).size)).toBe(2);await d.getByLabel('Colour count',{exact:true}).fill('16');await expect(d.locator('#raster-add')).toBeEnabled();
 const heavy=await d.locator('#raster-vector path').first().getAttribute('d');await d.getByLabel('Smoothing',{exact:true}).fill('0');await expect(d.locator('#raster-add')).toBeEnabled();expect(await d.locator('#raster-vector path').first().getAttribute('d')).not.toBe(heavy);
 await d.getByLabel('Smoothing',{exact:true}).fill('2');await expect(d.locator('#raster-add')).toBeEnabled();await page.screenshot({path:'test-results/raster-colour-preview.png'});await d.locator('#raster-add').click();
 const r=await page.evaluate(async()=>{const e=(window as any).__vectora,p=(window as any).__paper,{encodeDocument,decodeDocument}=await import('/src/documentFormat.ts'),{exportSVG}=await import('/src/exportSVG.ts');const objects=e.selectedItems,centre=p.view.center,report={count:objects.length,colours:objects.map((s:any)=>s.fillColor?.toCSS(true)).sort(),artwork:objects.every((s:any)=>s.layer===e.artwork&&!s.strokeColor),hole:objects.some((s:any)=>s.contains(centre.add([10,0]))),active:e.activeLayerId,width:e.selectionBounds.width,svg:exportSVG(objects)};const saved=encodeDocument(e),decoded=await decodeDocument(saved);e.restore(decoded.snapshot);const restored=e.objects.map((s:any)=>s.fillColor?.toCSS(true)).sort();e.undo();return {...report,restored,undone:e.objects.length};});
 expect(r).toMatchObject({count:3,colours:['#0000ff','#00ff00','#ff0000'],artwork:true,hole:false,active:'artwork',width:40});expect(r.restored).toEqual(r.colours);expect(r.undone).toBe(0);for(const c of r.colours)expect(r.svg.toLowerCase()).toContain(c);
});

test('Explicit neutral Colour vectors keep their colours through themes and operation-layer transfers',async({page})=>{
 await page.goto(DEV);await page.getByRole('button',{name:'Images',exact:true}).click();await page.getByRole('menuitem',{name:'Raster to vector',exact:true}).click();const d=page.locator('#raster-dialog');await d.getByRole('radio',{name:'Colour',exact:true}).check();const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=150;c.height=100;const ctx=c.getContext('2d')!;['#FFFFFF','#383838','#000000'].forEach((colour,i)=>{ctx.fillStyle=colour;ctx.fillRect(i*50,0,50,100);});return c.toDataURL().split(',')[1];});await d.locator('#raster-file').setInputFiles({name:'neutral.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await expect(d.locator('#raster-add')).toBeEnabled();await d.locator('#raster-add').click();
 const r=await page.evaluate(async()=>{const e=(window as any).__vectora,{applyArtworkTheme}=await import('/src/shapeStyles.ts'),{exportSVG}=await import('/src/exportSVG.ts');const colours=()=>e.selectedItems.map((s:any)=>s.fillColor?.toCSS(true)).sort();e.selectedItems.forEach((s:any)=>applyArtworkTheme(s,'#000000'));const themed=colours();e.moveSelectionToCutPath();const cuts=e.selectedItems.every((s:any)=>!s.fillColor&&s.strokeColor.toCSS(true)==='#ff0000');e.moveSelectionToLayer('artwork');return {themed,cuts,returned:colours(),svg:exportSVG(e.selectedItems)};});expect(r.themed).toEqual(['#000000','#383838','#ffffff']);expect(r.cuts).toBe(true);expect(r.returned).toEqual(r.themed);for(const c of r.themed)expect(r.svg.toLowerCase()).toContain(c);
});

test('Colour by Numbers is discoverable by its renamed menu, dialog and search',async({page})=>{
 await page.goto(DEV);await page.locator('[data-generator-trigger]').click();await page.getByRole('menuitem',{name:'Colour by numbers',exact:true}).click();await expect(page.getByRole('dialog',{name:'Colour by numbers',exact:true})).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Search tools',exact:true}).click();await page.getByRole('combobox',{name:'Search tools',exact:true}).fill('colour by numbers');await expect(page.getByRole('option',{name:/Colour by numbers/})).toBeVisible();
});

test('Colour tracing accepts the 1600px trace size and rejects invalid palette and smoothing settings',async({page})=>{
 await page.goto(DEV);const r=await page.evaluate(async()=>{const {traceRaster}=await import('/src/rasterTrace.ts'),w=1600,h=32,data=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++)data.set(x<800?[255,0,0,255]:[0,0,255,255],(y*w+x)*4);const valid=traceRaster(data,w,h,128,'colour' as any),bad=[{colourCount:1},{colourCount:33},{colourSmoothing:1.5},{colourSmoothing:3}].map(options=>{try{traceRaster(data,w,h,128,'colour' as any,options as any);return false;}catch{return true;}});return {paths:valid.paths.length,width:valid.width,height:valid.height,bad};});expect(r).toMatchObject({paths:2,width:1600,height:32,bad:[true,true,true,true]});
});

test('Colour mode switches back to Outline safely and blocks insertion into hidden or locked Artwork',async({page})=>{
 await page.goto(DEV);await page.getByRole('button',{name:'Images',exact:true}).click();await page.getByRole('menuitem',{name:'Raster to vector',exact:true}).click();const d=page.locator('#raster-dialog');await d.getByRole('radio',{name:'Colour',exact:true}).check();const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=100;const ctx=c.getContext('2d')!;ctx.fillStyle='#ff0000';ctx.fillRect(10,10,40,80);ctx.fillStyle='#0000ff';ctx.fillRect(50,10,40,80);return c.toDataURL().split(',')[1];});await d.locator('#raster-file').setInputFiles({name:'colour.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await expect(d.locator('#raster-add')).toBeEnabled();
 for(const state of ['locked','visible']){await page.evaluate(state=>{const e=(window as any).__vectora;e.setLayerState('artwork','locked',state==='locked');e.setLayerState('artwork','visible',state!=='visible');},state);await d.locator('#raster-add').click();await expect(d.locator('#raster-error')).toContainText('Show and unlock Artwork');expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(0);}
 await d.getByRole('radio',{name:'Outline',exact:true}).check();await expect(d.getByLabel('Threshold',{exact:true})).toBeVisible();await expect(d.getByLabel('Smoothing',{exact:true})).toBeHidden();await expect(d.locator('#raster-add')).toBeEnabled();await expect(d.locator('#raster-vector path')).toHaveAttribute('fill','none');await expect(d.getByRole('button',{name:'Binary',exact:true})).toBeVisible();await page.keyboard.press('Escape');
});

test('Production and reference Colour controls fit narrow windows and show matching smoothed colours',async({page})=>{
 await page.setViewportSize({width:420,height:700});
 for(const url of ['http://127.0.0.1:4173','http://127.0.0.1:5174/reference/design-system.html']){await page.goto(url);await page.locator('[data-image-trigger]').first().click();await page.locator('[data-raster-open]').first().click();const d=page.locator('#raster-dialog');await d.getByRole('radio',{name:'Colour',exact:true}).check();await expect(d.getByLabel('Colour count',{exact:true})).toBeVisible();await expect(d.getByLabel('Smoothing',{exact:true})).toBeVisible();const size=await d.evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.width);if(url.includes('reference')){await expect(d.locator('#raster-vector path')).toHaveCount(3);await d.getByLabel('Smoothing',{exact:true}).fill('0');await expect(d.locator('#raster-colourSmoothing-value')).toHaveText('Off');}await page.keyboard.press('Escape');}
});
