import {test,expect,Page} from '@playwright/test';
const DEV='http://127.0.0.1:5174';
async function setup(page:Page){await page.goto(DEV);await page.evaluate(()=>{const e=(window as any).__vectora,p=(window as any).__paper;for(const [i,r] of [[20,20,20,20],[30,30,20,20],[60,50,20,20]].entries())e.addShape(new p.Path.Rectangle({insert:false,rectangle:r,strokeColor:'white'}),'Shape '+i);e.select(e.objects[0],true);e.select(e.objects[1],true);});}

test('Selection menu groups alignment and shape operations into icon-only pop-outs',async({page})=>{
 await setup(page);const bar=page.locator('#selection-menu'),align=bar.getByRole('button',{name:'Align and distribute',exact:true}),operations=bar.getByRole('button',{name:'Shape operations',exact:true});await expect(align).toHaveCount(1);await expect(operations).toHaveCount(1);const width=(await bar.boundingBox())!.width;expect(width).toBeLessThan(550);
 await align.click();const a=page.getByRole('menu',{name:'Align and distribute',exact:true});await expect(a).toBeVisible();await expect(a.getByRole('menuitem')).toHaveCount(8);expect((await a.innerText()).trim()).toBe('');await expect(align).toHaveAttribute('aria-expanded','true');await expect(a.getByRole('menuitem',{name:'Align left',exact:true})).toBeFocused();
 await operations.click();const b=page.getByRole('menu',{name:'Shape operations',exact:true});await expect(a).toBeHidden();await expect(b.getByRole('menuitem')).toHaveCount(3);expect((await b.innerText()).trim()).toBe('');await b.getByRole('menuitem',{name:'Weld',exact:true}).click();await expect(b).toBeHidden();expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(1);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>(window as any).__vectora.objects.length)).toBe(3);
});

test('Pop-outs support keyboard navigation, Escape, toggling and outside dismissal without editing',async({page})=>{
 await setup(page);const before=await page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot())),trigger=page.getByRole('button',{name:'Align and distribute',exact:true}),menu=page.getByRole('menu',{name:'Align and distribute',exact:true});await trigger.click();await page.keyboard.press('ArrowRight');await expect(menu.getByRole('menuitem',{name:'Align centre',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(menu.getByRole('menuitem',{name:'Distribute vertically',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(menu).toBeHidden();await expect(trigger).toBeFocused();expect(await page.evaluate(()=>JSON.stringify((window as any).__vectora.snapshot()))).toBe(before);
 await trigger.click();await trigger.click();await expect(menu).toBeHidden();await trigger.click();await page.getByRole('button',{name:'Properties',exact:true}).click();await expect(menu).toBeHidden();await trigger.click();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(menu).toBeHidden();
});

test('Pop-outs attach without a gap, remain above chrome and clamp after moving or resizing the selection menu',async({page})=>{
 await setup(page);const bar=page.locator('#selection-menu'),trigger=page.getByRole('button',{name:'Align and distribute',exact:true}),menu=page.getByRole('menu',{name:'Align and distribute',exact:true});await trigger.click();let bounds=(await menu.boundingBox())!,root=(await bar.boundingBox())!;expect(Math.abs(bounds.y+bounds.height-root.y)).toBeLessThanOrEqual(1);
 await page.keyboard.press('Escape');await page.locator('#selection-menu-grip').focus();await page.keyboard.down('Shift');for(let i=0;i<90;i++)await page.keyboard.press('ArrowUp');await page.keyboard.up('Shift');await trigger.click();bounds=(await menu.boundingBox())!;root=(await bar.boundingBox())!;expect(Math.abs(bounds.y-root.y-root.height)).toBeLessThanOrEqual(1);
 for(const theme of ['dark','light']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const size of [{width:390,height:700},{width:900,height:300}]){await page.setViewportSize(size);await expect.poll(async()=>{const b=await menu.boundingBox();return !!b&&b.x>=0&&b.y>=0&&b.x+b.width<=size.width&&b.y+b.height<=size.height;}).toBe(true);for(const item of await menu.getByRole('menuitem').all())await expect(item).toBeInViewport();}await page.screenshot({path:`test-results/selection-popouts-${theme}.png`,scale:'css'});}
 await menu.getByRole('menuitem',{name:'Align left',exact:true}).click();await expect(menu).toBeHidden();expect(await page.evaluate(()=>(window as any).__vectora.objects.map((s:any)=>s.bounds.left))).toEqual([30,30,30]);
});

test('Reference pop-outs use the same icon-only controls and keyboard dismissal',async({page})=>{
 await page.goto(DEV+'/reference/design-system.html');const trigger=page.locator('#floating-menu').getByRole('button',{name:'Align and distribute',exact:true});await trigger.click();const menu=page.getByRole('menu',{name:'Align and distribute',exact:true});await expect(menu.getByRole('menuitem')).toHaveCount(8);await page.keyboard.press('Escape');await expect(menu).toBeHidden();await expect(trigger).toBeFocused();await trigger.click();await menu.getByRole('menuitem',{name:'Align left',exact:true}).click();await expect(menu).toBeHidden();await expect(page.locator('#floating-status')).toContainText('Align left');
});
