import { calculateChipLoad, calculateFeedRate, createToolStore, FACTORY_TOOLS, recalculateTool, TOOL_STORAGE_KEY, validateTool, type ToolStorage } from "../src/cam/toolStore";
import { buildManufacturingPlan, createDefaultProcesses, toolProcessDefaults } from "../src/cam/processModel";
import { documentModel } from "../src/document/DocumentModel";
import { compileGcode, DEFAULT_GRBL_LASER_PROFILE, validatePreflight } from "../src/cam/gcodeCompiler";
import { optimizeToolpaths } from "../src/cam/optimizer";
import type { RectangleEntity } from "../src/document/types";
import { usePresetStore } from "../src/store/usePresetStore";
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function close(a: number, b: number) { assert(Math.abs(a - b) < 1e-8, `${a} != ${b}`); }
function rejects(fn: () => unknown) { let threw = false; try { fn(); } catch { threw = true; } assert(threw, "Expected rejection"); }
let serialized: string | null = null;
const storage: ToolStorage = { getItem: key => key === TOOL_STORAGE_KEY ? serialized : null, setItem: (key, value) => { assert(key === "vectora_tools", "Storage key"); serialized = value; } };
const store = createToolStore(storage);
const factory = FACTORY_TOOLS[0]!;
assert(Object.isFrozen(FACTORY_TOOLS) && FACTORY_TOOLS.every(Object.isFrozen), "Factory immutability");
rejects(() => store.getState().updateTool(factory.id, { name: "oops" }));
rejects(() => store.getState().deleteTool(factory.id));
const custom = store.getState().addTool({ ...factory, id: "custom", name: "Aluminium rougher" });
assert(Object.isFrozen(custom) && storage.getItem(TOOL_STORAGE_KEY)?.includes('"custom"'), "Creation and persistence");
assert(!storage.getItem(TOOL_STORAGE_KEY)!.includes('"id":"factory-'), "Only custom tools persist");
rejects(() => store.getState().addTool(custom));
const edited = store.getState().updateTool(custom.id, { recommendedRPM: 18000, flutes: 3 });
close(edited.recommendedFeed, 1350);
close(store.getState().updateTool(custom.id, { recommendedFeed: 810 }).chipLoad, 0.015);
close(calculateFeedRate(12000, 2, 0.025), 600);
close(calculateChipLoad(600, 12000, 2), 0.025);
close(recalculateTool({ ...factory, chipLoad: 0.05 }, "chipLoad").recommendedFeed, 1200);
for (const fn of [() => calculateFeedRate(0, 2, 1), () => calculateFeedRate(1, 1.5, 1), () => calculateChipLoad(1, NaN, 2), () => validateTool({ ...factory, diameter: -1 }), () => validateTool({ ...factory, defaultStepover: 1.01 }), () => validateTool({ ...factory, recommendedFeed: 1 })]) rejects(fn);
validateTool({ ...factory, defaultStepover: 0 }); validateTool({ ...factory, defaultStepover: 1 });
const restored = createToolStore(storage);
assert(restored.getState().tools.find(t => t.id === custom.id)?.recommendedFeed === 810, "Reload persisted updates");
serialized = JSON.stringify({ version: 1, tools: [custom, custom, factory, { ...custom, id: "bad", diameter: NaN }] });
assert(createToolStore(storage).getState().tools.length === FACTORY_TOOLS.length + 1, "Hydration rejects corrupt/duplicate/reserved records");
serialized = "broken json";
assert(createToolStore(storage).getState().tools.length === FACTORY_TOOLS.length, "Malformed storage fallback");
const blocked = createToolStore({ getItem: () => null, setItem: () => { throw new Error("quota"); } });
blocked.getState().addTool(custom); assert(blocked.getState().storageError, "Storage failure surfaced");
restored.getState().selectTool("document", custom);
assert(restored.getState().deleteTool(custom.id), "Delete existing");
assert(restored.getState().selectedByDocument.document === null, "Deleted tool selection cleared");
assert(!restored.getState().deleteTool(custom.id), "Delete missing");
assert(createToolStore(storage).getState().tools.length === FACTORY_TOOLS.length, "Deletion persists");
const laser = FACTORY_TOOLS.find(t => t.type === "laser")!;
assert(recalculateTool(laser, "recommendedFeed").recommendedFeed === laser.recommendedFeed, "Laser feed independent");
assert(toolProcessDefaults(laser).spindleRPM === undefined, "Laser has no spindle RPM");
const inchDefaults = toolProcessDefaults(factory, 25.4);
close(inchDefaults.kerfWidth!, 0.125); close(inchDefaults.cutFeedRate!, 600 / 25.4); close(inchDefaults.pocket!.stepoverPct!, 60);
const pixelDefaults = toolProcessDefaults(factory, 0.25); close(pixelDefaults.kerfWidth!, 12.7); close(pixelDefaults.vectorStepdown!, 4);
const layerId = documentModel.getActiveLayer().id;
const rectangle: RectangleEntity = { id: "tool-cut", type: "rectangle", layerId, intent: "cut", visible: true, locked: false,
  style: { strokeColor: null, strokeWidth: 1, fillColor: null, dashArray: [] }, origin: { x: 10, y: 10 }, width: 25, height: 25, cornerRadius: 0, bbox: { minX: 10, minY: 10, maxX: 35, maxY: 35 } };
documentModel.addEntity(rectangle);
documentModel.addEntity({ ...rectangle, id: "tool-engrave", intent: "engrave", origin: { x: 50, y: 10 }, bbox: { minX: 50, minY: 10, maxX: 75, maxY: 35 } });
documentModel.addEntity({ ...rectangle, id: "tool-pocket", intent: "pocket", origin: { x: 90, y: 10 }, bbox: { minX: 90, minY: 10, maxX: 115, maxY: 35 } });
const defaults = toolProcessDefaults(factory);
const processes = createDefaultProcesses({ ...defaults, vectorDepth: 2.5, vectorStepdown: 1, pocket: { ...defaults.pocket!, depth: 2.5 }, leadIn: { leadType: "ramp", leadLength: 3, leadAngle: 90, rampAngle: 10 } });
const plan = optimizeToolpaths(buildManufacturingPlan(documentModel.getDocument(), { processes }));
assert(plan.toolpaths.some(p => p.processType === "pocket"), "Pocket generated");
for (const p of plan.toolpaths) { close(p.feedRate, 600); close(p.spindleRPM!, 12000); assert(p.tool?.id === factory.id && p.passes === 3, "Snapshot and depth passes propagated"); }
const profile = { ...DEFAULT_GRBL_LASER_PROFILE, mode: "spindle" as const, safeZ: 5, stockSurfaceZ: 0, workZ: -2.5 };
assert(!validatePreflight(plan, profile).hasCriticalErrors, "Tool plan preflight");
const gcode = compileGcode(plan, profile);
assert(gcode.includes("M3 S12000"), "RPM emitted without power normalization");
for (const depth of ["Z-1", "Z-2", "Z-2.5"]) assert(gcode.includes(depth), `Depth ${depth}`);
assert(validatePreflight(plan, DEFAULT_GRBL_LASER_PROFILE).hasCriticalErrors, "Milling tool rejected in laser mode");
const invalid = { ...plan, toolpaths: plan.toolpaths.map(p => ({ ...p, tool: { ...factory, maxStepdown: 0.1 } })) };
assert(validatePreflight(invalid, profile).hasCriticalErrors, "Cutter maximum enforced");
const badRPM = { ...plan, toolpaths: plan.toolpaths.map(p => ({ ...p, spindleRPM: NaN })) };
assert(validatePreflight(badRPM, profile).hasCriticalErrors, "Nonfinite RPM rejected");
const mixed = { ...plan, toolpaths: plan.toolpaths.map((p, index) => index ? p : { ...p, tool: FACTORY_TOOLS[1]! }) };
assert(validatePreflight(mixed, profile).hasCriticalErrors, "No unconfigured automatic tool changes");
const preset = usePresetStore.getState().addPreset({ id: "tool-rpm-preset", name: "Tool spindle test", thicknessMm: 3, kerfMm: factory.diameter, cut: { feedRate: 600, power: 1000, passes: 3, spindleRPM: 12000, cutDepth: 2.5, stepdown: 1 } });
assert(preset.cut?.spindleRPM === 12000 && preset.cut.stepdown === 1, "Material preset retains spindle fields");
console.log("Tool store: immutable factories, CRUD/reload, corrupt storage, reciprocal chip load, physical units, CAM propagation, depth passes, RPM output and mode/max-stepdown validation passed.");
