export interface HelpTopic {id:string;title:string;icon:string;summary:string;keywords?:string;body:string}
const keys=(value:string)=>value.split(' + ').map(key=>`<kbd>${key}</kbd>`).join(' + ');
const command=(key:string)=>keys(`Ctrl / ⌘ + ${key}`);
const table=(head:string[],rows:string[][])=>`<div class="help-table-wrap"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const steps=(items:string[])=>`<ol class="help-steps">${items.map(item=>`<li>${item}</li>`).join('')}</ol>`;
const go=(id:string,text:string)=>`<button type="button" class="help-link" data-help-go="${id}">${text}<span aria-hidden="true"> →</span></button>`;
const diagram=(label:string,paths:string)=>`<svg class="help-illustration" role="img" aria-label="${label}" viewBox="0 0 320 120"><g fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${paths}</g></svg>`;

/** Shared, local guide content for the editor and the design-system reference. */
export const HELP_TOPICS:readonly HelpTopic[]=[
 {id:'start',title:'Start here',icon:'help',summary:'A quick route from a blank canvas to an exportable design.',keywords:'welcome overview beginner getting started tutorial',body:`
 <div class="help-intro"><span class="help-eyebrow">YOUR WORKSPACE, IN MILLIMETRES</span><h3>Draw precisely. Make it your own.</h3><p>Vectora is a 2D drawing app for artwork, cut paths and engraving designs. Draw on the grid, refine your geometry, then save an editable project or export your vectors.</p></div>
 <div class="help-cards"><article><svg aria-hidden="true"><use href="#i-shapes"/></svg><h3>1. Draw</h3><p>Choose a layer, pick a tool on the left, and draw on the canvas.</p>${go('drawing','Drawing tools')}</article><article><svg aria-hidden="true"><use href="#i-sliders"/></svg><h3>2. Refine</h3><p>Select an object. Open Properties for exact dimensions, or edit its nodes.</p>${go('editing','Editing paths')}</article><article><svg aria-hidden="true"><use href="#i-save"/></svg><h3>3. Save &amp; export</h3><p>Save a .vectora file to keep editing, or export SVG and DXF for other tools.</p>${go('files','Save & export')}</article></div>
 <h3>Your first rectangle</h3>${steps(['Click Artwork in the Layers panel to make it active.','Press <kbd>R</kbd> and drag on the canvas. Press <kbd>V</kbd> to return to Select.','With the rectangle selected, open Properties on the right. Enter a width and height in mm.','Use File → Save to keep an editable copy.'])}
 <div class="help-note">Looking for a command? The magnifying glass in the top toolbar searches the app’s tools. Search in this Help window to find instructions.</div>${go('examples','Try a worked example')}`},
 {id:'shortcuts',title:'Keyboard shortcuts',icon:'text',summary:'A compact reference for drawing, editing and documents.',keywords:'keyboard commands hotkeys keys mac windows cmd command control',body:`
 <p>Use <kbd>⌘</kbd> on macOS and <kbd>Ctrl</kbd> on Windows or Linux. Drawing shortcuts work when you are not typing into a field. Click the canvas to return to drawing.</p>
 <h3>Drawing tools</h3>${table(['Key','Tool'],[['V','Select'],['N','Node editing'],['L','Line'],['P','Polyline'],['F','Freehand'],['R','Rectangle'],['C','Circle'],['E','Ellipse'],['Y','Polygon'],['Shift + Y','Star'],['A','Centre arc'],['Shift + A','Three-point arc'],['T','Text'],['D','Aligned dimension'],['B','Colour fill'],['K','Dissect delete'],['Shift + K','Line delete'],['S','Toggle snapping']].map(([key,label])=>[keys(key),label]))}
 <p>Choose Heart from Shapes, and Start–end arc, the other dimension tools and Raster to vector from their toolbar menus.</p>
 <h3>Editing &amp; documents</h3>${table(['Shortcut','Action'],[[command('Z'),'Undo'],[command('Shift + Z')+' or '+command('Y'),'Redo'],[command('C'),'Copy selected objects'],[command('V'),'Paste copied objects'],[keys('Delete')+' / '+keys('Backspace'),'Delete selection, or the active node in Node editing'],[command('N'),'New document'],[command('O'),'Open .vectora document'],[command('S'),'Save'],[command('Shift + S'),'Save As'],[command('E'),'Open export settings (SVG)'],[command('Shift + E'),'Open export settings (DXF)'],[keys('F1'),'Open Help']])}
 <p>All formats are available through File → Export…. Browser-reserved shortcuts may depend on your browser and operating system.</p>
 <h3>While drawing or typing</h3>${table(['Key / gesture','Action'],[[keys('Space')+' + drag','Pan the canvas'],[keys('Shift'),'Constrain proportions or angles for the current tool'],[keys('Enter'),'Finish a polyline; add a new line while typing text'],[keys('Backspace'),'Remove the last polyline or arc point while drawing'],[keys('↑')+' / '+keys('↓'),'Increase / decrease polygon sides or star points'],[keys('Escape'),'Cancel an unfinished action; otherwise clear selection'],[command('Enter')+' / '+keys('Tab'),'Finish editing canvas text']])}`},
 {id:'canvas',title:'Canvas & snapping',icon:'grid',summary:'Move around your drawing and place geometry accurately.',keywords:'controls navigation zoom pan mouse scroll trackpad ruler grid polar hexagonal triangular isometric dots no grid angle preferences',body:`
 ${table(['Control','What it does'],[['Scroll over the canvas','Zoom around the pointer.'],['Hold Space and drag','Pan without moving your objects.'],['Click the zoom percentage in the bottom bar','Reset to 100% around the current view centre.'],['Left and bottom rulers','Read positions and distances in millimetres.'],['Magnet at the bottom of the left toolbar, or S','Pause or resume snapping without losing the configured snap modes.']])}
 <h3>Choose a grid</h3><p>Open Settings → Grid. Choose Square, Isometric, Polar, Hexagonal, Triangular, Dot, or No grid. Set the grid size in mm. Polar also has an angle setting for its spokes. Each grid snaps to its own points.</p>
 <h3>Snap to geometry</h3><p>In Settings → Snapping, turn grid snapping and individual object modes on or off. Intersection, Nearest, Centre, Tangent and Perpendicular help place points relative to existing geometry. A marker shows the snap you are about to use.</p><p>Visible locked shapes can provide snap references. Hidden shapes cannot. Freehand drawing ignores grid snapping. Exact values entered in Properties are not rounded to the grid.</p>
 <div class="help-note">If points keep jumping, press <kbd>S</kbd> to pause snapping. For exact size or position, select the object and type its values in Properties.</div>
 <h3>Appearance</h3><p>Settings → Appearance switches between Dark and Light mode. Default Artwork follows the canvas theme; it exports as black in SVG in both modes.</p>`},
 {id:'drawing',title:'Drawing shapes & arcs',icon:'shapes',summary:'Create basic geometry, open paths and circular arcs.',keywords:'rectangle circle ellipse polygon star heart points line polyline freehand centre center three point start end arc arch sides',body:`
 <p>New objects go into the active layer. Make sure that layer is visible and unlocked before drawing.</p>
 ${table(['Tool','How to draw'],[['Rectangle · R','Drag from one corner to the opposite corner. Hold Shift for a square.'],['Circle · C','Drag from the centre out to the radius.'],['Ellipse · E','Drag opposite corners of its bounding box. Hold Shift for a circle.'],['Polygon · Y','Drag from the centre to a vertex. Use ↑ / ↓ for 3–64 sides; hold Shift to constrain rotation.'],['Star · Shift+Y','Drag from the centre to an outer tip. Use ↑ / ↓ for 3–64 points (default 5). Inner radius is 40% of outer radius; Shift constrains rotation to 15°.'],['Heart','In Shapes, drag opposite bounding corners. Hold Shift for equal width and height. The closed, unfilled heart uses editable curves and the active layer’s colour.'],['Line · L','Drag from one endpoint to the other. Hold Shift for 45° directions.'],['Polyline · P','Click each point, then Enter or double-click to finish. Backspace removes the last point.'],['Freehand · F','Press, draw and release for a smooth open stroke.']])}
 <h3>Three ways to draw an arc</h3>${diagram('Three arc points: start, bend and end','<path d="M65 90Q160-35 255 90" stroke="var(--chrome-accent)"/><circle cx="65" cy="90" r="4"/><circle cx="160" cy="27.5" r="4"/><circle cx="255" cy="90" r="4"/><path d="M70 100h180" stroke-dasharray="4 4"/>')}
 ${table(['Arc tool','Point order'],[['Centre arc · A','Drag from centre to radius to create a semicircle. Select it to adjust Radius, Start and Sweep, or use its dedicated handles.'],['Three-point arc · Shift+A','Click start, a point on the curve, then end.'],['Start–end arc','Click start, then end, then move and click to choose the bend. Hold Shift to snap the sweep to 15° steps.']])}
 <p>Arcs stay open and unfilled. Escape cancels an unfinished arc; Backspace goes back a step in the click-based tools. Open the Arcs menu directly above Text to choose a variant.</p>`},
 {id:'generators',title:'Generators',icon:'wand',summary:'Build editable mechanical profiles, enclosures, patterns and packaging nets.',keywords:'gear spur helical bevel rack pinion sprocket timing pulley thread bolt nut washer cam cycloidal harmonic polynomial enclosure structural box finger joint tabs t-slot living hinge flexure kerf packaging carton tray fold truss framework warren pratt howe voronoi spirograph cycloid maze labyrinth halftone stipple perlin noise waveform seed image holes',body:`
 ${steps(['Open the wand icon on the left toolbar and choose a generator.','Choose a profile and edit its dimensions in mm. The preview updates automatically; Guides toggles reference geometry.','Check the derived dimensions and any validation message. Reset parameters restores the current profile defaults.','Click Insert paths to add the result at the centre of the current view, in the active layer. Undo removes the entire insertion.'])}
 ${table(['Generator','Profiles'],[['Involute gear','Spur, helical transverse section, bevel outer-end approximation, and rack & pinion. Module, teeth, pressure angle, backlash and bore are editable.'],['Sprocket & timing pulley','Custom circular roller seats, trapezoidal pulley grooves or rounded grooves. Set pitch, teeth and groove/roller dimensions.'],['Thread & fastener','Custom external thread axial section, bolt side silhouette, hex nut top view and washer.'],['Cam profile','Cycloidal, simple harmonic or 3–4–5 polynomial rise/return. Set base radius, lift and dwell angles. Roller radius zero gives a knife-edge follower.'],['Box & finger joints','Closed six-panel and open five-panel boxes, tab/slot joint pairs and T-slot nut-capture joints. Enter outside box dimensions and measured sheet thickness.'],['Flexure & living hinge','Vertical/horizontal staggered open slits or closed rounded slots. Control borders, spacing, bridges and expected cut width.'],['Packaging & die-cut nets','Reverse-tuck carton, slotted shipping carton or fold-up glued tray. Panel dimensions are crease-to-crease. Blue dashed fold paths are inserted on Engrave Path.'],['Truss & framework','Warren, Pratt and Howe cut profiles or a rectangular lattice. Set span, height, bay count and member width.'],['Voronoi pattern','Seeded polygon cells with adjustable border, material web and relaxation.'],['Spirograph & cycloid','Inside/outside rolling circles and a cycloid along a line. Set radii, pen offset and revolutions.'],['Maze & labyrinth','Seeded rectangular wall lines or closed wall outlines, plus a circular single-route labyrinth. Guides show the rectangular maze solution.'],['Halftone & stipple','Choose a local image for square, hexagonal or seeded points. Darker pixels make larger holes; adjust contrast, invert, diameter and material gap.'],['Noise & waveform','Sine or seeded Perlin waves as open lines or closed strips inside a panel border.']])}
 <h3>What gets inserted?</h3><p>Unfilled editable paths. Holes are contours inside each part; use Explode to separate them. Rack and pinion are two objects. Preview guides and part labels are never inserted. Packaging folds are real open paths on Engrave Path, separate from the net outline on the active layer. Show and unlock both destinations before inserting; the complete result is one undo step. Hinge slit cuts stay open; rounded slots, panel borders and framework openings stay closed. Generated paths work with node editing, layer transfers, SVG/DXF export and .vectora documents. Changing a generator later creates a new result; it does not parametrically update existing paths.</p>
 <h3>Profile scope</h3><p>These are 2D profiles and views. Helical sections do not contain an axial helix; bevel profiles use an outer-end approximation. Gear roots use radial connections without cutter fillets or undercut. Sprockets, pulleys and fasteners have custom editable dimensions rather than certified standard tooth or thread forms. Curved generated profiles are sampled to approximately 0.015 mm chord tolerance; bore circles remain native curves.</p>
 <h3>Enclosures &amp; sheet patterns</h3><p>Box panels have complementary finger joints and are laid out separately. Clearance widens notches; it is not automatic laser kerf compensation. T-slot joints contain an open nut pocket in the upright and a bolt hole in the receiver plate. Living-hinge patterns check remaining webs against the entered cut width but do not predict a bend radius. Test a material coupon to choose the spacing. Packaging nets need crease and board-thickness allowances set for your stock. Truss generators create geometry without calculating load capacity.</p><h3>Pattern controls</h3><p>New seed changes random patterns; entering the same seed and dimensions reproduces them. Voronoi webs, image-hole gaps and wave gaps are geometric clearances before cutting. Excessively dense patterns are blocked with a message. Spirographs may cross themselves; whole periods close and partial periods stay open. The circular labyrinth is one open decorative route.</p><h3>Example: an image cut-out panel</h3><p>Select Cut Path, open Halftone &amp; stipple and click Choose an image. The image stays on your device and fits inside the border without stretching. Dark pixels make larger holes; transparent areas remain solid even when inverted. Set spacing, minimum/maximum hole diameter and minimum material gap, then Insert paths. Use Explode to edit holes separately. The raster image is not inserted or saved with the drawing.</p><h3>Example: a 24-tooth spur gear</h3><p>Select Cut Path, open Involute gear, choose Spur gear and set 24 teeth, module 2, pressure angle 20° and a 5 mm bore. The pitch diameter is 48 mm and outside diameter 52 mm. Insert the paths, then export DXF or SVG.</p>`},
 {id:'editing',title:'Selection & path editing',icon:'nodes',summary:'Select, transform, combine and reshape your objects.',keywords:'align distribute arrange centre center middle reference spacing move resize rotate flip copy paste weld subtract intersect boolean union difference join explode close split smooth corner nodes bezier handles delete trim dissect fillet chamfer bevel radius rounding rectangular circular pattern array repeat rows columns centre holes slots',body:`
 <p>For selections over 100 objects, moving, resizing, rotating and marquee selection use a combined bounds preview. Individual selection boxes return after the gesture; all geometry retains its full precision.</p>
 <h3>Select &amp; transform</h3><p>Press <kbd>V</kbd>. Click an object, or drag a box around objects to select fully enclosed items. Shift-click toggles an object; Shift-drag adds to the selection. Hidden or locked objects cannot be edited.</p><p>Drag a selected object to move it, square handles to resize, and the round handle above it to rotate. Shift constrains resizing or snaps rotation to 15°. Properties gives exact position, size and rotation controls.</p><p>The small overlapping squares below a selection duplicate it 10 mm right and down. Copy and paste also work through the right-click menu. Right-click an empty point and choose Paste to place a copy there.</p>
 <h3>The selection menu</h3>${table(['Command','Result'],[['Close path','Connects the nearest endpoints of selected open paths on the same layer and closes the final gap. One open curve can close by itself; a lone straight line cannot.'],['Join','Combines selected objects on one layer so they act as one shape. It preserves each contour without joining endpoints or merging overlapping regions.'],['Explode','Separates a joined / compound shape into independent contour paths.'],['Flip horizontal / vertical','Mirrors the selection around its combined centre.'],['Convert to path','Turns selected text into separate editable contours.']])}
 <h3>Align and distribute</h3>${steps(['Select two or more objects. Shift-click the reference object last; its position stays fixed when aligning. If it is already selected, Shift-click it off and on again to make it the reference.','Open Align and distribute in the selection menu, then choose an alignment icon: left, centre, right, top, middle or bottom. The button tooltip names the reference object. Alignment uses each object’s axis-aligned bounds, including dimension and callout labels.','For even spacing, select at least three objects and choose Distribute horizontally or Distribute vertically in the same pop-out. Centres are spaced evenly between the two end objects, which stay fixed. Objects of different sizes can have different gaps.'])}<p>Actions apply exact positions without grid snapping, across visible, unlocked layers. Editable text, circular arcs, compound paths and annotations retain their styles and editability. Each action is one Undo step, and Undo/Redo preserves which object is the alignment reference. An already aligned selection adds no history step. After a marquee selection, the last object in its selection order is the reference.</p>
 <h3>Weld, subtract or intersect shapes</h3>${steps(['Select two or more closed paths on the same visible, unlocked layer. Convert text to paths first.','Open Shape operations in the floating selection menu, then choose the Weld, Subtract or Intersect icon. Hover for a tool name, or find the same action through tool search.','Weld merges areas. Subtract removes the upper shapes from the bottom shape in drawing order, regardless of selection order. Intersect keeps only the area shared by every selected shape.','The action applies immediately. The result keeps the bottom shape’s layer, style and opacity; Undo restores all original shapes together.'])}<p>Curves and holes stay editable. Disconnected areas become one compound shape; use Explode to separate its contours. Open paths, dimensions and editable text cannot be combined. An empty or excessively complex result leaves the drawing unchanged and reports the issue through Notifications.</p><h3>Example: a panel with circular holes</h3><p>Draw the panel first, then circles over it on the same layer. Select the panel and circles, open Shape operations, then click Subtract. The circles become holes in the panel outline.</p>
 <h3>Repeat objects in a pattern</h3>${steps(['Select one or more objects and click Pattern in the floating selection menu, or search for Rectangular pattern / Circular pattern.','Rectangular: enter rows, columns and the repeat spacing in mm. Negative spacing repeats left or up. Spacing is measured between corresponding positions, not the empty gap between objects.','Circular: enter the total number of instances and angle. Set Centre X/Y or choose Pick centre on canvas; the centre follows grid snapping when enabled. Escape or Cancel pick returns to the settings.','Enable Rotate copies to turn each copy around the centre. Turn it off to keep the original orientation as copies move around the centre.','Check the blue preview, then Apply. Counts include the unchanged original. A full turn has no duplicate at the end; partial arcs include both ends.'])}<p>Multiple selected objects repeat together, retaining their layers, colours, editable text and arc controls. Copies remain separate objects. Cancel or Escape discards the preview; Undo removes the entire new pattern in one step. Patterns allow up to 1,000 total objects and limit complex geometry to keep previews responsive.</p>
 <h3>Offset a path</h3><p>Choose Offset path in the selection menu, right-click menu or tool search. You can start without a selection: click Select path, then click a visible, unlocked closed path on the canvas. Escape cancels path picking. Enter the distance in mm, choose Inward or Outward, and Round, Sharp or Bevel corners. Check the blue preview, then Create offset. Each result is a new unfilled path on its original layer; originals stay unchanged. Compound holes are preserved, and multiple shapes offset independently. Join related contours first to offset a shape with holes together. Convert editable text first. Open paths and annotations are excluded. A large inward distance can remove small features or collapse a shape; reduce the distance if creation is blocked. Curves are approximated within 0.01 mm; very sharp miters are capped. Cancel or Escape discards the preview; Undo removes all offsets in one step.</p>
 <h3>Edit individual nodes</h3>${steps(['Choose Node editing (<kbd>N</kbd>) and click a path.','Drag a square node to move it. Drag its Bézier handles to adjust the curve.','Double-click a line or curve to add a node. Select a node and press Delete to remove it.','Right-click a node for Fillet, Chamfer, Smooth node, Corner node, Split path or Delete node.'])}
 <h3>Round or bevel corners</h3>${steps(['Choose Node editing and click a corner. Shift-click additional corners to select them together.','Right-click a selected corner and choose Fillet for a rounded corner, or Chamfer for a straight bevel.','Enter an exact radius or distance in millimetres. Chamfer measures the distance along each adjoining edge.','Check the blue preview, then Apply. Undo restores all edited corners together; Cancel or Escape leaves the drawing unchanged.'])}<p>These tools work on corners between straight edges, including rectangles, polygons and polylines. Open endpoints and curved junctions are excluded. Reduce the value if adjoining corner trims overlap.</p>
 <p>Splitting an open path at an interior node creates two paths. Splitting a closed path opens it at that node. Convert editable text to paths before editing its nodes.</p>
 <h3>Remove part of a line</h3><p>Dissect delete (<kbd>K</kbd>) removes a section between path points or intersections. Line delete (<kbd>Shift</kbd> + <kbd>K</kbd>) removes the whole clicked object. Hover to inspect the highlighted target, then click. Undo restores the change.</p>`},
 {id:'text',title:'Text & fonts',icon:'text',summary:'Type on the canvas, choose a font and edit letter outlines.',keywords:'letters lettering type font single line engraving hershey relief outline convert contour text size',body:`
 ${steps(['Choose Text (<kbd>T</kbd>) and click the canvas. Type directly where you clicked.','Enter adds a line. Click outside, press Tab, or use Ctrl/⌘+Enter to finish. Escape cancels the edit.','Select the text and open Properties to choose a font and size in mm.','Double-click the text, or use Properties → Edit text, to change the wording.'])}
 <h3>Editable text or paths?</h3><p>Text stays editable until you choose Convert to path in the selection menu. Conversion creates separate paths for each contour: the outer and inner outlines of an O are independent objects, as are dots and accents. Select all related contours before moving an entire converted letter. Undo restores editable text.</p>
 <h3>Choose the right font</h3>${table(['Font group','Useful for'],[['General','Lato, PT Serif and Space Mono for everyday lettering.'],['Single-line / engraving','Hershey Sans 1-stroke and Relief Single Line for open engraving paths instead of doubled outlines.'],['Technical / CAD','FreeMono, Inter and JetBrains Mono for clear technical labels.'],['Display','Oswald, Montserrat and Bebas Neue for strong lettering.'],['Stencil','Allerta Stencil and Saira Stencil One for bridged letter shapes.']])}
 <div class="help-note">Single-line fonts display as text while you type. Convert to path, or export DXF, to use their original stroke geometry. Ordinary fonts convert to outlines.</div>${go('examples','Make a simple label')}`},
 {id:'layers',title:'Layers & colour',icon:'layers',summary:'Choose the destination and operation for every object.',keywords:'artwork cut engrave construction red blue magenta white black colour color fill bucket overlap intersection lens no fill move layer hidden locked',body:`
 ${table(['Layer','Purpose'],[['Artwork','General drawing, text, fills and annotations. White on the dark canvas, charcoal on the light canvas; default SVG output is black.'],['Cut Path · red','Cutting outlines. Exported as red in SVG and on cut layers in DXF.'],['Engrave Path · blue','Engraving geometry, exported separately from cut paths.'],['Construction Path · magenta','Drawing guides. Excluded from SVG and DXF exports.']])}
 <h3>Organise objects</h3><p>Open Layers on the right. Click a layer name to make it active for new objects. Expand a layer to select its objects. The eye controls visibility; the lock prevents editing.</p><p>Move an object with Select → right-click → Layer, or drag its row onto another visible, unlocked layer. Dragging a selected object’s row moves the selection together. Hold near the top or bottom of the list to scroll. Dimensions and callouts belong in Artwork.</p>
 <h3>Choose a colour</h3><p>Open Fill &amp; appearance using the palette icon on the right toolbar. Drag the colour area to adjust saturation and brightness, use the hue and opacity sliders, or enter hex and RGB values. Arrow keys adjust the colour area; Shift makes larger steps. Colour changes update selected Artwork and the Fill tool; unfilled paths keep their outlines. Cut, Engrave and Construction retain their operation colours. Each completed adjustment is one Undo step.</p><p>The plus button keeps up to 12 swatches for this session. No fill switches the Fill tool to clearing enclosed regions.</p>
 <h3>Gradient and pattern fills</h3><p>The Gradient tab provides linear or radial blends with 2–8 editable colour stops, stop positions, stop opacity, angle and overall opacity. Pattern offers stripes, crosshatch, dots and checkerboard, with foreground/background colours, transparency, size in millimetres, angle and detail. Each tab has a live preview. Switching tabs chooses the paint for the next Fill click without changing your selection; editing controls also updates selected filled Artwork. No fill clears regions in every mode.</p><p>Paint appearance is saved with the drawing and retained in SVG, PNG and PDF exports. PDF preserves transparent gradient fills as images at up to 300 DPI; other artwork and outlines remain vector. DXF exports the region boundaries, not gradient colours or decorative pattern tiles.</p>
 <h3>Fill a bounded area</h3>${steps(['Choose Colour fill (<kbd>B</kbd>), immediately above Delete tools.','Open Fill &amp; appearance using the palette icon on the right toolbar, then choose a colour and opacity. No fill is selected initially.','Click inside the enclosed region to fill only that area. Overlapping outlines form separate regions.','Choose No fill in the right Fill &amp; appearance panel and click a coloured region to remove its colour.'])}
 <p>Colour, gradient and pattern fills always create or recolour objects in the default Artwork layer, regardless of the active drawing layer. Artwork must be visible and unlocked. The active drawing layer stays unchanged. Fills are separate editable objects. Visible outlines, including locked outlines, can form region boundaries. A gap in the boundary means there is no enclosed region to fill. Click inside the area rather than on its edge.</p><div class="help-note">Moving between operation layers applies the destination layer’s style. Keep coloured presentation artwork in Artwork and cutting outlines in Cut Path.</div>${go('examples','Fill only an intersection')}`},
 {id:'images',title:'Images & tracing',icon:'image',summary:'Turn a bitmap image into editable vector geometry.',keywords:'raster vector tracing png jpg jpeg webp gif bmp outline center centre line fill threshold contrast brightness invert simplify',body:`
 ${steps(['Open Images in the left toolbar, then Raster to vector.','Click anywhere in “Start with an image” to choose a PNG, JPEG, WebP, GIF or BMP.','Compare Original or Binary input with the live vector preview.','Choose Outline, Center line or Fill, then adjust the controls.','Set the insertion scale, check the resulting size, and insert into the active visible, unlocked layer.'])}
 ${table(['Mode','Use it for'],[['Outline','Closed contours around the dark areas of an image.'],['Center line','Open paths through strokes, useful for line drawings.'],['Fill','Filled geometry with holes preserved.']])}
 <h3>Get a cleaner trace</h3><p>Threshold separates dark and light pixels. Brightness, Contrast and Invert help isolate the subject. Noise reduction removes small fragments. Path simplification reduces complexity; Curve fitting and Corner sensitivity tune Outline and Fill results.</p><p>Use a clear, high-contrast source for simpler geometry. Click the input preview again to replace the image. Cancel closes the dialog without inserting anything.</p><div class="help-note">Tracing accepts images up to 20 MB and 40 million pixels, and scales tracing to a maximum 1600-pixel dimension. Fine details in a large source can be lost; inspect the vector preview before inserting.</div>${go('editing','Clean up nodes after tracing')}`},
 {id:'dimensions',title:'Dimensions & callouts',icon:'dimensions',summary:'Measure your design and add explanatory labels.',keywords:'aligned linear radial radius diameter leader annotation measurement label',body:`
 <p>Open Dimensions in the left toolbar. Keep an Artwork layer active when adding annotations.</p>
 ${table(['Tool','How to place it'],[['Aligned dimension · D','Click two reference points, then click to place the dimension parallel to them.'],['Linear dimension','Click two reference points, then place the label. Its placement chooses horizontal or vertical measurement.'],['Radial dimension','Click a circle or circular arc, then place the radius label.'],['Diameter dimension','Click a circle or circular arc, then place the diameter label.'],['Leader callout','Click the tip, elbow and label position, then enter the callout text. Double-click the finished callout to edit it.']])}
 <p>Measurements are in millimetres. Escape cancels an unfinished annotation. Select an annotation to move or delete it like other objects.</p><div class="help-note">Dimensions record reference measurements; they are not constraints that drive or automatically follow the original shape. Check them again after changing the measured geometry.</div><p>SVG includes visible annotation lines and labels. For DXF, turn on Include artwork; annotations export on the ANNOTATIONS layer.</p>`},
 {id:'files',title:'Save & export',icon:'save',summary:'Keep editable projects and send vector files to other apps.',keywords:'document new open save as export svg dxf laser compatible r12 techsoft pdf png print dpi transparent download file browser cache recovery refresh lost black white',body:`
 <h3>Canvas size</h3><p>Choose Infinite or a measured canvas on first launch and when creating a document. Custom sizes accept mm, cm or inches. Use File → Canvas size to change the active canvas later, with Undo/Redo. The boundary starts at (0, 0) and is a visual guide: objects can extend outside it, and exports use their existing settings. Saved documents and browser recovery restore the canvas size and view; older files open as Infinite.</p><h3>Keep an editable project</h3><p>Click the project name at the top to rename it. File → Save (${command('S')}) saves a .vectora document containing your layers, geometry, text, canvas size and view. Save As creates a separate file; Open restores a saved .vectora document.</p><p>When supported, a native file picker lets Save update the selected file. Other browsers handle it as a download; their download preferences decide whether a Save window appears. A cancelled save does not count as a completed save.</p><p>New document and the + button ask for an Infinite canvas or a preset/custom size, then open a new tab; Open adds a saved document in another tab. Click a tab to switch drawings. Each keeps its own selection, active layer, view, undo/redo history and save target. Save and export use the active document. A dot marks unsaved changes. Close a tab with its × button; unsaved changes require confirmation. Scroll the tab row when it overflows, or focus a tab and use Left/Right and Home/End. Closing the last tab leaves a blank document.</p>
 <h3>Choose an export</h3><p>File → Export… opens a centred dialog with a live preview. Choose a format on the left, name the file and select Drawing or Selection. Advanced options contain layer checkboxes; checked hidden layers are included, while Construction is always excluded. Format settings are remembered for this session. PNG offers DPI, proportional pixel sizing and transparent or coloured backgrounds. SVG offers physical width, margin and layer groups. PDF offers fitted or standard pages, orientation, margin and exact scale; reduce scale if the drawing does not fit. Both DXF modes offer curve tolerance and Move to origin without changing the drawing. Standard DXF preserves recognised circles and circular arcs as native entities; other curves use the chosen tolerance. Laser-compatible DXF deliberately uses basic straight lines for restrictive importers. Neither mode guarantees support in every application: check imported dimensions and contours before cutting.</p><p>Exports omit the grid, rulers, selection handles and Construction Path. PNG is limited to 32 megapixels and 16,384 pixels per side; PDF supports up to 5,080 mm per side. Oversized exports show an error without changing the drawing. Use SVG for larger designs.</p>${table(['Format','What is included'],[['SVG · File → Export… → SVG','Visible Artwork, Cut Path and Engrave Path, including locked objects. Exact curves, colours, fills and holes; text becomes font-independent outline geometry. Default Artwork exports black in either theme.'],['PDF · File → Export… → PDF','One vector page fitted to the visible design at actual millimetre size. Uses the same visible layers, colours, holes and black Artwork as SVG. Lettering is outlined; annotation labels use bundled Lato fitted to their original width. Unsupported callout characters show an error; use PNG/SVG for system-font fallbacks. Print at 100% / actual size.'],['PNG · File → Export… → PNG','Transparent image at 300 DPI, fitted to the visible design. Includes physical-resolution metadata and the same visible layers/colours as SVG.'],['DXF · File → Export… → DXF','Cut and engraving paths in millimetres, on separate layers. Check Artwork under Advanced → Layers for Artwork and annotations. Exports geometry rather than coloured fill rendering.']])}
 <p>Construction is excluded from all formats. Hidden objects are excluded from SVG, PDF and PNG; layer visibility does not exclude geometry from DXF. The grid, selection handles and menus never export.</p>
 <h3>Laser-compatible DXF</h3><p>Open File → Export… → DXF, choose Laser-compatible DXF (R12) from Compatibility, then Export DXF. Tool search opens the DXF tab with this mode selected. The file uses older ASCII DXF R12 and basic line segments for laser software that cannot read standard polylines. Closing edges and separate hole outlines are retained. Physical size and original position are preserved unless Move to origin is checked. Set curve tolerance in Advanced; lower values create more segments. Include Artwork using the layer checkboxes.</p><p>Choose millimetres in the receiving software: R12 does not reliably carry unit metadata. Annotation labels remain TEXT on ANNOTATIONS; the compatibility format accepts ASCII and the diameter symbol, and reports unsupported labels. Standard DXF (2000) is available in the same dropdown. The mode is remembered, and switching modes preserves layer, origin and tolerance settings.</p>
 <h3>Browser recovery</h3><p>Vectora keeps local copies of all open tabs and restores them, including the active tab, when you return. Undo history and file-picker permissions last only for the current session. Clearing site data removes these copies. Save a .vectora file for a separate, portable copy. A browser-controlled confirmation can appear when refreshing or leaving the page after interaction.</p><div class="help-note">Exporting does not change your document or its undo history. Save .vectora when you need to keep text editable and retain the original document structure.</div>`},
 {id:'examples',title:'How-to examples',icon:'shapes',summary:'Four short projects to put the tools together.',keywords:'tutorial walkthrough how to badge label washer hole overlap fill lens trace logo',body:`
 <div class="help-recipes"><article><span class="help-eyebrow">01 / LETTERING</span><h3>Make a 60 × 30 mm label</h3>${diagram('Rectangular label with text and a larger cut outline','<rect x="57" y="16" width="206" height="88" stroke="var(--color-cutline)"/><rect x="70" y="29" width="180" height="62"/><text x="160" y="68" text-anchor="middle" fill="currentColor" stroke="none" font-size="22">VECTORA</text>')}${steps(['On Artwork, draw a rectangle and set Width to 60 mm and Height to 30 mm in Properties.','Use Text to add a name. Choose its font and size in Properties, then position it over the rectangle.','Select the rectangle. Open Offset path, set Outward, Round and 3 mm, then create the offset. Move the new outer path to Cut Path in Layers.','Save .vectora, then export SVG for the complete visible design.'])}</article>
 <article><span class="help-eyebrow">02 / CUT PATHS</span><h3>Draw a washer outline</h3>${diagram('Two concentric circles defining a washer','<circle cx="160" cy="60" r="44" stroke="var(--color-cutline)"/><circle cx="160" cy="60" r="15" stroke="var(--color-cutline)"/><path d="M108 60h104M160 8v104" stroke-dasharray="3 5" opacity=".4"/>')}${steps(['Make Cut Path active and draw a circle. Set Width and Height to 40 mm.','Draw a second circle with Width and Height of 12 mm.','Use Properties to centre them: set the outer X/Y to 0/0 mm and the inner X/Y to 14/14 mm.','Export DXF. The two closed paths define the outer edge and inner hole; assign their cutting operation in your manufacturing software.'])}</article>
 <article><span class="help-eyebrow">03 / COLOUR</span><h3>Fill only an intersection</h3>${diagram('Two overlapping circles with only their shared lens filled','<path d="M160 20a46 46 0 0 1 0 80 46 46 0 0 1 0-80Z" fill="var(--chrome-accent)" fill-opacity=".4" stroke="none"/><circle cx="138" cy="60" r="46"/><circle cx="182" cy="60" r="46"/>')}${steps(['On Artwork, draw two overlapping circles.','Choose a colour in the right Fill &amp; appearance panel, then activate Colour fill.','Click in the shared middle area, away from the outlines. Only the intersection fills.','To clear it, choose No fill and click that area again. The outlines remain.'])}</article>
 <article><span class="help-eyebrow">04 / TRACING</span><h3>Turn a logo into paths</h3>${diagram('Pixelated source becoming a smooth vector curve','<path d="M48 90V60h16V36h20V22h24v14h20v24h16v30Z" stroke-dasharray="3 3"/><path d="M165 60h30m-8-7 8 7-8 7"/><path d="M220 90c0-90 60-90 60 0Z" stroke="var(--chrome-accent)"/>')}${steps(['Open Images → Raster to vector and choose a high-contrast logo.','Choose Outline. Adjust Threshold until the Binary input keeps the detail you want.','Use Noise reduction and Path simplification sparingly; compare the live vector preview.','Check the physical size, insert, and use Node editing to tidy any unwanted points. Save before exporting.'])}</article></div>`},
 {id:'troubleshooting',title:'Troubleshooting',icon:'help',summary:'Quick checks when something does not behave as expected.',keywords:'help problem issue error warning notification missing disabled cannot fill draw locked hidden snap no cut lines white export',body:`
 <h3>I cannot draw or select an object</h3><p>Check that the active layer is visible and unlocked. Press <kbd>V</kbd> for Select. Some open paths select by their stroke, so click the line rather than the space around it.</p>
 <h3>Fill does nothing, or reaches the wrong area</h3><p>Pick a colour in the right Fill &amp; appearance panel first: the default is No fill. Click inside a closed region, not on its boundary. Zoom in to check for tiny gaps or extra crossings. Only visible outlines contribute boundaries.</p>
 <h3>A command is disabled</h3><p>Check the selection and finish any active drawing or text edit. Join needs at least two objects on the same layer. Explode needs a compound shape. Close path needs an eligible open path; Convert to path needs editable text.</p>
 <h3>Export says there are no cut lines</h3><p>Move your cutting geometry into Cut Path, or check Artwork under Advanced → Layers for DXF. SVG exports visible Artwork as well as Cut and Engrave paths.</p>
 <h3>The exported Artwork looks different</h3><p>Default Artwork is white only for visibility on the dark canvas. SVG exports it as black. Explicit colour fills and operation colours remain unchanged. DXF carries geometry, so filled areas may appear as outlines in another app.</p>
 <h3>Where did a message go?</h3><p>Click the bell at the bottom of the right toolbar. Notifications stay inside that menu until dismissed or replaced; it keeps the latest 15 messages.</p>
 <h3>How do I undo an accidental change?</h3><p>Use ${command('Z')}. If you have not saved a separate file, the browser working copy may restore the latest state when you return. Clearing site data removes that recovery copy.</p>
 <h3>I cannot find a tool</h3><p>Use the magnifying glass in the top toolbar and search by name, such as “arc”, “convert” or “export”. Greyed-out results explain what must be selected first.</p>${go('shortcuts','Open the shortcut reference')}`}
];
